<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-operator_panel']['en-us'] = "Operator Panel";
$text['title-operator_panel']['en-gb'] = "Operator Panel";
$text['title-operator_panel']['ar-eg'] = "";
$text['title-operator_panel']['de-at'] = "Bedienfeld"; //copied from de-de
$text['title-operator_panel']['de-ch'] = "Bedienfeld"; //copied from de-de
$text['title-operator_panel']['de-de'] = "Bedienfeld";
$text['title-operator_panel']['es-cl'] = "Panel de Operador";
$text['title-operator_panel']['es-mx'] = "Panel de Operador"; //copied from es-cl
$text['title-operator_panel']['fr-ca'] = "Operator Panel"; //copied from fr-fr
$text['title-operator_panel']['fr-fr'] = "Operator Panel";
$text['title-operator_panel']['he-il'] = "לוח מפעיל";
$text['title-operator_panel']['it-it'] = "Pannello Operatore";
$text['title-operator_panel']['nl-nl'] = "Operator paneel";
$text['title-operator_panel']['pl-pl'] = "Panel operatora";
$text['title-operator_panel']['pt-br'] = "Painel do Agente";
$text['title-operator_panel']['pt-pt'] = "Painel do Agente";
$text['title-operator_panel']['ro-ro'] = "";
$text['title-operator_panel']['ru-ru'] = "Панель Оператора";
$text['title-operator_panel']['sv-se'] = "Telefonist Panel";
$text['title-operator_panel']['uk-ua'] = "ÐŸÐ°Ð½ÐµÐ»ÑŒ Ð¾Ð¿ÐµÑ€Ð°Ñ‚Ð¾Ñ€Ð°";

$text['label-status_on_demand']['en-us'] = "On Demand";
$text['label-status_on_demand']['en-gb'] = "On Demand";
$text['label-status_on_demand']['ar-eg'] = "";
$text['label-status_on_demand']['de-at'] = "Bei Bedarf"; //copied from de-de
$text['label-status_on_demand']['de-ch'] = "Bei Bedarf"; //copied from de-de
$text['label-status_on_demand']['de-de'] = "Bei Bedarf";
$text['label-status_on_demand']['es-cl'] = "A Pedido";
$text['label-status_on_demand']['es-mx'] = "A Pedido"; //copied from es-cl
$text['label-status_on_demand']['fr-ca'] = "Sur Demande"; //copied from fr-fr
$text['label-status_on_demand']['fr-fr'] = "Sur Demande";
$text['label-status_on_demand']['he-il'] = "על פי דרישה";
$text['label-status_on_demand']['it-it'] = "Su Richiesta";
$text['label-status_on_demand']['nl-nl'] = "Op Aanvraag";
$text['label-status_on_demand']['pl-pl'] = "Na żądanie";
$text['label-status_on_demand']['pt-br'] = "Não Receber";
$text['label-status_on_demand']['pt-pt'] = "A Pedido";
$text['label-status_on_demand']['ro-ro'] = "";
$text['label-status_on_demand']['ru-ru'] = "По требованию";
$text['label-status_on_demand']['sv-se'] = "På Begäran";
$text['label-status_on_demand']['uk-ua'] = "";

$text['label-status_on_break']['en-us'] = "On Break";
$text['label-status_on_break']['en-gb'] = "On Break";
$text['label-status_on_break']['ar-eg'] = "";
$text['label-status_on_break']['de-at'] = "In Pause"; //copied from de-de
$text['label-status_on_break']['de-ch'] = "In Pause"; //copied from de-de
$text['label-status_on_break']['de-de'] = "In Pause";
$text['label-status_on_break']['es-cl'] = "En Pausa";
$text['label-status_on_break']['es-mx'] = "En Pausa"; //copied from es-cl
$text['label-status_on_break']['fr-ca'] = "En Pause"; //copied from fr-fr
$text['label-status_on_break']['fr-fr'] = "En Pause";
$text['label-status_on_break']['he-il'] = "בהפסקה";
$text['label-status_on_break']['it-it'] = "In Pausa";
$text['label-status_on_break']['nl-nl'] = "In de wacht";
$text['label-status_on_break']['pl-pl'] = "Na przerwie";
$text['label-status_on_break']['pt-br'] = "Em Pausa";
$text['label-status_on_break']['pt-pt'] = "Em Pausa";
$text['label-status_on_break']['ro-ro'] = "";
$text['label-status_on_break']['ru-ru'] = "Пауза";
$text['label-status_on_break']['sv-se'] = "På Rast";
$text['label-status_on_break']['uk-ua'] = "ÐÐ° Ð¿ÐµÑ€ÐµÑ€Ð²Ñ–";

$text['label-status_logged_out_or_unknown']['en-us'] = "Logged Out";
$text['label-status_logged_out_or_unknown']['en-gb'] = "Logged Out / Unknown";
$text['label-status_logged_out_or_unknown']['ar-eg'] = "";
$text['label-status_logged_out_or_unknown']['de-at'] = "Abgemeldet / Unbekannt"; //copied from de-de
$text['label-status_logged_out_or_unknown']['de-ch'] = "Abgemeldet / Unbekannt"; //copied from de-de
$text['label-status_logged_out_or_unknown']['de-de'] = "Abgemeldet / Unbekannt";
$text['label-status_logged_out_or_unknown']['es-cl'] = "Desconectado / Desconocido";
$text['label-status_logged_out_or_unknown']['es-mx'] = "Desconectado / Desconocido"; //copied from es-cl
$text['label-status_logged_out_or_unknown']['fr-ca'] = "Déconnexion / Unknown"; //copied from fr-fr
$text['label-status_logged_out_or_unknown']['fr-fr'] = "Déconnexion / Unknown";
$text['label-status_logged_out_or_unknown']['he-il'] = "";
$text['label-status_logged_out_or_unknown']['it-it'] = "Sloggato/Sconosciuto";
$text['label-status_logged_out_or_unknown']['nl-nl'] = "Afgelogged / Onbekend";
$text['label-status_logged_out_or_unknown']['pl-pl'] = "";
$text['label-status_logged_out_or_unknown']['pt-br'] = "Desconectado";
$text['label-status_logged_out_or_unknown']['pt-pt'] = "Desligado / Unknown";
$text['label-status_logged_out_or_unknown']['ro-ro'] = "";
$text['label-status_logged_out_or_unknown']['ru-ru'] = "Вышел из системы / Неизвестен";
$text['label-status_logged_out_or_unknown']['sv-se'] = "Utloggad / Okänd";
$text['label-status_logged_out_or_unknown']['uk-ua'] = "Ð’Ð¸Ð¹ÑˆÐ¾Ð²/Ð½ÐµÐ²Ñ–Ð´Ð¾Ð¼Ð¾";

$text['label-status_logged_out']['en-us'] = "Logged Out";
$text['label-status_logged_out']['en-gb'] = "Logged Out";
$text['label-status_logged_out']['ar-eg'] = "";
$text['label-status_logged_out']['de-at'] = "Abgemeldet"; //copied from de-de
$text['label-status_logged_out']['de-ch'] = "Abgemeldet"; //copied from de-de
$text['label-status_logged_out']['de-de'] = "Abgemeldet";
$text['label-status_logged_out']['es-cl'] = "Desconectado";
$text['label-status_logged_out']['es-mx'] = "Desconectado"; //copied from es-cl
$text['label-status_logged_out']['fr-ca'] = "Déconnexion"; //copied from fr-fr
$text['label-status_logged_out']['fr-fr'] = "Déconnexion";
$text['label-status_logged_out']['he-il'] = "";
$text['label-status_logged_out']['it-it'] = "Sloggato";
$text['label-status_logged_out']['nl-nl'] = "Afgelogged";
$text['label-status_logged_out']['pl-pl'] = "Wylogowany";
$text['label-status_logged_out']['pt-br'] = "Desligado"; //copied from pt-pt
$text['label-status_logged_out']['pt-pt'] = "Desligado";
$text['label-status_logged_out']['ro-ro'] = "";
$text['label-status_logged_out']['ru-ru'] = "Вышел из системы";
$text['label-status_logged_out']['sv-se'] = "Utloggad";
$text['label-status_logged_out']['uk-ua'] = "Ð’Ð¸Ð¹ÑˆÐ¾Ð²";

$text['label-status_do_not_disturb']['en-us'] = "Do Not Disturb";
$text['label-status_do_not_disturb']['en-gb'] = "Do Not Disturb";
$text['label-status_do_not_disturb']['ar-eg'] = "";
$text['label-status_do_not_disturb']['de-at'] = "Bitte nicht Stören"; //copied from de-de
$text['label-status_do_not_disturb']['de-ch'] = "Bitte nicht Stören"; //copied from de-de
$text['label-status_do_not_disturb']['de-de'] = "Bitte nicht Stören";
$text['label-status_do_not_disturb']['es-cl'] = "No Molestar";
$text['label-status_do_not_disturb']['es-mx'] = "No Molestar"; //copied from es-cl
$text['label-status_do_not_disturb']['fr-ca'] = "Ne pas Déranger"; //copied from fr-fr
$text['label-status_do_not_disturb']['fr-fr'] = "Ne pas Déranger";
$text['label-status_do_not_disturb']['he-il'] = "נא לא להפריע";
$text['label-status_do_not_disturb']['it-it'] = "Non Disturbare";
$text['label-status_do_not_disturb']['nl-nl'] = "Niet Storen";
$text['label-status_do_not_disturb']['pl-pl'] = "Nie przeszkadzać (DND)";
$text['label-status_do_not_disturb']['pt-br'] = "Não perturbe (DND)";
$text['label-status_do_not_disturb']['pt-pt'] = "Não perturbe (DND)";
$text['label-status_do_not_disturb']['ro-ro'] = "";
$text['label-status_do_not_disturb']['ru-ru'] = "Просьба не беспокоить";
$text['label-status_do_not_disturb']['sv-se'] = "Stör Ej";
$text['label-status_do_not_disturb']['uk-ua'] = "ÐÐµ Ñ‚ÑƒÑ€Ð±ÑƒÐ²Ð°Ñ‚Ð¸";

$text['label-recent_calls']['en-us'] = "Recent Calls";
$text['label-recent_calls']['en-gb'] = "Recent Calls";
$text['label-recent_calls']['ar-eg'] = "";
$text['label-recent_calls']['de-at'] = "Bitte nicht Stören"; //copied from de-de
$text['label-recent_calls']['de-ch'] = "Bitte nicht Stören"; //copied from de-de
$text['label-recent_calls']['de-de'] = "Bitte nicht Stören";
$text['label-recent_calls']['es-cl'] = "No Molestar";
$text['label-recent_calls']['es-mx'] = "No Molestar"; //copied from es-cl
$text['label-recent_calls']['fr-ca'] = "Ne pas Déranger"; //copied from fr-fr
$text['label-recent_calls']['fr-fr'] = "Ne pas Déranger";
$text['label-recent_calls']['he-il'] = "נא לא להפריע";
$text['label-recent_calls']['it-it'] = "Non Disturbare";
$text['label-recent_calls']['nl-nl'] = "Niet Storen";
$text['label-recent_calls']['pl-pl'] = "Nie przeszkadzać (DND)";
$text['label-recent_calls']['pt-br'] = "Chamadas Recentes";
$text['label-recent_calls']['pt-pt'] = "Não perturbe (DND)";
$text['label-recent_calls']['ro-ro'] = "";
$text['label-recent_calls']['ru-ru'] = "Просьба не беспокоить";
$text['label-recent_calls']['sv-se'] = "Stör Ej";
$text['label-recent_calls']['uk-ua'] = "ÐÐµ Ñ‚ÑƒÑ€Ð±ÑƒÐ²Ð°Ñ‚Ð¸";

$text['label-status_available_on_demand']['en-us'] = "Available (On Demand)";
$text['label-status_available_on_demand']['en-gb'] = "Available (On Demand)";
$text['label-status_available_on_demand']['ar-eg'] = "";
$text['label-status_available_on_demand']['de-at'] = "Verfügbar (Bei Bedarf)"; //copied from de-de
$text['label-status_available_on_demand']['de-ch'] = "Verfügbar (Bei Bedarf)"; //copied from de-de
$text['label-status_available_on_demand']['de-de'] = "Verfügbar (Bei Bedarf)";
$text['label-status_available_on_demand']['es-cl'] = "Disponible (A Pedido)";
$text['label-status_available_on_demand']['es-mx'] = "Disponible (A Pedido)"; //copied from es-cl
$text['label-status_available_on_demand']['fr-ca'] = "Disponible (sur demande)"; //copied from fr-fr
$text['label-status_available_on_demand']['fr-fr'] = "Disponible (sur demande)";
$text['label-status_available_on_demand']['he-il'] = "";
$text['label-status_available_on_demand']['it-it'] = "Disponibile (Su Richiesta)";
$text['label-status_available_on_demand']['nl-nl'] = "Beschikbaar (Op Aaanvraag)";
$text['label-status_available_on_demand']['pl-pl'] = "Dostępny (na żądanie)";
$text['label-status_available_on_demand']['pt-br'] = "Não Receber";
$text['label-status_available_on_demand']['pt-pt'] = "Disponível (A Pedido)";
$text['label-status_available_on_demand']['ro-ro'] = "";
$text['label-status_available_on_demand']['ru-ru'] = "Доступен (по требованию)";
$text['label-status_available_on_demand']['sv-se'] = "Tillgänglig (På Begäran)";
$text['label-status_available_on_demand']['uk-ua'] = "Ð”Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð¸Ð¹ (Ð½Ð° Ð²Ð¸Ð¼Ð¾Ð³Ñƒ)";

$text['label-status_available']['en-us'] = "Available";
$text['label-status_available']['en-gb'] = "Available";
$text['label-status_available']['ar-eg'] = "";
$text['label-status_available']['de-at'] = "Verfügbar"; //copied from de-de
$text['label-status_available']['de-ch'] = "Verfügbar"; //copied from de-de
$text['label-status_available']['de-de'] = "Verfügbar";
$text['label-status_available']['es-cl'] = "Disponible";
$text['label-status_available']['es-mx'] = "Disponible"; //copied from es-cl
$text['label-status_available']['fr-ca'] = "Disponible"; //copied from fr-fr
$text['label-status_available']['fr-fr'] = "Disponible";
$text['label-status_available']['he-il'] = "זמין";
$text['label-status_available']['it-it'] = "Disponibile";
$text['label-status_available']['nl-nl'] = "Beschikbaar";
$text['label-status_available']['pl-pl'] = "Dostępny";
$text['label-status_available']['pt-br'] = "Disponível";
$text['label-status_available']['pt-pt'] = "Disponível";
$text['label-status_available']['ro-ro'] = "";
$text['label-status_available']['ru-ru'] = "Доступен";
$text['label-status_available']['sv-se'] = "Tillgänglig";
$text['label-status_available']['uk-ua'] = "Ð”Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð¸Ð¹";

$text['label-meeting']['en-us'] = "On Meeting";
$text['label-meeting']['en-gb'] = "On Meeting";
$text['label-meeting']['ar-eg'] = "";
$text['label-meeting']['de-at'] = "On Meeting"; //copied from de-de
$text['label-meeting']['de-ch'] = "On Meeting"; //copied from de-de
$text['label-meeting']['de-de'] = "On Meeting";
$text['label-meeting']['es-cl'] = "On Meeting";
$text['label-meeting']['es-mx'] = "On Meeting"; //copied from es-cl
$text['label-meeting']['fr-ca'] = "On Meeting"; //copied from fr-fr
$text['label-meeting']['fr-fr'] = "On Meeting";
$text['label-meeting']['he-il'] = "";
$text['label-meeting']['it-it'] = "On Meeting";
$text['label-meeting']['nl-nl'] = "On Meeting";
$text['label-meeting']['pl-pl'] = "On Meeting";
$text['label-meeting']['pt-br'] = "Em Reunião"; //copied from pt-pt
$text['label-meeting']['pt-pt'] = "Em Reunião";
$text['label-meeting']['ro-ro'] = "";
$text['label-meeting']['ru-ru'] = "On Meeting";
$text['label-meeting']['sv-se'] = "On Meeting";
$text['label-meeting']['uk-ua'] = "On Meeting";

$text['label-lunch']['en-us'] = "Lunch";
$text['label-lunch']['en-gb'] = "Lunch";
$text['label-lunch']['ar-eg'] = "";
$text['label-lunch']['de-at'] = "Lunch"; //copied from de-de
$text['label-lunch']['de-ch'] = "Lunch"; //copied from de-de
$text['label-lunch']['de-de'] = "Lunch";
$text['label-lunch']['es-cl'] = "Lunch";
$text['label-lunch']['es-mx'] = "Lunch"; //copied from es-cl
$text['label-lunch']['fr-ca'] = "Lunch"; //copied from fr-fr
$text['label-lunch']['fr-fr'] = "Lunch";
$text['label-lunch']['he-il'] = "";
$text['label-lunch']['it-it'] = "Lunch";
$text['label-lunch']['nl-nl'] = "Lunch";
$text['label-lunch']['pl-pl'] = "Lunch";
$text['label-lunch']['pt-br'] = "Almoço"; //copied from pt-pt
$text['label-lunch']['pt-pt'] = "Almoço";
$text['label-lunch']['ro-ro'] = "";
$text['label-lunch']['ru-ru'] = "Lunch";
$text['label-lunch']['sv-se'] = "Lunch";
$text['label-lunch']['uk-ua'] = "Lunch";

$text['label-snack']['en-us'] = "Snack";
$text['label-snack']['en-gb'] = "Snack";
$text['label-snack']['ar-eg'] = "";
$text['label-snack']['de-at'] = "Snack"; //copied from de-de
$text['label-snack']['de-ch'] = "Snack"; //copied from de-de
$text['label-snack']['de-de'] = "Snack";
$text['label-snack']['es-cl'] = "Snack";
$text['label-snack']['es-mx'] = "Snack"; //copied from es-cl
$text['label-snack']['fr-ca'] = "Snack"; //copied from fr-fr
$text['label-snack']['fr-fr'] = "Snack";
$text['label-snack']['he-il'] = "";
$text['label-snack']['it-it'] = "Snack";
$text['label-snack']['nl-nl'] = "Snack";
$text['label-snack']['pl-pl'] = "Snack";
$text['label-snack']['pt-br'] = "Lanche"; //copied from pt-pt
$text['label-snack']['pt-pt'] = "Lanche";
$text['label-snack']['ro-ro'] = "";
$text['label-snack']['ru-ru'] = "Snack";
$text['label-snack']['sv-se'] = "Snack";
$text['label-snack']['uk-ua'] = "Snack";

$text['label-bathroom']['en-us'] = "Bathroom";
$text['label-bathroom']['en-gb'] = "Bathroom";
$text['label-bathroom']['ar-eg'] = "";
$text['label-bathroom']['de-at'] = "Bathroom"; //copied from de-de
$text['label-bathroom']['de-ch'] = "Bathroom"; //copied from de-de
$text['label-bathroom']['de-de'] = "Bathroom";
$text['label-bathroom']['es-cl'] = "Bathroom";
$text['label-bathroom']['es-mx'] = "Bathroom"; //copied from es-cl
$text['label-bathroom']['fr-ca'] = "Bathroom"; //copied from fr-fr
$text['label-bathroom']['fr-fr'] = "Bathroom";
$text['label-bathroom']['he-il'] = "";
$text['label-bathroom']['it-it'] = "Bathroom";
$text['label-bathroom']['nl-nl'] = "Bathroom";
$text['label-bathroom']['pl-pl'] = "Bathroom";
$text['label-bathroom']['pt-br'] = "Banheiro"; //copied from pt-pt
$text['label-bathroom']['pt-pt'] = "Banheiro";
$text['label-bathroom']['ro-ro'] = "";
$text['label-bathroom']['ru-ru'] = "Bathroom";
$text['label-bathroom']['sv-se'] = "Bathroom";
$text['label-bathroom']['uk-ua'] = "Bathroom";

$text['label-feedback']['en-us'] = "Feedback";
$text['label-feedback']['en-gb'] = "Feedback";
$text['label-feedback']['ar-eg'] = "";
$text['label-feedback']['de-at'] = "Feedback"; //copied from de-de
$text['label-feedback']['de-ch'] = "Feedback"; //copied from de-de
$text['label-feedback']['de-de'] = "Feedback";
$text['label-feedback']['es-cl'] = "Feedback";
$text['label-feedback']['es-mx'] = "Feedback"; //copied from es-cl
$text['label-feedback']['fr-ca'] = "Feedback"; //copied from fr-fr
$text['label-feedback']['fr-fr'] = "Feedback";
$text['label-feedback']['he-il'] = "";
$text['label-feedback']['it-it'] = "Feedback";
$text['label-feedback']['nl-nl'] = "Feedback";
$text['label-feedback']['pl-pl'] = "Feedback";
$text['label-feedback']['pt-br'] = "Feedback"; //copied from pt-pt
$text['label-feedback']['pt-pt'] = "Feedback";
$text['label-feedback']['ro-ro'] = "";
$text['label-feedback']['ru-ru'] = "Feedback";
$text['label-feedback']['sv-se'] = "Feedback";
$text['label-feedback']['uk-ua'] = "Feedback";

$text['label-training']['en-us'] = "Training";
$text['label-training']['en-gb'] = "Training";
$text['label-training']['ar-eg'] = "";
$text['label-training']['de-at'] = "Training"; //copied from de-de
$text['label-training']['de-ch'] = "Training"; //copied from de-de
$text['label-training']['de-de'] = "Training";
$text['label-training']['es-cl'] = "Training";
$text['label-training']['es-mx'] = "Training"; //copied from es-cl
$text['label-training']['fr-ca'] = "Training"; //copied from fr-fr
$text['label-training']['fr-fr'] = "Training";
$text['label-training']['he-il'] = "";
$text['label-training']['it-it'] = "Training";
$text['label-training']['nl-nl'] = "Training";
$text['label-training']['pl-pl'] = "Training";
$text['label-training']['pt-br'] = "Treinamento"; //copied from pt-pt
$text['label-training']['pt-pt'] = "Treinamento";
$text['label-training']['ro-ro'] = "";
$text['label-training']['ru-ru'] = "Training";
$text['label-training']['sv-se'] = "Training";
$text['label-training']['uk-ua'] = "Training";

$text['label-refresh_pause']['en-us'] = "Pause Refresh";
$text['label-refresh_pause']['en-gb'] = "Pause Refresh";
$text['label-refresh_pause']['ar-eg'] = "";
$text['label-refresh_pause']['de-at'] = "Seite neu laden deaktivieren"; //copied from de-de
$text['label-refresh_pause']['de-ch'] = "Seite neu laden deaktivieren"; //copied from de-de
$text['label-refresh_pause']['de-de'] = "Seite neu laden deaktivieren";
$text['label-refresh_pause']['es-cl'] = "Actualizar Pausa";
$text['label-refresh_pause']['es-mx'] = "Actualizar Pausa"; //copied from es-cl
$text['label-refresh_pause']['fr-ca'] = "Pause Actualiser"; //copied from fr-fr
$text['label-refresh_pause']['fr-fr'] = "Pause Actualiser";
$text['label-refresh_pause']['he-il'] = "עצור רענון";
$text['label-refresh_pause']['it-it'] = "Interrompi";
$text['label-refresh_pause']['nl-nl'] = "Stop verversen";
$text['label-refresh_pause']['pl-pl'] = "Pauzuj odświeżanie";
$text['label-refresh_pause']['pt-br'] = "Pausar Atualização";
$text['label-refresh_pause']['pt-pt'] = "Pausa Atualizar";
$text['label-refresh_pause']['ro-ro'] = "";
$text['label-refresh_pause']['ru-ru'] = "Приостановить обновление";
$text['label-refresh_pause']['sv-se'] = "Paus Uppdatera";
$text['label-refresh_pause']['uk-ua'] = "";

$text['label-refresh_enable']['en-us'] = "Enable Refresh";
$text['label-refresh_enable']['en-gb'] = "Enable Refresh";
$text['label-refresh_enable']['ar-eg'] = "";
$text['label-refresh_enable']['de-at'] = "Seite neu laden aktivieren"; //copied from de-de
$text['label-refresh_enable']['de-ch'] = "Seite neu laden aktivieren"; //copied from de-de
$text['label-refresh_enable']['de-de'] = "Seite neu laden aktivieren";
$text['label-refresh_enable']['es-cl'] = "Activar Actualizar";
$text['label-refresh_enable']['es-mx'] = "Activar Actualizar"; //copied from es-cl
$text['label-refresh_enable']['fr-ca'] = "Activer Actualiser"; //copied from fr-fr
$text['label-refresh_enable']['fr-fr'] = "Activer Actualiser";
$text['label-refresh_enable']['he-il'] = "אפשר רענון";
$text['label-refresh_enable']['it-it'] = "Abilita Aggiornamento";
$text['label-refresh_enable']['nl-nl'] = "Start verversen";
$text['label-refresh_enable']['pl-pl'] = "Włącz odświeżanie";
$text['label-refresh_enable']['pt-br'] = "Habilitar Atualização";
$text['label-refresh_enable']['pt-pt'] = "Habilitar Atualização";
$text['label-refresh_enable']['ro-ro'] = "";
$text['label-refresh_enable']['ru-ru'] = "Включить обновление";
$text['label-refresh_enable']['sv-se'] = "Aktivera Uppdatering";
$text['label-refresh_enable']['uk-ua'] = "Ð’ÐºÐ»ÑŽÑ‡Ð¸Ñ‚Ð¸ Ð¾Ð½Ð¾Ð²Ð»ÐµÐ½Ð½Ñ";

$text['label-recording']['en-us'] = "Recording";
$text['label-recording']['en-gb'] = "Recording";
$text['label-recording']['ar-eg'] = "";
$text['label-recording']['de-at'] = "Aufnahme"; //copied from de-de
$text['label-recording']['de-ch'] = "Aufnahme"; //copied from de-de
$text['label-recording']['de-de'] = "Aufnahme";
$text['label-recording']['es-cl'] = "Grabación de Llamadas";
$text['label-recording']['es-mx'] = "Grabación de Llamadas"; //copied from es-cl
$text['label-recording']['fr-ca'] = "Enregistrement de L'appel"; //copied from fr-fr
$text['label-recording']['fr-fr'] = "Enregistrement de L'appel";
$text['label-recording']['he-il'] = "מקליט";
$text['label-recording']['it-it'] = "Registrazione";
$text['label-recording']['nl-nl'] = "Opnemend";
$text['label-recording']['pl-pl'] = "Nagrywanie";
$text['label-recording']['pt-br'] = "Gravar Chamada";
$text['label-recording']['pt-pt'] = "Gravação de Chamadas";
$text['label-recording']['ro-ro'] = "";
$text['label-recording']['ru-ru'] = "Запись";
$text['label-recording']['sv-se'] = "Inspelning";
$text['label-recording']['uk-ua'] = "Ð—Ð°Ð¿Ð¸Ñ";

$text['label-record']['en-us'] = "Record";
$text['label-record']['en-gb'] = "Record";
$text['label-record']['ar-eg'] = "";
$text['label-record']['de-at'] = "Aufnehmen"; //copied from de-de
$text['label-record']['de-ch'] = "Aufnehmen"; //copied from de-de
$text['label-record']['de-de'] = "Aufnehmen";
$text['label-record']['es-cl'] = "Registro";
$text['label-record']['es-mx'] = "Registro"; //copied from es-cl
$text['label-record']['fr-ca'] = "Enregistrer"; //copied from fr-fr
$text['label-record']['fr-fr'] = "Enregistrer";
$text['label-record']['he-il'] = "הקלטה";
$text['label-record']['it-it'] = "Registrazione";
$text['label-record']['nl-nl'] = "Opnemen";
$text['label-record']['pl-pl'] = "Nagrywanie";
$text['label-record']['pt-br'] = "Gravar"; //copied from pt-pt
$text['label-record']['pt-pt'] = "Gravar";
$text['label-record']['ro-ro'] = "";
$text['label-record']['ru-ru'] = "Воспроизведение";
$text['label-record']['sv-se'] = "Spela In";
$text['label-record']['uk-ua'] = "Ð—Ð°Ð¿Ð¸Ñ";


$text['label-park']['en-us'] = "Park";
$text['label-park']['en-gb'] = "Park";
$text['label-park']['ar-eg'] = "";
$text['label-park']['de-at'] = "Park"; //copied from de-de
$text['label-park']['de-ch'] = "Park"; //copied from de-de
$text['label-park']['de-de'] = "Park";
$text['label-park']['es-cl'] = "Park";
$text['label-park']['es-mx'] = "Park"; //copied from es-cl
$text['label-park']['fr-ca'] = "Park"; //copied from fr-fr
$text['label-park']['fr-fr'] = "Park";
$text['label-park']['he-il'] = "Park";
$text['label-park']['it-it'] = "Park";
$text['label-park']['nl-nl'] = "Park";
$text['label-park']['pl-pl'] = "Park";
$text['label-park']['pt-br'] = "Estacionar"; //copied from pt-pt
$text['label-park']['pt-pt'] = "Estacionar";
$text['label-park']['ro-ro'] = "";
$text['label-park']['ru-ru'] = "Park";
$text['label-park']['sv-se'] = "Park";
$text['label-park']['uk-ua'] = "Park";

$text['label-other_extensions']['en-us'] = "Other Extensions";
$text['label-other_extensions']['en-gb'] = "Other Extensions";
$text['label-other_extensions']['ar-eg'] = "";
$text['label-other_extensions']['de-at'] = "Andere Nebenstellen"; //copied from de-de
$text['label-other_extensions']['de-ch'] = "Andere Nebenstellen"; //copied from de-de
$text['label-other_extensions']['de-de'] = "Andere Nebenstellen";
$text['label-other_extensions']['es-cl'] = "Otras Extensiones";
$text['label-other_extensions']['es-mx'] = "Otras Extensiones"; //copied from es-cl
$text['label-other_extensions']['fr-ca'] = "Autres Extensions"; //copied from fr-fr
$text['label-other_extensions']['fr-fr'] = "Autres Extensions";
$text['label-other_extensions']['he-il'] = "שלוחות אחרות";
$text['label-other_extensions']['it-it'] = "Altri Interni";
$text['label-other_extensions']['nl-nl'] = "Andere toestellen";
$text['label-other_extensions']['pl-pl'] = "Inne numery wewnętrzne";
$text['label-other_extensions']['pt-br'] = "Outros Ramais";
$text['label-other_extensions']['pt-pt'] = "Outros Extensions";
$text['label-other_extensions']['ro-ro'] = "";
$text['label-other_extensions']['ru-ru'] = "Другие внутренние номера";
$text['label-other_extensions']['sv-se'] = "Annan Anknytning";
$text['label-other_extensions']['uk-ua'] = "Ð†Ð½ÑˆÑ– Ñ€Ð¾Ð·ÑˆÐ¸Ñ€ÐµÐ½Ð½Ñ";

$text['label-no_extensions_found']['en-us'] = "No extensions found.";
$text['label-no_extensions_found']['en-gb'] = "No extensions found.";
$text['label-no_extensions_found']['ar-eg'] = "";
$text['label-no_extensions_found']['de-at'] = "Keine Nebenstellen gefunden."; //copied from de-de
$text['label-no_extensions_found']['de-ch'] = "Keine Nebenstellen gefunden."; //copied from de-de
$text['label-no_extensions_found']['de-de'] = "Keine Nebenstellen gefunden.";
$text['label-no_extensions_found']['es-cl'] = "No hay extensiones encontrados.";
$text['label-no_extensions_found']['es-mx'] = "No hay extensiones encontrados."; //copied from es-cl
$text['label-no_extensions_found']['fr-ca'] = "Aucun extensions trouvés."; //copied from fr-fr
$text['label-no_extensions_found']['fr-fr'] = "Aucun extensions trouvés.";
$text['label-no_extensions_found']['he-il'] = "לא נמצאו שלוחות";
$text['label-no_extensions_found']['it-it'] = "Nessun interno trovato.";
$text['label-no_extensions_found']['nl-nl'] = "Geen toestellen gevonden.";
$text['label-no_extensions_found']['pl-pl'] = "Nie znaleziono numerów wewnętrznych";
$text['label-no_extensions_found']['pt-br'] = "Não foi encontrado nenhum ramal.";
$text['label-no_extensions_found']['pt-pt'] = "Sem extensões encontrado.";
$text['label-no_extensions_found']['ro-ro'] = "";
$text['label-no_extensions_found']['ru-ru'] = "Внутренних номеров не найдено.";
$text['label-no_extensions_found']['sv-se'] = "Ingen anknytning funnen.";
$text['label-no_extensions_found']['uk-ua'] = "ÐÐµ Ð·Ð½Ð°Ð¹Ð´ÐµÐ½Ð¾ Ñ€Ð¾Ð·ÑˆÐ¸Ñ€ÐµÐ½ÑŒ";

$text['label-hangup']['en-us'] = "Hangup";
$text['label-hangup']['en-gb'] = "Hangup";
$text['label-hangup']['ar-eg'] = "";
$text['label-hangup']['de-at'] = "Abwürgen"; //copied from de-de
$text['label-hangup']['de-ch'] = "Abwürgen"; //copied from de-de
$text['label-hangup']['de-de'] = "Abwürgen";
$text['label-hangup']['es-cl'] = "Finalizar Llamada";
$text['label-hangup']['es-mx'] = "Finalizar Llamada"; //copied from es-cl
$text['label-hangup']['fr-ca'] = "Tuer Appel"; //copied from fr-fr
$text['label-hangup']['fr-fr'] = "Tuer Appel";
$text['label-hangup']['he-il'] = "הפסק";
$text['label-hangup']['it-it'] = "Abbatti";
$text['label-hangup']['nl-nl'] = "Ophangen";
$text['label-hangup']['pl-pl'] = "Rozłączenie się";
$text['label-hangup']['pt-br'] = "Encerrar Chamada.";
$text['label-hangup']['pt-pt'] = "Chamada Final";
$text['label-hangup']['ro-ro'] = "";
$text['label-hangup']['ru-ru'] = "Убить";
$text['label-hangup']['sv-se'] = "Lägg På";
$text['label-hangup']['uk-ua'] = "вбити";

$text['label-eavesdrop']['en-us'] = "Eavesdrop";
$text['label-eavesdrop']['en-gb'] = "Eavesdrop";
$text['label-eavesdrop']['ar-eg'] = "";
$text['label-eavesdrop']['de-at'] = "Mithören"; //copied from de-de
$text['label-eavesdrop']['de-ch'] = "Mithören"; //copied from de-de
$text['label-eavesdrop']['de-de'] = "Mithören";
$text['label-eavesdrop']['es-cl'] = "Escuchar";
$text['label-eavesdrop']['es-mx'] = "Escuchar"; //copied from es-cl
$text['label-eavesdrop']['fr-ca'] = "Espionner"; //copied from fr-fr
$text['label-eavesdrop']['fr-fr'] = "Espionner";
$text['label-eavesdrop']['he-il'] = "";
$text['label-eavesdrop']['it-it'] = "Ascolta";
$text['label-eavesdrop']['nl-nl'] = "Afluisteren";
$text['label-eavesdrop']['pl-pl'] = "Podsłuchiwanie";
$text['label-eavesdrop']['pt-br'] = "Escutar Chamada";
$text['label-eavesdrop']['pt-pt'] = "Bisbilhotar";
$text['label-eavesdrop']['ro-ro'] = "";
$text['label-eavesdrop']['ru-ru'] = "Подслушивать";
$text['label-eavesdrop']['sv-se'] = "Medlyssning";
$text['label-eavesdrop']['uk-ua'] = "підслуховувати";

$text['label-filter']['en-us'] = "Filter";
$text['label-filter']['en-gb'] = "Filter";
$text['label-filter']['ar-eg'] = "";
$text['label-filter']['de-at'] = "Filter"; //copied from de-de
$text['label-filter']['de-ch'] = "Filter"; //copied from de-de
$text['label-filter']['de-de'] = "Filter";
$text['label-filter']['es-cl'] = "Filtrar";
$text['label-filter']['es-mx'] = "Filtrar"; //copied from es-cl
$text['label-filter']['fr-ca'] = "Filter"; //copied from fr-fr
$text['label-filter']['fr-fr'] = "Filter";
$text['label-filter']['he-il'] = "";
$text['label-filter']['it-it'] = "Filter";
$text['label-filter']['nl-nl'] = "Filter";
$text['label-filter']['pl-pl'] = "Filter";
$text['label-filter']['pt-br'] = "Filtrar";
$text['label-filter']['pt-pt'] = "Filtrar";
$text['label-filter']['ro-ro'] = "";
$text['label-filter']['ru-ru'] = "Подслушивать";
$text['label-filter']['sv-se'] = "Medlyssning";
$text['label-filter']['uk-ua'] = "підслуховувати";


$text['label-call_group']['en-us'] = "Call Group";
$text['label-call_group']['en-gb'] = "Call Group";
$text['label-call_group']['ar-eg'] = "";
$text['label-call_group']['de-at'] = "Rufgruppe"; //copied from de-de
$text['label-call_group']['de-ch'] = "Rufgruppe"; //copied from de-de
$text['label-call_group']['de-de'] = "Rufgruppe";
$text['label-call_group']['es-cl'] = "Llamar a Grupo";
$text['label-call_group']['es-mx'] = "Llamar a Grupo"; //copied from es-cl
$text['label-call_group']['fr-ca'] = "Groupe d'appel"; //copied from fr-fr
$text['label-call_group']['fr-fr'] = "Groupe d'appel";
$text['label-call_group']['he-il'] = "קבוצת חיוג";
$text['label-call_group']['it-it'] = "Gruppo di Chiamata";
$text['label-call_group']['nl-nl'] = "Oproep Groep";
$text['label-call_group']['pl-pl'] = "Grupa odbiorców rozmowy";
$text['label-call_group']['pt-br'] = "Grupo"; //copied from pt-pt
$text['label-call_group']['pt-pt'] = "Grupo";
$text['label-call_group']['ro-ro'] = "";
$text['label-call_group']['ru-ru'] = "Группы вызова";
$text['label-call_group']['sv-se'] = "Ring Grupp";
$text['label-call_group']['uk-ua'] = "груповий виклик";



$text['label-hold']['en-us'] = "Hold";
$text['label-hold']['en-gb'] = "Hold";
$text['label-hold']['ar-eg'] = "";
$text['label-hold']['de-at'] = ""; //copied from de-de
$text['label-hold']['de-ch'] = ""; //copied from de-de
$text['label-hold']['de-de'] = "";
$text['label-hold']['es-cl'] = "";
$text['label-hold']['es-mx'] = ""; //copied from es-cl
$text['label-hold']['fr-ca'] = "Enregistrement de L'appel"; //copied from fr-fr
$text['label-hold']['fr-fr'] = "Enregistrement de L'appel";
$text['label-hold']['he-il'] = "מקליט";
$text['label-hold']['it-it'] = "Registrazione";
$text['label-hold']['nl-nl'] = "Opnemend";
$text['label-hold']['pl-pl'] = "Nagrywanie";
$text['label-hold']['pt-br'] = "Espera";
$text['label-hold']['pt-pt'] = "Espera";
$text['label-hold']['ro-ro'] = "";
$text['label-hold']['ru-ru'] = "";
$text['label-hold']['sv-se'] = "";
$text['label-hold']['uk-ua'] = "";

$text['label-call_group']['en-us'] = "Call Group";
$text['label-call_group']['en-gb'] = "Call Group";
$text['label-call_group']['ar-eg'] = "";
$text['label-call_group']['de-at'] = "Rufgruppe"; //copied from de-de
$text['label-call_group']['de-ch'] = "Rufgruppe"; //copied from de-de
$text['label-call_group']['de-de'] = "Rufgruppe";
$text['label-call_group']['es-cl'] = "Llamar a Grupo";
$text['label-call_group']['es-mx'] = "Llamar a Grupo"; //copied from es-cl
$text['label-call_group']['fr-ca'] = "Groupe d'appel"; //copied from fr-fr
$text['label-call_group']['fr-fr'] = "Groupe d'appel";
$text['label-call_group']['he-il'] = "קבוצת חיוג";
$text['label-call_group']['it-it'] = "Gruppo di Chiamata";
$text['label-call_group']['nl-nl'] = "Oproep Groep";
$text['label-call_group']['pl-pl'] = "Grupa odbiorców rozmowy";
$text['label-call_group']['pt-br'] = "Grupo"; //copied from pt-pt
$text['label-call_group']['pt-pt'] = "Grupo";
$text['label-call_group']['ro-ro'] = "";
$text['label-call_group']['ru-ru'] = "Группы вызова";
$text['label-call_group']['sv-se'] = "Ring Grupp";
$text['label-call_group']['uk-ua'] = "груповий виклик";

$text['label-call_direction']['en-us'] = "Call Direction";
$text['label-call_direction']['en-gb'] = "Call Direction";
$text['label-call_direction']['ar-eg'] = "";
$text['label-call_direction']['de-at'] = "Anruf Richtung"; //copied from de-de
$text['label-call_direction']['de-ch'] = "Anruf Richtung"; //copied from de-de
$text['label-call_direction']['de-de'] = "Anruf Richtung";
$text['label-call_direction']['es-cl'] = "Dirección de la llamada";
$text['label-call_direction']['es-mx'] = "Dirección de la llamada"; //copied from es-cl
$text['label-call_direction']['fr-ca'] = "Sens de l'appel"; //copied from fr-fr
$text['label-call_direction']['fr-fr'] = "Sens de l'appel";
$text['label-call_direction']['he-il'] = "כיוון שיחה";
$text['label-call_direction']['it-it'] = "Direzione Chiamata";
$text['label-call_direction']['nl-nl'] = "Oproep richting";
$text['label-call_direction']['pl-pl'] = "Kierunek rozmowy";
$text['label-call_direction']['pt-br'] = "Direção da Chamada";
$text['label-call_direction']['pt-pt'] = "Direção da chamada";
$text['label-call_direction']['ro-ro'] = "";
$text['label-call_direction']['ru-ru'] = "Направление вызова";
$text['label-call_direction']['sv-se'] = "Samtals Riktning";
$text['label-call_direction']['uk-ua'] = "напрямок виклику";

$text['description-eavesdrop_destination']['en-us'] = "Select the Eavesdrop Destination";
$text['description-eavesdrop_destination']['en-gb'] = "Select the Eavesdrop Destination";
$text['description-eavesdrop_destination']['ar-eg'] = "";
$text['description-eavesdrop_destination']['de-at'] = "Wählen Sie ein Ziel zum Mithören"; //copied from de-de
$text['description-eavesdrop_destination']['de-ch'] = "Wählen Sie ein Ziel zum Mithören"; //copied from de-de
$text['description-eavesdrop_destination']['de-de'] = "Wählen Sie ein Ziel zum Mithören";
$text['description-eavesdrop_destination']['es-cl'] = "Seleccione el Eavesdrop Destino";
$text['description-eavesdrop_destination']['es-mx'] = "Seleccione el Eavesdrop Destino"; //copied from es-cl
$text['description-eavesdrop_destination']['fr-ca'] = "Sélectionnez la destination d'espionnage"; //copied from fr-fr
$text['description-eavesdrop_destination']['fr-fr'] = "Sélectionnez la destination d'espionnage";
$text['description-eavesdrop_destination']['he-il'] = "";
$text['description-eavesdrop_destination']['it-it'] = "Seleziona la Destinazione d'Ascolto";
$text['description-eavesdrop_destination']['nl-nl'] = "Kies afluister bestemming";
$text['description-eavesdrop_destination']['pl-pl'] = "Wybierz destynację podsłuchiwanych rozmów";
$text['description-eavesdrop_destination']['pt-br'] = "Selecione o ramal de destino";
$text['description-eavesdrop_destination']['pt-pt'] = "Selecione o Eavesdrop Destino";
$text['description-eavesdrop_destination']['ro-ro'] = "";
$text['description-eavesdrop_destination']['ru-ru'] = "Выберите подслушивание пункта назначения";
$text['description-eavesdrop_destination']['sv-se'] = "Välj Medlyssning Destination";
$text['description-eavesdrop_destination']['uk-ua'] = "Виберіть пункт призначення підслуховувати";

$text['button-all']['en-us'] = "All";
$text['button-all']['en-gb'] = "All";
$text['button-all']['ar-eg'] = "";
$text['button-all']['de-at'] = "Alle"; //copied from de-de
$text['button-all']['de-ch'] = "Alle"; //copied from de-de
$text['button-all']['de-de'] = "Alle";
$text['button-all']['es-cl'] = "Todos";
$text['button-all']['es-mx'] = "Todos"; //copied from es-cl
$text['button-all']['fr-ca'] = "Tous"; //copied from fr-fr
$text['button-all']['fr-fr'] = "Tous";
$text['button-all']['he-il'] = "הכל";
$text['button-all']['it-it'] = "Tutti";
$text['button-all']['nl-nl'] = "Alle";
$text['button-all']['pl-pl'] = "Wszyscy";
$text['button-all']['pt-br'] = "Todos"; //copied from pt-pt
$text['button-all']['pt-pt'] = "Tudo";
$text['button-all']['ro-ro'] = "";
$text['button-all']['ru-ru'] = "Все";
$text['button-all']['sv-se'] = "Alla";
$text['button-all']['uk-ua'] = "Ð’ÑÑ–";


$text['button-all']['en-us'] = "All";
$text['button-all']['en-gb'] = "All";
$text['button-all']['ar-eg'] = "";
$text['button-all']['de-at'] = "Alle"; //copied from de-de
$text['button-all']['de-ch'] = "Alle"; //copied from de-de
$text['button-all']['de-de'] = "Alle";
$text['button-all']['es-cl'] = "Todos";
$text['button-all']['es-mx'] = "Todos"; //copied from es-cl
$text['button-all']['fr-ca'] = "Tous"; //copied from fr-fr
$text['button-all']['fr-fr'] = "Tous";
$text['button-all']['he-il'] = "הכל";
$text['button-all']['it-it'] = "Tutti";
$text['button-all']['nl-nl'] = "Alle";
$text['button-all']['pl-pl'] = "Wszyscy";
$text['button-all']['pt-br'] = "Todos"; //copied from pt-pt
$text['button-all']['pt-pt'] = "Tudo";
$text['button-all']['ro-ro'] = "";
$text['button-all']['ru-ru'] = "Все";
$text['button-all']['sv-se'] = "Alla";
$text['button-all']['uk-ua'] = "Ð’ÑÑ–";

$text['button-clear']['en-us'] = "Clear";
$text['button-clear']['en-gb'] = "Clear";
$text['button-clear']['ar-eg'] = "";
$text['button-clear']['de-at'] = "Alle"; //copied from de-de
$text['button-clear']['de-ch'] = "Alle"; //copied from de-de
$text['button-clear']['de-de'] = "Alle";
$text['button-clear']['es-cl'] = "Limpar";
$text['button-clear']['es-mx'] = "Limpar"; //copied from es-cl
$text['button-clear']['fr-ca'] = "Tous"; //copied from fr-fr
$text['button-clear']['fr-fr'] = "Tous";
$text['button-clear']['he-il'] = "הכל";
$text['button-clear']['it-it'] = "Tutti";
$text['button-clear']['nl-nl'] = "Alle";
$text['button-clear']['pl-pl'] = "Wszyscy";
$text['button-clear']['pt-br'] = "Limpar"; //copied from pt-pt
$text['button-clear']['pt-pt'] = "Limpar";
$text['button-clear']['ro-ro'] = "";
$text['button-clear']['ru-ru'] = "Все";
$text['button-clear']['sv-se'] = "Alla";
$text['button-clear']['uk-ua'] = "";

$text['button-clear']['en-us'] = "Clear";
$text['button-clear']['en-gb'] = "Clear";
$text['button-clear']['ar-eg'] = "";
$text['button-clear']['de-at'] = "Alle"; //copied from de-de
$text['button-clear']['de-ch'] = "Alle"; //copied from de-de
$text['button-clear']['de-de'] = "Alle";
$text['button-clear']['es-cl'] = "Limpar";
$text['button-clear']['es-mx'] = "Limpar"; //copied from es-cl
$text['button-clear']['fr-ca'] = "Tous"; //copied from fr-fr
$text['button-clear']['fr-fr'] = "Tous";
$text['button-clear']['he-il'] = "הכל";
$text['button-clear']['it-it'] = "Tutti";
$text['button-clear']['nl-nl'] = "Alle";
$text['button-clear']['pl-pl'] = "Wszyscy";
$text['button-clear']['pt-br'] = "Limpar"; //copied from pt-pt
$text['button-clear']['pt-pt'] = "Limpar";
$text['button-clear']['ro-ro'] = "";
$text['button-clear']['ru-ru'] = "Все";
$text['button-clear']['sv-se'] = "Alla";
$text['button-clear']['uk-ua'] = "";

$text['button-reboot']['en-us'] = "Reboot";
$text['button-reboot']['en-gb'] = "Reboot";
$text['button-reboot']['ar-eg'] = "";
$text['button-reboot']['de-at'] = "Neu starten"; //copied from de-de
$text['button-reboot']['de-ch'] = "Neu starten"; //copied from de-de
$text['button-reboot']['de-de'] = "Neu starten";
$text['button-reboot']['es-cl'] = "Reiniciar";
$text['button-reboot']['es-mx'] = "Reiniciar"; //copied from es-cl
$text['button-reboot']['fr-ca'] = "Redémarrer"; //copied from fr-fr
$text['button-reboot']['fr-fr'] = "Redémarrer";
$text['button-reboot']['he-il'] = "";
$text['button-reboot']['it-it'] = "Riavvia";
$text['button-reboot']['nl-nl'] = "Herstart";
$text['button-reboot']['pl-pl'] = "Zrestartuj";
$text['button-reboot']['pt-br'] = "Reiniciando";
$text['button-reboot']['pt-pt'] = "Reinicialização";
$text['button-reboot']['ro-ro'] = "";
$text['button-reboot']['ru-ru'] = "Перезагрузить";
$text['button-reboot']['sv-se'] = "Starta Om";
$text['button-reboot']['uk-ua'] = "Перезавантажити";

$text['button-extension']['en-us'] = "Extension";
$text['button-extension']['en-gb'] = "Extension";
$text['button-extension']['ar-eg'] = "";
$text['button-extension']['de-at'] = "Alle"; //copied from de-de
$text['button-extension']['de-ch'] = "Alle"; //copied from de-de
$text['button-extension']['de-de'] = "Alle";
$text['button-extension']['es-cl'] = "Iniciar Ramal";
$text['button-extension']['es-mx'] = "Iniciar Ramal"; //copied from es-cl
$text['button-extension']['fr-ca'] = "Tous"; //copied from fr-fr
$text['button-extension']['fr-fr'] = "Tous";
$text['button-extension']['he-il'] = "הכל";
$text['button-extension']['it-it'] = "Tutti";
$text['button-extension']['nl-nl'] = "Alle";
$text['button-extension']['pl-pl'] = "Wszyscy";
$text['button-extension']['pt-br'] = "Iniciar Ramal"; //copied from pt-pt
$text['button-extension']['pt-pt'] = "Iniciar Ramal";
$text['button-extension']['ro-ro'] = "";
$text['button-extension']['ru-ru'] = "Все";
$text['button-extension']['sv-se'] = "Alla";
$text['button-extension']['uk-ua'] = "";

$text['label-name_filter']['en-us'] = "Filter Name";
$text['label-name_filter']['en-gb'] = "Filter Name";
$text['label-name_filter']['ar-eg'] = "";
$text['label-name_filter']['de-at'] = "Rufgruppe"; //copied from de-de
$text['label-name_filter']['de-ch'] = "Rufgruppe"; //copied from de-de
$text['label-name_filter']['de-de'] = "Rufgruppe";
$text['label-name_filter']['es-cl'] = "Llamar a Buscar por Nome";
$text['label-name_filter']['es-mx'] = "Llamar a Buscar por Nome"; //copied from es-cl
$text['label-name_filter']['fr-ca'] = "Groupe d'appel"; //copied from fr-fr
$text['label-name_filter']['fr-fr'] = "Groupe d'appel";
$text['label-name_filter']['he-il'] = "קבוצת חיוג";
$text['label-name_filter']['it-it'] = "Gruppo di Chiamata";
$text['label-name_filter']['nl-nl'] = "Oproep Groep";
$text['label-name_filter']['pl-pl'] = "Grupa odbiorców rozmowy";
$text['label-name_filter']['pt-br'] = "Buscar por Nome"; //copied from pt-pt
$text['label-name_filter']['pt-pt'] = "Buscar por Nome";
$text['label-name_filter']['ro-ro'] = "";
$text['label-name_filter']['ru-ru'] = "Группы вызова";
$text['label-name_filter']['sv-se'] = "Ring Grupp";
$text['label-name_filter']['uk-ua'] = "груповий виклик";



$text['label-extension_filter']['en-us'] = "Filter Extension";
$text['label-extension_filter']['en-gb'] = "Filter Extension";
$text['label-extension_filter']['ar-eg'] = "";
$text['label-extension_filter']['de-at'] = "Rufgruppe"; //copied from de-de
$text['label-extension_filter']['de-ch'] = "Rufgruppe"; //copied from de-de
$text['label-extension_filter']['de-de'] = "Rufgruppe";
$text['label-extension_filter']['es-cl'] = "Llamar a Grupo";
$text['label-extension_filter']['es-mx'] = "Llamar a Grupo"; //copied from es-cl
$text['label-extension_filter']['fr-ca'] = "Groupe d'appel"; //copied from fr-fr
$text['label-extension_filter']['fr-fr'] = "Groupe d'appel";
$text['label-extension_filter']['he-il'] = "קבוצת חיוג";
$text['label-extension_filter']['it-it'] = "Gruppo di Chiamata";
$text['label-extension_filter']['nl-nl'] = "Oproep Groep";
$text['label-extension_filter']['pl-pl'] = "Grupa odbiorców rozmowy";
$text['label-extension_filter']['pt-br'] = "Buscar por Ramal"; //copied from pt-pt
$text['label-extension_filter']['pt-pt'] = "Buscar por Ramal";
$text['label-extension_filter']['ro-ro'] = "";
$text['label-extension_filter']['ru-ru'] = "Группы вызова";
$text['label-extension_filter']['sv-se'] = "Ring Grupp";
$text['label-extension_filter']['uk-ua'] = "груповий виклик";


?>
