<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-flux_texts']['en-us'] = "Flux Text To Speech";
$text['title-flux_texts']['en-gb'] = "Flux Text To Speech";
$text['title-flux_texts']['ar-eg'] = "";
$text['title-flux_texts']['de-at'] = "Rundrufe"; //copied from de-de
$text['title-flux_texts']['de-ch'] = "Rundrufe"; //copied from de-de
$text['title-flux_texts']['de-de'] = "Rundrufe";
$text['title-flux_texts']['es-cl'] = "Llamada Masiva (Text To Speech)";
$text['title-flux_texts']['es-mx'] = "Llamada Masiva (Text To Speech)"; //copied from es-cl
$text['title-flux_texts']['fr-ca'] = "Campagne d'appels"; //copied from fr-fr
$text['title-flux_texts']['fr-fr'] = "Campagne d'appels";
$text['title-flux_texts']['he-il'] = "הגדרת חשבון";
$text['title-flux_texts']['it-it'] = "Chiamate Multiple";
$text['title-flux_texts']['nl-nl'] = "Omroep";
$text['title-flux_texts']['pl-pl'] = "Rozsyłanie rozmów";
$text['title-flux_texts']['pt-br'] = "Configurações da Conta";
$text['title-flux_texts']['pt-pt'] = "Chamadas de Text To Speech";
$text['title-flux_texts']['ro-ro'] = "";
$text['title-flux_texts']['ru-ru'] = "Массовые вызовы";
$text['title-flux_texts']['sv-se'] = "Samtalsdistributioner";
$text['title-flux_texts']['uk-ua'] = "Трансляція дзвінків";

$text['title-flux_text']['en-us'] = "Flux Text To Speech";
$text['title-flux_text']['en-gb'] = "Flux Text To Speech";
$text['title-flux_text']['ar-eg'] = "";
$text['title-flux_text']['de-at'] = "Rundrufe"; //copied from de-de
$text['title-flux_text']['de-ch'] = "Rundrufe"; //copied from de-de
$text['title-flux_text']['de-de'] = "Rundrufe";
$text['title-flux_text']['es-cl'] = "Llamada Masiva (Text To Speech)";
$text['title-flux_text']['es-mx'] = "Llamada Masiva (Text To Speech)"; //copied from es-cl
$text['title-flux_text']['fr-ca'] = "Campagne d'appels"; //copied from fr-fr
$text['title-flux_text']['fr-fr'] = "Campagne d'appels";
$text['title-flux_text']['he-il'] = "הגדרת חשבון";
$text['title-flux_text']['it-it'] = "Chiamate Multiple";
$text['title-flux_text']['nl-nl'] = "Omroep";
$text['title-flux_text']['pl-pl'] = "Rozsyłanie rozmów";
$text['title-flux_text']['pt-br'] = "Configurações da Conta";
$text['title-flux_text']['pt-pt'] = "Chamadas de Text To Speech";
$text['title-flux_text']['ro-ro'] = "";
$text['title-flux_text']['ru-ru'] = "Массовые вызовы";
$text['title-flux_text']['sv-se'] = "Samtalsdistributioner";
$text['title-flux_text']['uk-ua'] = "Трансляція дзвінків";

$text['title_description-flux_text']['en-us'] = "Application to create interactive sounds from texts.";
$text['title_description-flux_text']['en-gb'] = "Application to create interactive sounds from texts.";
$text['title_description-flux_text']['ar-eg'] = "";
$text['title_description-flux_text']['de-at'] = "";
$text['title_description-flux_text']['de-ch'] = "";
$text['title_description-flux_text']['de-de'] = "";
$text['title_description-flux_text']['es-cl'] = "";
$text['title_description-flux_text']['es-mx'] = "";
$text['title_description-flux_text']['fr-ca'] = "";
$text['title_description-flux_text']['fr-fr'] = "";
$text['title_description-flux_text']['he-il'] = "";
$text['title_description-flux_text']['it-it'] = "";
$text['title_description-flux_text']['nl-nl'] = "Beheer de aflevering van voor-opgenomen boodschappen naar meerdere ontvangers.";
$text['title_description-flux_text']['pl-pl'] = "";
$text['title_description-flux_text']['pt-br'] = "Aplicação para criar áudios interativos a partir de textos.";
$text['title_description-flux_text']['pt-pt'] = "";
$text['title_description-flux_text']['ro-ro'] = "";
$text['title_description-flux_text']['ru-ru'] = "";
$text['title_description-flux_text']['sv-se'] = "";
$text['title_description-flux_text']['uk-ua'] = "";


$text['option-true']['en-us'] = "True";
$text['option-true']['en-gb'] = "True";
$text['option-true']['ar-eg'] = "";
$text['option-true']['de-at'] = "Ein"; //copied from de-de
$text['option-true']['de-ch'] = "Ein"; //copied from de-de
$text['option-true']['de-de'] = "Ein";
$text['option-true']['es-cl'] = "Verdadero";
$text['option-true']['es-mx'] = "Verdadero"; //copied from es-cl
$text['option-true']['fr-ca'] = "Oui"; //copied from fr-fr
$text['option-true']['fr-fr'] = "Oui";
$text['option-true']['he-il'] = "חוקי";
$text['option-true']['it-it'] = "";
$text['option-true']['nl-nl'] = "Aan";
$text['option-true']['pl-pl'] = "Tak";
$text['option-true']['pt-br'] = "Sim"; //copied from pt-pt
$text['option-true']['pt-pt'] = "Sim";
$text['option-true']['ro-ro'] = "";
$text['option-true']['ru-ru'] = "Да";
$text['option-true']['sv-se'] = "Sann";
$text['option-true']['uk-ua'] = "Так";

$text['option-false']['en-us'] = "False";
$text['option-false']['en-gb'] = "False";
$text['option-false']['ar-eg'] = "";
$text['option-false']['de-at'] = "Aus"; //copied from de-de
$text['option-false']['de-ch'] = "Aus"; //copied from de-de
$text['option-false']['de-de'] = "Aus";
$text['option-false']['es-cl'] = "Falso";
$text['option-false']['es-mx'] = "Falso"; //copied from es-cl
$text['option-false']['fr-ca'] = "Non"; //copied from fr-fr
$text['option-false']['fr-fr'] = "Non";
$text['option-false']['he-il'] = "לא חוקי";
$text['option-false']['it-it'] = "";
$text['option-false']['nl-nl'] = "Uit";
$text['option-false']['pl-pl'] = "Nie";
$text['option-false']['pt-br'] = "Não"; //copied from pt-pt
$text['option-false']['pt-pt'] = "Não";
$text['option-false']['ro-ro'] = "";
$text['option-false']['ru-ru'] = "Нет";
$text['option-false']['sv-se'] = "Falsk";
$text['option-false']['uk-ua'] = "Ні";

$text['label-accountcode']['en-us'] = "Accountcode";
$text['label-accountcode']['en-gb'] = "Accountcode";
$text['label-accountcode']['ar-eg'] = "";
$text['label-accountcode']['de-at'] = "Kontoschlüssel"; //copied from de-de
$text['label-accountcode']['de-ch'] = "Kontoschlüssel"; //copied from de-de
$text['label-accountcode']['de-de'] = "Kontoschlüssel";
$text['label-accountcode']['es-cl'] = "Código de cuenta";
$text['label-accountcode']['es-mx'] = "Código de cuenta"; //copied from es-cl
$text['label-accountcode']['fr-ca'] = "Code de compte"; //copied from fr-fr
$text['label-accountcode']['fr-fr'] = "Code de compte";
$text['label-accountcode']['he-il'] = "קוד חשבון";
$text['label-accountcode']['it-it'] = "";
$text['label-accountcode']['nl-nl'] = "Account code";
$text['label-accountcode']['pl-pl'] = "Numer konta billingowego";
$text['label-accountcode']['pt-br'] = "Código da conta";
$text['label-accountcode']['pt-pt'] = "Accountcode";
$text['label-accountcode']['ro-ro'] = "";
$text['label-accountcode']['ru-ru'] = "Код Авторизации";
$text['label-accountcode']['sv-se'] = "Accountcode";
$text['label-accountcode']['uk-ua'] = "Код облікового запису";


$text['label-text']['en-us'] = "Text to create file";
$text['label-text']['en-gb'] = "Text to create file";
$text['label-text']['ar-eg'] = "Text to create file";
$text['label-text']['de-at'] = "Text to create file";
$text['label-text']['de-ch'] = "Text to create file";
$text['label-text']['de-de'] = "Text to create file";
$text['label-text']['es-cl'] = "Text to create file";
$text['label-text']['es-mx'] = "Text to create file";
$text['label-text']['fr-ca'] = "Text to create file";
$text['label-text']['fr-fr'] = "Text to create file";
$text['label-text']['he-il'] = "Text to create file";
$text['label-text']['it-it'] = "Text to create file";
$text['label-text']['nl-nl'] = "";
$text['label-text']['pl-pl'] = "Text to create file";
$text['label-text']['pt-br'] = "Texto para criar arquivo";
$text['label-text']['pt-pt'] = "Text to create file";
$text['label-text']['ro-ro'] = "Text to create file";
$text['label-text']['ru-ru'] = "Text to create file";
$text['label-text']['sv-se'] = "Text to create file";
$text['label-text']['uk-ua'] = "Text to create file";


$text['description-accountcode']['en-us'] = "Account code used for identify Text to Speech.";
$text['description-accountcode']['en-gb'] = "";
$text['description-accountcode']['ar-eg'] = "";
$text['description-accountcode']['de-at'] = ""; //copied from de-de
$text['description-accountcode']['de-ch'] = ""; //copied from de-de
$text['description-accountcode']['de-de'] = "";
$text['description-accountcode']['es-cl'] = "";
$text['description-accountcode']['es-mx'] = "";
$text['description-accountcode']['fr-ca'] = "";
$text['description-accountcode']['fr-fr'] = "";
$text['description-accountcode']['he-il'] = "";
$text['description-accountcode']['it-it'] = "";
$text['description-accountcode']['nl-nl'] = "";
$text['description-accountcode']['pl-pl'] = "";
$text['description-accountcode']['pt-br'] = ""; //copied from pt-pt
$text['description-accountcode']['pt-pt'] = "";
$text['description-accountcode']['ro-ro'] = "";
$text['description-accountcode']['ru-ru'] = "";
$text['description-accountcode']['sv-se'] = "";
$text['description-accountcode']['uk-ua'] = "";


$text['description-name']['en-us'] = "Enter the name here.";
$text['description-name']['en-gb'] = "Enter the name here.";
$text['description-name']['ar-eg'] = "";
$text['description-name']['de-at'] = "Geben Sie den Namen an."; //copied from de-de
$text['description-name']['de-ch'] = "Geben Sie den Namen an."; //copied from de-de
$text['description-name']['de-de'] = "Geben Sie den Namen an.";
$text['description-name']['es-cl'] = "Ingrese el nombre aquí.";
$text['description-name']['es-mx'] = "Ingrese el nombre aquí."; //copied from es-cl
$text['description-name']['fr-ca'] = "Insérer le Nom."; //copied from fr-fr
$text['description-name']['fr-fr'] = "Insérer le Nom.";
$text['description-name']['he-il'] = "הכנס את השם";
$text['description-name']['it-it'] = "Inserire il nome qui.";
$text['description-name']['nl-nl'] = "Voer de naam hier in.";
$text['description-name']['pl-pl'] = "Wprowadź nazwę";
$text['description-name']['pt-br'] = "Insira o nome do broadcast.";
$text['description-name']['pt-pt'] = "Introduza o nome aqui.";
$text['description-name']['ro-ro'] = "";
$text['description-name']['ru-ru'] = "Введите имя";
$text['description-name']['sv-se'] = "Skriv in namnet här.";
$text['description-name']['uk-ua'] = "Введіть назву";

$text['description-info']['en-us'] = "Enter the description here.";
$text['description-info']['en-gb'] = "Enter the description here.";
$text['description-info']['ar-eg'] = "";
$text['description-info']['de-at'] = "Geben Sie eine Beschreibung an."; //copied from de-de
$text['description-info']['de-ch'] = "Geben Sie eine Beschreibung an."; //copied from de-de
$text['description-info']['de-de'] = "Geben Sie eine Beschreibung an.";
$text['description-info']['es-cl'] = "Ingrese descripción aquí.";
$text['description-info']['es-mx'] = "Ingrese descripción aquí."; //copied from es-cl
$text['description-info']['fr-ca'] = "Entrez la description ici";
$text['description-info']['fr-fr'] = "Entrez la description ici";
$text['description-info']['he-il'] = "הכנס תאור";
$text['description-info']['it-it'] = "Inserire la descrizione qui.";
$text['description-info']['nl-nl'] = "Voer de omschrijving hier in.";
$text['description-info']['pl-pl'] = "Wprowadź opis";
$text['description-info']['pt-br'] = "Inisra uma descrição";
$text['description-info']['pt-pt'] = "Insira a descrição aqui.";
$text['description-info']['ro-ro'] = "";
$text['description-info']['ru-ru'] = "Введите описание";
$text['description-info']['sv-se'] = "Ange beskrivning här.";
$text['description-info']['uk-ua'] = "Введіть опис";

$text['label-text-field']['en-us'] = "Text to create audio.";
$text['label-text-field']['en-gb'] = "Text to create audio.";
$text['label-text-field']['ar-eg'] = "";
$text['label-text-field']['de-at'] = "Geben Sie eine Beschreibung an."; //copied from de-de
$text['label-text-field']['de-ch'] = "Geben Sie eine Beschreibung an."; //copied from de-de
$text['label-text-field']['de-de'] = "Geben Sie eine Beschreibung an.";
$text['label-text-field']['es-cl'] = "Ingrese descripción aquí.";
$text['label-text-field']['es-mx'] = "Ingrese descripción aquí."; //copied from es-cl
$text['label-text-field']['fr-ca'] = "Entrez la description ici";
$text['label-text-field']['fr-fr'] = "Entrez la description ici";
$text['label-text-field']['he-il'] = "הכנס תאור";
$text['label-text-field']['it-it'] = "Inserire la descrizione qui.";
$text['label-text-field']['nl-nl'] = "Voer de omschrijving hier in.";
$text['label-text-field']['pl-pl'] = "Wprowadź opis";
$text['label-text-field']['pt-br'] = "Texto para criar arquivo de audio.";
$text['label-text-field']['pt-pt'] = "Texto para criar arquivo de audio.";
$text['label-text-field']['ro-ro'] = "";
$text['label-text-field']['ru-ru'] = "Введите описание";
$text['label-text-field']['sv-se'] = "Ange beskrivning här.";
$text['label-text-field']['uk-ua'] = "Введіть опис";

$text['description-destination']['en-us'] = "Send the call to the extension an IVR Menu, Conference Room, or any other number.";
$text['description-destination']['en-gb'] = "Send the call to the extension an IVR Menu, Conference Room, or any other number.";
$text['description-destination']['ar-eg'] = "";
$text['description-destination']['de-at'] = "Der Anruf wird an eine Nebenstelle, eine Automatische Vermittlung, ein Konferenzraum oder jede andere Nummer weitergeleitet."; //copied from de-de
$text['description-destination']['de-ch'] = "Der Anruf wird an eine Nebenstelle, eine Automatische Vermittlung, ein Konferenzraum oder jede andere Nummer weitergeleitet."; //copied from de-de
$text['description-destination']['de-de'] = "Der Anruf wird an eine Nebenstelle, eine Automatische Vermittlung, ein Konferenzraum oder jede andere Nummer weitergeleitet.";
$text['description-destination']['es-cl'] = "Enviar la llamada a extension a IVR, conferencias o cualquier otro número.";
$text['description-destination']['es-mx'] = "Enviar la llamada a extension a IVR, conferencias o cualquier otro número."; //copied from es-cl
$text['description-destination']['fr-ca'] = "Emettre l'appel vers un SVI, salle de conférence, ou tout autre numéro."; //copied from fr-fr
$text['description-destination']['fr-fr'] = "Emettre l'appel vers un SVI, salle de conférence, ou tout autre numéro.";
$text['description-destination']['he-il'] = "";
$text['description-destination']['it-it'] = "Connetti la chiamata con un interno, un IVR, un'audioconferenza, o qualsiasi altro servizio.";
$text['description-destination']['nl-nl'] = "Send de oproep naar een toestel, IVR Menu, conferentie of een willekeurig ander nummer.";
$text['description-destination']['pl-pl'] = "Wybierz numer docelowy.";
$text['description-destination']['pt-br'] = "Enviar a chamada para a extensão de um menu de IVR, Sala de Conferência ou qualquer outro número. ";
$text['description-destination']['pt-pt'] = "Enviar a chamada para a extensão de um menu de IVR, Sala de Conferência ou qualquer outro número.";
$text['description-destination']['ro-ro'] = "";
$text['description-destination']['ru-ru'] = "Отправить вызов на внутренний номер, IVR, конференцию или любой другой номер.";
$text['description-destination']['sv-se'] = "Skicka samtalet till en anknytning, IVR Meny, Konferens Rum eller något annat nummer.";
$text['description-destination']['uk-ua'] = "Відправити дзвінок на розширення, меню IVR, конференцію, або будь-який інший номер.";

$text['confirm-update']['en-us'] = "Update Complete";
$text['confirm-update']['en-gb'] = "Update Complete";
$text['confirm-update']['ar-eg'] = "";
$text['confirm-update']['de-at'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['confirm-update']['de-ch'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['confirm-update']['de-de'] = "Aktualisierung durchgeführt";
$text['confirm-update']['es-cl'] = "Actualización Completa";
$text['confirm-update']['es-mx'] = "Actualización Completa"; //copied from es-cl
$text['confirm-update']['fr-ca'] = "Mise à jour terminée"; //copied from fr-fr
$text['confirm-update']['fr-fr'] = "Mise à jour terminée";
$text['confirm-update']['he-il'] = "עידכון הושלם";
$text['confirm-update']['it-it'] = "Aggiornamento Completato.";
$text['confirm-update']['nl-nl'] = "Bijwerken gereed";
$text['confirm-update']['pl-pl'] = "Aktualizacja zakonczona";
$text['confirm-update']['pt-br'] = "Atualização Efetuada";
$text['confirm-update']['pt-pt'] = "Actualização Efectuada";
$text['confirm-update']['ro-ro'] = "";
$text['confirm-update']['ru-ru'] = "Обновление завершено";
$text['confirm-update']['sv-se'] = "Uppdatering Klar";
$text['confirm-update']['uk-ua'] = "Оновлення завершено";

$text['confirm-name']['en-us'] = "Please provide: Name";
$text['confirm-name']['en-gb'] = "Please provide: Name";
$text['confirm-name']['ar-eg'] = "";
$text['confirm-name']['de-at'] = "Bitte geben Sie den Namen an"; //copied from de-de
$text['confirm-name']['de-ch'] = "Bitte geben Sie den Namen an"; //copied from de-de
$text['confirm-name']['de-de'] = "Bitte geben Sie den Namen an";
$text['confirm-name']['es-cl'] = "Por favor agregue: Nombre";
$text['confirm-name']['es-mx'] = "Por favor agregue: Nombre"; //copied from es-cl
$text['confirm-name']['fr-ca'] = "Merci d'indiquer: Nom"; //copied from fr-fr
$text['confirm-name']['fr-fr'] = "Merci d'indiquer: Nom";
$text['confirm-name']['he-il'] = "";
$text['confirm-name']['it-it'] = "Prego fornire: Nome";
$text['confirm-name']['nl-nl'] = "Geef aub: Naam";
$text['confirm-name']['pl-pl'] = "Wprowadź: Nazwę";
$text['confirm-name']['pt-br'] = "Por favor insira: Nome";
$text['confirm-name']['pt-pt'] = "Por favor indique: Nome";
$text['confirm-name']['ro-ro'] = "";
$text['confirm-name']['ru-ru'] = "Пожалуйста, укажите: Имя";
$text['confirm-name']['sv-se'] = "Ange: Namn";
$text['confirm-name']['uk-ua'] = "Введіть назву";

$text['confirm-delete-info']['en-us'] = "Do you really want to delete this?";
$text['confirm-delete-info']['en-gb'] = "Do you really want to delete this?";
$text['confirm-delete-info']['ar-eg'] = "";
$text['confirm-delete-info']['de-at'] = "Wollen Sie das wirklich löschen?"; //copied from de-de
$text['confirm-delete-info']['de-ch'] = "Wollen Sie das wirklich löschen?"; //copied from de-de
$text['confirm-delete-info']['de-de'] = "Wollen Sie das wirklich löschen?";
$text['confirm-delete-info']['es-cl'] = "¿Desea realmente eliminar esto?";
$text['confirm-delete-info']['es-mx'] = "¿Desea realmente eliminar esto?"; //copied from es-cl
$text['confirm-delete-info']['fr-ca'] = "Voulez-vous vraiment supprimer cela?"; //copied from fr-fr
$text['confirm-delete-info']['fr-fr'] = "Voulez-vous vraiment supprimer cela?";
$text['confirm-delete-info']['he-il'] = "";
$text['confirm-delete-info']['it-it'] = "Vuoi veramente cancellarlo?";
$text['confirm-delete-info']['nl-nl'] = "Wilt u dit echt verwijderen?";
$text['confirm-delete-info']['pl-pl'] = "Czy na pewno chcesz to usunąć?";
$text['confirm-delete-info']['pt-br'] = "Deseja realmente remover isto?"; //copied from pt-pt
$text['confirm-delete-info']['pt-pt'] = "Deseja realmente remover isto?";
$text['confirm-delete-info']['ro-ro'] = "";
$text['confirm-delete-info']['ru-ru'] = "Вы действительно хотите это удалить?";
$text['confirm-delete-info']['sv-se'] = "Vill du verkligen ta bort detta?";
$text['confirm-delete-info']['uk-ua'] = "Ви дійсно бажаєте це видалити?";

$text['confirm-add']['en-us'] = "Add Complete";
$text['confirm-add']['en-gb'] = "Add Complete";
$text['confirm-add']['ar-eg'] = "";
$text['confirm-add']['de-at'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['confirm-add']['de-ch'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['confirm-add']['de-de'] = "Erfolgreich hinzugefügt";
$text['confirm-add']['es-cl'] = "Ingreso Completo";
$text['confirm-add']['es-mx'] = "Ingreso Completo"; //copied from es-cl
$text['confirm-add']['fr-ca'] = "Ajouté"; //copied from fr-fr
$text['confirm-add']['fr-fr'] = "Ajouté";
$text['confirm-add']['he-il'] = "הוספה הושלמה";
$text['confirm-add']['it-it'] = "Inserimento Completato";
$text['confirm-add']['nl-nl'] = "Toevoegen gereed";
$text['confirm-add']['pl-pl'] = "Dodano poprawnie";
$text['confirm-add']['pt-br'] = "Criação efetuada";
$text['confirm-add']['pt-pt'] = "Adição Efectuada";
$text['confirm-add']['ro-ro'] = "";
$text['confirm-add']['ru-ru'] = "Добавление завершено";
$text['confirm-add']['sv-se'] = "Tillagd";
$text['confirm-add']['uk-ua'] = "Додано";

$text['file-error']['en-us'] = "Sorry, File type not allowed";
$text['file-error']['en-gb'] = "Sorry, File type not allowed";
$text['file-error']['ar-eg'] = "";
$text['file-error']['de-at'] = "Entschuldigung, Dateityp nicht erlaubt"; //copied from de-de
$text['file-error']['de-ch'] = "Entschuldigung, Dateityp nicht erlaubt"; //copied from de-de
$text['file-error']['de-de'] = "Entschuldigung, Dateityp nicht erlaubt";
$text['file-error']['es-cl'] = "Lo sentimos, no se permite el tipo de archivo";
$text['file-error']['es-mx'] = "Lo sentimos, no se permite el tipo de archivo"; //copied from es-cl
$text['file-error']['fr-ca'] = "Désolé, le type de fichier n'est pas autorisé"; //copied from fr-fr
$text['file-error']['fr-fr'] = "Désolé, le type de fichier n'est pas autorisé";
$text['file-error']['he-il'] = "מצטערים, סוג הקובץ אינו מותר";
$text['file-error']['it-it'] = "";
$text['file-error']['nl-nl'] = "Sorry, File type niet toegestaan";
$text['file-error']['pl-pl'] = "Niestety, Typ pliku jest niedozwolony";
$text['file-error']['pt-br'] = "Desculpe, tipo de arquivo não permitido";
$text['file-error']['pt-pt'] = "Desculpe, tipo de arquivo não permitido";
$text['file-error']['ro-ro'] = "";
$text['file-error']['ru-ru'] = "Обновление завершено";
$text['file-error']['sv-se'] = "Uppdatering Klar";
$text['file-error']['uk-ua'] = "Оновлення завершено";

?>
