<?php

//Rest API
$text['title-restapis']['en-us'] = 'FluxPBX Rest APIs';
$text['title-restapis']['ar-eg'] = 'FluxPBX Rest APIs';
$text['title-restapis']['de-at'] = 'FluxPBX Rest APIs';
$text['title-restapis']['de-ch'] = 'FluxPBX Rest APIs';
$text['title-restapis']['de-de'] = 'FluxPBX Rest APIs';
$text['title-restapis']['es-cl'] = 'FluxPBX Rest APIs';
$text['title-restapis']['es-mx'] = 'FluxPBX Rest APIs';
$text['title-restapis']['fr-ca'] = 'FluxPBX Rest APIs';
$text['title-restapis']['fr-fr'] = 'FluxPBX Rest APIs';
$text['title-restapis']['he-il'] = 'FluxPBX Rest APIs';
$text['title-restapis']['it-it'] = 'FluxPBX Rest APIs';
$text['title-restapis']['nl-nl'] = 'FluxPBX Rest APIs';
$text['title-restapis']['pl-pl'] = 'FluxPBX Rest APIs';
$text['title-restapis']['pt-br'] = 'FluxPBX Rest APIs';
$text['title-restapis']['pt-pt'] = 'FluxPBX Rest APIs';
$text['title-restapis']['ro-ro'] = 'FluxPBX Rest APIs';
$text['title-restapis']['ru-ru'] = 'FluxPBX Rest APIs';
$text['title-restapis']['sv-se'] = 'FluxPBX Rest APIs';
$text['title-restapis']['uk-ua'] = 'FluxPBX Rest APIs';


$text['title-restapis_endpoints']['en-us'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['ar-eg'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['de-at'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['de-ch'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['de-de'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['es-cl'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['es-mx'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['fr-ca'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['fr-fr'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['he-il'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['it-it'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['nl-nl'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['pl-pl'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['pt-br'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['pt-pt'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['ro-ro'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['ru-ru'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['sv-se'] = 'FluxPBX Rest Endpoints';
$text['title-restapis_endpoints']['uk-ua'] = 'FluxPBX Rest Endpoints';



$text['title-restapis_endpoint']['en-us'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['ar-eg'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['de-at'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['de-ch'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['de-de'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['es-cl'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['es-mx'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['fr-ca'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['fr-fr'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['he-il'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['it-it'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['nl-nl'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['pl-pl'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['pt-br'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['pt-pt'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['ro-ro'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['ru-ru'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['sv-se'] = 'FluxPBX Rest Endpoint';
$text['title-restapis_endpoint']['uk-ua'] = 'FluxPBX Rest Endpoint';

$text['title-restapi']['en-us'] = 'FluxPBX Rest APIs';
$text['title-restapi']['ar-eg'] = 'FluxPBX Rest APIs';
$text['title-restapi']['de-at'] = 'FluxPBX Rest APIs';
$text['title-restapi']['de-ch'] = 'FluxPBX Rest APIs';
$text['title-restapi']['de-de'] = 'FluxPBX Rest APIs';
$text['title-restapi']['es-cl'] = 'FluxPBX Rest APIs';
$text['title-restapi']['es-mx'] = 'FluxPBX Rest APIs';
$text['title-restapi']['fr-ca'] = 'FluxPBX Rest APIs';
$text['title-restapi']['fr-fr'] = 'FluxPBX Rest APIs';
$text['title-restapi']['he-il'] = 'FluxPBX Rest APIs';
$text['title-restapi']['it-it'] = 'FluxPBX Rest APIs';
$text['title-restapi']['nl-nl'] = 'FluxPBX Rest APIs';
$text['title-restapi']['pl-pl'] = 'FluxPBX Rest APIs';
$text['title-restapi']['pt-br'] = 'FluxPBX Rest APIs';
$text['title-restapi']['pt-pt'] = 'FluxPBX Rest APIs';
$text['title-restapi']['ro-ro'] = 'FluxPBX Rest APIs';
$text['title-restapi']['ru-ru'] = 'FluxPBX Rest APIs';
$text['title-restapi']['sv-se'] = 'FluxPBX Rest APIs';
$text['title-restapi']['uk-ua'] = 'FluxPBX Rest APIs';


$text['title_description-restapi']['en-us'] = 'Add Rest API URIs to the available API list.';
$text['title_description-restapi']['ar-eg'] = '';
$text['title_description-restapi']['de-at'] = '';
$text['title_description-restapi']['de-ch'] = '';
$text['title_description-restapi']['de-de'] = '';
$text['title_description-restapi']['es-cl'] = '';
$text['title_description-restapi']['es-mx'] = '';
$text['title_description-restapi']['fr-ca'] = '';
$text['title_description-restapi']['fr-fr'] = '';
$text['title_description-restapi']['he-il'] = '';
$text['title_description-restapi']['it-it'] = '';
$text['title_description-restapi']['nl-nl'] = '';
$text['title_description-restapi']['pl-pl'] = '';
$text['title_description-restapi']['pt-br'] = 'Adicionar URIs de Chamada API Rest à lista de APIs disponíveis.';
$text['title_description-restapi']['pt-pt'] = '';
$text['title_description-restapi']['ro-ro'] = '';
$text['title_description-restapi']['ru-ru'] = '';
$text['title_description-restapi']['sv-se'] = '';
$text['title_description-restapi']['uk-ua'] = '';


$text['title_description-restapi_endpoints']['en-us'] = 'Add Rest Endpoints API URIs to the available API list.';
$text['title_description-restapi_endpoints']['ar-eg'] = '';
$text['title_description-restapi_endpoints']['de-at'] = '';
$text['title_description-restapi_endpoints']['de-ch'] = '';
$text['title_description-restapi_endpoints']['de-de'] = '';
$text['title_description-restapi_endpoints']['es-cl'] = '';
$text['title_description-restapi_endpoints']['es-mx'] = '';
$text['title_description-restapi_endpoints']['fr-ca'] = '';
$text['title_description-restapi_endpoints']['fr-fr'] = '';
$text['title_description-restapi_endpoints']['he-il'] = '';
$text['title_description-restapi_endpoints']['it-it'] = '';
$text['title_description-restapi_endpoints']['nl-nl'] = '';
$text['title_description-restapi_endpoints']['pl-pl'] = '';
$text['title_description-restapi_endpoints']['pt-br'] = 'Adicionar Endpoints de Chamada API Rest à lista de APIs disponíveis.';
$text['title_description-restapi_endpoints']['pt-pt'] = '';
$text['title_description-restapi_endpoints']['ro-ro'] = '';
$text['title_description-restapi_endpoints']['ru-ru'] = '';
$text['title_description-restapi_endpoints']['sv-se'] = '';
$text['title_description-restapi_endpoints']['uk-ua'] = '';

$text['label-restapi_name']['en-us'] = 'Name';
$text['label-restapi_name']['ar-eg'] = '';
$text['label-restapi_name']['de-at'] = '';
$text['label-restapi_name']['de-ch'] = '';
$text['label-restapi_name']['de-de'] = '';
$text['label-restapi_name']['es-cl'] = '';
$text['label-restapi_name']['es-mx'] = '';
$text['label-restapi_name']['fr-ca'] = 'Nom';
$text['label-restapi_name']['fr-fr'] = 'Nom';
$text['label-restapi_name']['he-il'] = '';
$text['label-restapi_name']['it-it'] = '';
$text['label-restapi_name']['nl-nl'] = 'Naam';
$text['label-restapi_name']['pl-pl'] = '';
$text['label-restapi_name']['pt-br'] = 'Nome';
$text['label-restapi_name']['pt-pt'] = '';
$text['label-restapi_name']['ro-ro'] = '';
$text['label-restapi_name']['ru-ru'] = '';
$text['label-restapi_name']['sv-se'] = '';
$text['label-restapi_name']['uk-ua'] = '';


$text['label-restapi_authentication']['en-us'] = 'API Authentication';
$text['label-restapi_authentication']['ar-eg'] = '';
$text['label-restapi_authentication']['de-at'] = '';
$text['label-restapi_authentication']['de-ch'] = '';
$text['label-restapi_authentication']['de-de'] = '';
$text['label-restapi_authentication']['es-cl'] = '';
$text['label-restapi_authentication']['es-mx'] = '';
$text['label-restapi_authentication']['fr-ca'] = 'Nom';
$text['label-restapi_authentication']['fr-fr'] = 'Nom';
$text['label-restapi_authentication']['he-il'] = '';
$text['label-restapi_authentication']['it-it'] = '';
$text['label-restapi_authentication']['nl-nl'] = 'Naam';
$text['label-restapi_authentication']['pl-pl'] = '';
$text['label-restapi_authentication']['pt-br'] = 'Autenticação API';
$text['label-restapi_authentication']['pt-pt'] = '';
$text['label-restapi_authentication']['ro-ro'] = '';
$text['label-restapi_authentication']['ru-ru'] = '';
$text['label-restapi_authentication']['sv-se'] = '';
$text['label-restapi_authentication']['uk-ua'] = '';



$text['label-restapi_password']['en-us'] = 'API Password';
$text['label-restapi_password']['ar-eg'] = '';
$text['label-restapi_password']['de-at'] = '';
$text['label-restapi_password']['de-ch'] = '';
$text['label-restapi_password']['de-de'] = '';
$text['label-restapi_password']['es-cl'] = '';
$text['label-restapi_password']['es-mx'] = '';
$text['label-restapi_password']['fr-ca'] = 'Nom';
$text['label-restapi_password']['fr-fr'] = 'Nom';
$text['label-restapi_password']['he-il'] = '';
$text['label-restapi_password']['it-it'] = '';
$text['label-restapi_password']['nl-nl'] = 'Naam';
$text['label-restapi_password']['pl-pl'] = '';
$text['label-restapi_password']['pt-br'] = 'Senha da API';
$text['label-restapi_password']['pt-pt'] = '';
$text['label-restapi_password']['ro-ro'] = '';
$text['label-restapi_password']['ru-ru'] = '';
$text['label-restapi_password']['sv-se'] = '';
$text['label-restapi_password']['uk-ua'] = '';


$text['label-username']['en-us'] = 'Username';
$text['label-username']['ar-eg'] = '';
$text['label-username']['de-at'] = '';
$text['label-username']['de-ch'] = '';
$text['label-username']['de-de'] = '';
$text['label-username']['es-cl'] = '';
$text['label-username']['es-mx'] = '';
$text['label-username']['fr-ca'] = 'Nom';
$text['label-username']['fr-fr'] = 'Nom';
$text['label-username']['he-il'] = '';
$text['label-username']['it-it'] = '';
$text['label-username']['nl-nl'] = 'Naam';
$text['label-username']['pl-pl'] = '';
$text['label-username']['pt-br'] = 'Usuário';
$text['label-username']['pt-pt'] = '';
$text['label-username']['ro-ro'] = '';
$text['label-username']['ru-ru'] = '';
$text['label-username']['sv-se'] = '';
$text['label-username']['uk-ua'] = '';

$text['label-token']['en-us'] = 'Token';
$text['label-token']['ar-eg'] = '';
$text['label-token']['de-at'] = '';
$text['label-token']['de-ch'] = '';
$text['label-token']['de-de'] = '';
$text['label-token']['es-cl'] = '';
$text['label-token']['es-mx'] = '';
$text['label-token']['fr-ca'] = 'Nom';
$text['label-token']['fr-fr'] = 'Nom';
$text['label-token']['he-il'] = '';
$text['label-token']['it-it'] = '';
$text['label-token']['nl-nl'] = 'Naam';
$text['label-token']['pl-pl'] = '';
$text['label-token']['pt-br'] = 'Token';
$text['label-token']['pt-pt'] = '';
$text['label-token']['ro-ro'] = '';
$text['label-token']['ru-ru'] = '';
$text['label-token']['sv-se'] = '';
$text['label-token']['uk-ua'] = '';

$text['label-user_list']['en-us'] = "User List";
$text['label-user_list']['en-gb'] = "User List";
$text['label-user_list']['ar-eg'] = "";
$text['label-user_list']['de-at'] = "Benutzer Liste"; //copied from de-de
$text['label-user_list']['de-ch'] = "Benutzer Liste"; //copied from de-de
$text['label-user_list']['de-de'] = "Benutzer Liste";
$text['label-user_list']['es-cl'] = "Listado de usuarios";
$text['label-user_list']['es-mx'] = "Listado de usuarios"; //copied from es-cl
$text['label-user_list']['fr-ca'] = "Liste d'utilisateurs"; //copied from fr-fr
$text['label-user_list']['fr-fr'] = "Liste d'utilisateurs";
$text['label-user_list']['he-il'] = "רשימת משתמשים";
$text['label-user_list']['it-it'] = "Lista Utenti";
$text['label-user_list']['nl-nl'] = "Gebruikerslijst";
$text['label-user_list']['pl-pl'] = "Lista użytkowników";
$text['label-user_list']['pt-br'] = "Utilizadores"; //copied from pt-pt
$text['label-user_list']['pt-pt'] = "Utilizadores";
$text['label-user_list']['ro-ro'] = "";
$text['label-user_list']['ru-ru'] = "Список пользователей";
$text['label-user_list']['sv-se'] = "Användar-lista";
$text['label-user_list']['uk-ua'] = "Список користувачів";

$text['label-both']['en-us'] = 'Both';
$text['label-both']['ar-eg'] = '';
$text['label-both']['de-at'] = '';
$text['label-both']['de-ch'] = '';
$text['label-both']['de-de'] = '';
$text['label-both']['es-cl'] = '';
$text['label-both']['es-mx'] = '';
$text['label-both']['fr-ca'] = 'Nom';
$text['label-both']['fr-fr'] = 'Nom';
$text['label-both']['he-il'] = '';
$text['label-both']['it-it'] = '';
$text['label-both']['nl-nl'] = 'Naam';
$text['label-both']['pl-pl'] = '';
$text['label-both']['pt-br'] = 'Ambos';
$text['label-both']['pt-pt'] = '';
$text['label-both']['ro-ro'] = '';
$text['label-both']['ru-ru'] = '';
$text['label-both']['sv-se'] = '';
$text['label-both']['uk-ua'] = '';

$text['description-restapi_name']['en-us'] = 'Enter the name.';
$text['description-restapi_name']['ar-eg'] = '';
$text['description-restapi_name']['de-at'] = '';
$text['description-restapi_name']['de-ch'] = '';
$text['description-restapi_name']['de-de'] = '';
$text['description-restapi_name']['es-cl'] = '';
$text['description-restapi_name']['es-mx'] = '';
$text['description-restapi_name']['fr-ca'] = 'Entrez le nom';
$text['description-restapi_name']['fr-fr'] = 'Entrez le nom';
$text['description-restapi_name']['he-il'] = '';
$text['description-restapi_name']['it-it'] = '';
$text['description-restapi_name']['nl-nl'] = 'Voer naam in.';
$text['description-restapi_name']['pl-pl'] = '';
$text['description-restapi_name']['pt-br'] = 'Digite o nome';
$text['description-restapi_name']['pt-pt'] = '';
$text['description-restapi_name']['ro-ro'] = '';
$text['description-restapi_name']['ru-ru'] = '';
$text['description-restapi_name']['sv-se'] = '';
$text['description-restapi_name']['uk-ua'] = '';

$text['label-restapi_category']['en-us'] = 'Category';
$text['label-restapi_category']['ar-eg'] = '';
$text['label-restapi_category']['de-at'] = '';
$text['label-restapi_category']['de-ch'] = '';
$text['label-restapi_category']['de-de'] = '';
$text['label-restapi_category']['es-cl'] = '';
$text['label-restapi_category']['es-mx'] = '';
$text['label-restapi_category']['fr-ca'] = '';
$text['label-restapi_category']['fr-fr'] = '';
$text['label-restapi_category']['he-il'] = '';
$text['label-restapi_category']['it-it'] = '';
$text['label-restapi_category']['nl-nl'] = '';
$text['label-restapi_category']['pl-pl'] = '';
$text['label-restapi_category']['pt-br'] = 'Categoria';
$text['label-restapi_category']['pt-pt'] = '';
$text['label-restapi_category']['ro-ro'] = '';
$text['label-restapi_category']['ru-ru'] = '';
$text['label-restapi_category']['sv-se'] = '';
$text['label-restapi_category']['uk-ua'] = '';

$text['description-restapi_category']['en-us'] = 'Enter the category.';
$text['description-restapi_category']['ar-eg'] = '';
$text['description-restapi_category']['de-at'] = '';
$text['description-restapi_category']['de-ch'] = '';
$text['description-restapi_category']['de-de'] = '';
$text['description-restapi_category']['es-cl'] = '';
$text['description-restapi_category']['es-mx'] = '';
$text['description-restapi_category']['fr-ca'] = '';
$text['description-restapi_category']['fr-fr'] = '';
$text['description-restapi_category']['he-il'] = '';
$text['description-restapi_category']['it-it'] = '';
$text['description-restapi_category']['nl-nl'] = '';
$text['description-restapi_category']['pl-pl'] = '';
$text['description-restapi_category']['pt-br'] = 'Digite a categoria';
$text['description-restapi_category']['pt-pt'] = '';
$text['description-restapi_category']['ro-ro'] = '';
$text['description-restapi_category']['ru-ru'] = '';
$text['description-restapi_category']['sv-se'] = '';
$text['description-restapi_category']['uk-ua'] = '';



$text['description-restapi_password']['en-us'] = 'Enter the API password.';
$text['description-restapi_password']['ar-eg'] = '';
$text['description-restapi_password']['de-at'] = '';
$text['description-restapi_password']['de-ch'] = '';
$text['description-restapi_password']['de-de'] = '';
$text['description-restapi_password']['es-cl'] = '';
$text['description-restapi_password']['es-mx'] = '';
$text['description-restapi_password']['fr-ca'] = '';
$text['description-restapi_password']['fr-fr'] = '';
$text['description-restapi_password']['he-il'] = '';
$text['description-restapi_password']['it-it'] = '';
$text['description-restapi_password']['nl-nl'] = '';
$text['description-restapi_password']['pl-pl'] = '';
$text['description-restapi_password']['pt-br'] = 'Digite a senha da API';
$text['description-restapi_password']['pt-pt'] = '';
$text['description-restapi_password']['ro-ro'] = '';
$text['description-restapi_password']['ru-ru'] = '';
$text['description-restapi_password']['sv-se'] = '';
$text['description-restapi_password']['uk-ua'] = '';




$text['description-restapi_username']['en-us'] = 'Enter the API username.';
$text['description-restapi_username']['ar-eg'] = '';
$text['description-restapi_username']['de-at'] = '';
$text['description-restapi_username']['de-ch'] = '';
$text['description-restapi_username']['de-de'] = '';
$text['description-restapi_username']['es-cl'] = '';
$text['description-restapi_username']['es-mx'] = '';
$text['description-restapi_username']['fr-ca'] = '';
$text['description-restapi_username']['fr-fr'] = '';
$text['description-restapi_username']['he-il'] = '';
$text['description-restapi_username']['it-it'] = '';
$text['description-restapi_username']['nl-nl'] = '';
$text['description-restapi_username']['pl-pl'] = '';
$text['description-restapi_username']['pt-br'] = 'Digite o usuário da API';
$text['description-restapi_username']['pt-pt'] = '';
$text['description-restapi_username']['ro-ro'] = '';
$text['description-restapi_username']['ru-ru'] = '';
$text['description-restapi_username']['sv-se'] = '';
$text['description-restapi_username']['uk-ua'] = '';







$text['label-restapi_global']['en-us'] = 'Global';
$text['label-restapi_global']['ar-eg'] = '';
$text['label-restapi_global']['de-at'] = '';
$text['label-restapi_global']['de-ch'] = '';
$text['label-restapi_global']['de-de'] = '';
$text['label-restapi_global']['es-cl'] = '';
$text['label-restapi_global']['es-mx'] = '';
$text['label-restapi_global']['fr-ca'] = '';
$text['label-restapi_global']['fr-fr'] = '';
$text['label-restapi_global']['he-il'] = '';
$text['label-restapi_global']['it-it'] = '';
$text['label-restapi_global']['nl-nl'] = '';
$text['label-restapi_global']['pl-pl'] = '';
$text['label-restapi_global']['pt-br'] = 'Global';
$text['label-restapi_global']['pt-pt'] = '';
$text['label-restapi_global']['ro-ro'] = '';
$text['label-restapi_global']['ru-ru'] = '';
$text['label-restapi_global']['sv-se'] = '';
$text['label-restapi_global']['uk-ua'] = '';

$text['description-restapi_global']['en-us'] = 'Select if global or local to domain.';
$text['description-restapi_global']['ar-eg'] = '';
$text['description-restapi_global']['de-at'] = '';
$text['description-restapi_global']['de-ch'] = '';
$text['description-restapi_global']['de-de'] = '';
$text['description-restapi_global']['es-cl'] = '';
$text['description-restapi_global']['es-mx'] = '';
$text['description-restapi_global']['fr-ca'] = '';
$text['description-restapi_global']['fr-fr'] = '';
$text['description-restapi_global']['he-il'] = '';
$text['description-restapi_global']['it-it'] = '';
$text['description-restapi_global']['nl-nl'] = '';
$text['description-restapi_global']['pl-pl'] = '';
$text['description-restapi_global']['pt-br'] = 'Selecione se é global ou local para o domínio';
$text['description-restapi_global']['pt-pt'] = '';
$text['description-restapi_global']['ro-ro'] = '';
$text['description-restapi_global']['ru-ru'] = '';
$text['description-restapi_global']['sv-se'] = '';
$text['description-restapi_global']['uk-ua'] = '';

$text['label-restapi_method']['en-us'] = 'Method';
$text['label-restapi_method']['ar-eg'] = '';
$text['label-restapi_method']['de-at'] = '';
$text['label-restapi_method']['de-ch'] = '';
$text['label-restapi_method']['de-de'] = '';
$text['label-restapi_method']['es-cl'] = '';
$text['label-restapi_method']['es-mx'] = '';
$text['label-restapi_method']['fr-ca'] = '';
$text['label-restapi_method']['fr-fr'] = '';
$text['label-restapi_method']['he-il'] = '';
$text['label-restapi_method']['it-it'] = '';
$text['label-restapi_method']['nl-nl'] = '';
$text['label-restapi_method']['pl-pl'] = '';
$text['label-restapi_method']['pt-br'] = 'Método';
$text['label-restapi_method']['pt-pt'] = '';
$text['label-restapi_method']['ro-ro'] = '';
$text['label-restapi_method']['ru-ru'] = '';
$text['label-restapi_method']['sv-se'] = '';
$text['label-restapi_method']['uk-ua'] = '';

$text['description-restapi_method']['en-us'] = 'Enter the method.';
$text['description-restapi_method']['ar-eg'] = '';
$text['description-restapi_method']['de-at'] = '';
$text['description-restapi_method']['de-ch'] = '';
$text['description-restapi_method']['de-de'] = '';
$text['description-restapi_method']['es-cl'] = '';
$text['description-restapi_method']['es-mx'] = '';
$text['description-restapi_method']['fr-ca'] = '';
$text['description-restapi_method']['fr-fr'] = '';
$text['description-restapi_method']['he-il'] = '';
$text['description-restapi_method']['it-it'] = '';
$text['description-restapi_method']['nl-nl'] = '';
$text['description-restapi_method']['pl-pl'] = '';
$text['description-restapi_method']['pt-br'] = 'Escolha o método';
$text['description-restapi_method']['pt-pt'] = '';
$text['description-restapi_method']['ro-ro'] = '';
$text['description-restapi_method']['ru-ru'] = '';
$text['description-restapi_method']['sv-se'] = '';
$text['description-restapi_method']['uk-ua'] = '';

$text['label-restapi_uri']['en-us'] = 'URI';
$text['label-restapi_uri']['ar-eg'] = '';
$text['label-restapi_uri']['de-at'] = '';
$text['label-restapi_uri']['de-ch'] = '';
$text['label-restapi_uri']['de-de'] = '';
$text['label-restapi_uri']['es-cl'] = '';
$text['label-restapi_uri']['es-mx'] = '';
$text['label-restapi_uri']['fr-ca'] = '';
$text['label-restapi_uri']['fr-fr'] = '';
$text['label-restapi_uri']['he-il'] = '';
$text['label-restapi_uri']['it-it'] = '';
$text['label-restapi_uri']['nl-nl'] = '';
$text['label-restapi_uri']['pl-pl'] = '';
$text['label-restapi_uri']['pt-br'] = '';
$text['label-restapi_uri']['pt-pt'] = '';
$text['label-restapi_uri']['ro-ro'] = '';
$text['label-restapi_uri']['ru-ru'] = '';
$text['label-restapi_uri']['sv-se'] = '';
$text['label-restapi_uri']['uk-ua'] = '';


$text['label-restapi_redirect']['en-us'] = 'Redirect URL';
$text['label-restapi_redirect']['ar-eg'] = '';
$text['label-restapi_redirect']['de-at'] = '';
$text['label-restapi_redirect']['de-ch'] = '';
$text['label-restapi_redirect']['de-de'] = '';
$text['label-restapi_redirect']['es-cl'] = '';
$text['label-restapi_redirect']['es-mx'] = '';
$text['label-restapi_redirect']['fr-ca'] = '';
$text['label-restapi_redirect']['fr-fr'] = '';
$text['label-restapi_redirect']['he-il'] = '';
$text['label-restapi_redirect']['it-it'] = '';
$text['label-restapi_redirect']['nl-nl'] = '';
$text['label-restapi_redirect']['pl-pl'] = '';
$text['label-restapi_redirect']['pt-br'] = '';
$text['label-restapi_redirect']['pt-pt'] = '';
$text['label-restapi_redirect']['ro-ro'] = '';
$text['label-restapi_redirect']['ru-ru'] = '';
$text['label-restapi_redirect']['sv-se'] = '';
$text['label-restapi_redirect']['uk-ua'] = '';

$text['description-restapi_uri']['en-us'] = 'Enter the URI.';
$text['description-restapi_uri']['ar-eg'] = '';
$text['description-restapi_uri']['de-at'] = '';
$text['description-restapi_uri']['de-ch'] = '';
$text['description-restapi_uri']['de-de'] = '';
$text['description-restapi_uri']['es-cl'] = '';
$text['description-restapi_uri']['es-mx'] = '';
$text['description-restapi_uri']['fr-ca'] = '';
$text['description-restapi_uri']['fr-fr'] = '';
$text['description-restapi_uri']['he-il'] = '';
$text['description-restapi_uri']['it-it'] = '';
$text['description-restapi_uri']['nl-nl'] = '';
$text['description-restapi_uri']['pl-pl'] = '';
$text['description-restapi_uri']['pt-br'] = '';
$text['description-restapi_uri']['pt-pt'] = '';
$text['description-restapi_uri']['ro-ro'] = '';
$text['description-restapi_uri']['ru-ru'] = '';
$text['description-restapi_uri']['sv-se'] = '';
$text['description-restapi_uri']['uk-ua'] = '';



$text['description-restapi_redirect']['en-us'] = 'Enter the Redirect URL.';
$text['description-restapi_redirect']['ar-eg'] = '';
$text['description-restapi_redirect']['de-at'] = '';
$text['description-restapi_redirect']['de-ch'] = '';
$text['description-restapi_redirect']['de-de'] = '';
$text['description-restapi_redirect']['es-cl'] = '';
$text['description-restapi_redirect']['es-mx'] = '';
$text['description-restapi_redirect']['fr-ca'] = '';
$text['description-restapi_redirect']['fr-fr'] = '';
$text['description-restapi_redirect']['he-il'] = '';
$text['description-restapi_redirect']['it-it'] = '';
$text['description-restapi_redirect']['nl-nl'] = '';
$text['description-restapi_redirect']['pl-pl'] = '';
$text['description-restapi_redirect']['pt-br'] = '';
$text['description-restapi_redirect']['pt-pt'] = '';
$text['description-restapi_redirect']['ro-ro'] = '';
$text['description-restapi_redirect']['ru-ru'] = '';
$text['description-restapi_redirect']['sv-se'] = '';
$text['description-restapi_redirect']['uk-ua'] = '';

$text['label-restapi_sql']['en-us'] = 'SQL';
$text['label-restapi_sql']['ar-eg'] = '';
$text['label-restapi_sql']['de-at'] = '';
$text['label-restapi_sql']['de-ch'] = '';
$text['label-restapi_sql']['de-de'] = '';
$text['label-restapi_sql']['es-cl'] = '';
$text['label-restapi_sql']['es-mx'] = '';
$text['label-restapi_sql']['fr-ca'] = '';
$text['label-restapi_sql']['fr-fr'] = '';
$text['label-restapi_sql']['he-il'] = '';
$text['label-restapi_sql']['it-it'] = '';
$text['label-restapi_sql']['nl-nl'] = '';
$text['label-restapi_sql']['pl-pl'] = '';
$text['label-restapi_sql']['pt-br'] = '';
$text['label-restapi_sql']['pt-pt'] = '';
$text['label-restapi_sql']['ro-ro'] = '';
$text['label-restapi_sql']['ru-ru'] = '';
$text['label-restapi_sql']['sv-se'] = '';
$text['label-restapi_sql']['uk-ua'] = '';


$text['description-user_list']['en-us'] = "Define users assigned to this ring group.";
$text['description-user_list']['en-gb'] = "Define users assigned to this ring group.";
$text['description-user_list']['ar-eg'] = "";
$text['description-user_list']['de-at'] = "Weisen Sie diese Rufgruppe Benutzern zu."; //copied from de-de
$text['description-user_list']['de-ch'] = "Weisen Sie diese Rufgruppe Benutzern zu."; //copied from de-de
$text['description-user_list']['de-de'] = "Weisen Sie diese Rufgruppe Benutzern zu.";
$text['description-user_list']['es-cl'] = "Define los usuarios que serán asignados a este grupo de llamado";
$text['description-user_list']['es-mx'] = "Define los usuarios que serán asignados a este grupo de llamado"; //copied from es-cl
$text['description-user_list']['fr-ca'] = "Associer les utilisateurs à ce groupe de sonnerie. "; //copied from fr-fr
$text['description-user_list']['fr-fr'] = "Associer les utilisateurs à ce groupe de sonnerie. ";
$text['description-user_list']['he-il'] = "";
$text['description-user_list']['it-it'] = "Seleziona gli utenti che sono assegnati a questo gruppo di squillo.";
$text['description-user_list']['nl-nl'] = "Deinieer gebruikers die aan deze belgroep toegewezen zijn.";
$text['description-user_list']['pl-pl'] = "Przypisz użytkowników do grupy odbiorców rozmów.";
$text['description-user_list']['pt-br'] = "Atribua os utilizadores que estão associados a essa extensão";
$text['description-user_list']['pt-pt'] = "Associar utilizadores ao grupo.";
$text['description-user_list']['ro-ro'] = "";
$text['description-user_list']['ru-ru'] = "Назначьте пользователей, которые будут членами этой группе вызовов.";
$text['description-user_list']['sv-se'] = "Tilldela användare till denna ringgrupp.";
$text['description-user_list']['uk-ua'] = "";


$text['label-restapi_endpoint']['en-us'] = 'Endpoint';
$text['label-restapi_endpoint']['ar-eg'] = '';
$text['label-restapi_endpoint']['de-at'] = '';
$text['label-restapi_endpoint']['de-ch'] = '';
$text['label-restapi_endpoint']['de-de'] = '';
$text['label-restapi_endpoint']['es-cl'] = '';
$text['label-restapi_endpoint']['es-mx'] = '';
$text['label-restapi_endpoint']['fr-ca'] = '';
$text['label-restapi_endpoint']['fr-fr'] = '';
$text['label-restapi_endpoint']['he-il'] = '';
$text['label-restapi_endpoint']['it-it'] = '';
$text['label-restapi_endpoint']['nl-nl'] = '';
$text['label-restapi_endpoint']['pl-pl'] = '';
$text['label-restapi_endpoint']['pt-br'] = 'Endpoint';
$text['label-restapi_endpoint']['pt-pt'] = '';
$text['label-restapi_endpoint']['ro-ro'] = '';
$text['label-restapi_endpoint']['ru-ru'] = '';
$text['label-restapi_endpoint']['sv-se'] = '';
$text['label-restapi_endpoint']['uk-ua'] = '';


$text['label-restapi_carrier']['en-us'] = 'Application';
$text['label-restapi_carrier']['ar-eg'] = '';
$text['label-restapi_carrier']['de-at'] = '';
$text['label-restapi_carrier']['de-ch'] = '';
$text['label-restapi_carrier']['de-de'] = '';
$text['label-restapi_carrier']['es-cl'] = '';
$text['label-restapi_carrier']['es-mx'] = '';
$text['label-restapi_carrier']['fr-ca'] = '';
$text['label-restapi_carrier']['fr-fr'] = '';
$text['label-restapi_carrier']['he-il'] = '';
$text['label-restapi_carrier']['it-it'] = '';
$text['label-restapi_carrier']['nl-nl'] = '';
$text['label-restapi_carrier']['pl-pl'] = '';
$text['label-restapi_carrier']['pt-br'] = 'Aplicativo';
$text['label-restapi_carrier']['pt-pt'] = '';
$text['label-restapi_carrier']['ro-ro'] = '';
$text['label-restapi_carrier']['ru-ru'] = '';
$text['label-restapi_carrier']['sv-se'] = '';
$text['label-restapi_carrier']['uk-ua'] = '';



$text['description-restapi_carrier']['en-us'] = 'Endpoint Application';
$text['description-restapi_carrier']['ar-eg'] = '';
$text['description-restapi_carrier']['de-at'] = '';
$text['description-restapi_carrier']['de-ch'] = '';
$text['description-restapi_carrier']['de-de'] = '';
$text['description-restapi_carrier']['es-cl'] = '';
$text['description-restapi_carrier']['es-mx'] = '';
$text['description-restapi_carrier']['fr-ca'] = '';
$text['description-restapi_carrier']['fr-fr'] = '';
$text['description-restapi_carrier']['he-il'] = '';
$text['description-restapi_carrier']['it-it'] = '';
$text['description-restapi_carrier']['nl-nl'] = '';
$text['description-restapi_carrier']['pl-pl'] = '';
$text['description-restapi_carrier']['pt-br'] = 'Aplicativo da API';
$text['description-restapi_carrier']['pt-pt'] = '';
$text['description-restapi_carrier']['ro-ro'] = '';
$text['description-restapi_carrier']['ru-ru'] = '';
$text['description-restapi_carrier']['sv-se'] = '';
$text['description-restapi_carrier']['uk-ua'] = '';


$text['label-restapi_token']['en-us'] = 'Token';
$text['label-restapi_token']['ar-eg'] = '';
$text['label-restapi_token']['de-at'] = '';
$text['label-restapi_token']['de-ch'] = '';
$text['label-restapi_token']['de-de'] = '';
$text['label-restapi_token']['es-cl'] = '';
$text['label-restapi_token']['es-mx'] = '';
$text['label-restapi_token']['fr-ca'] = '';
$text['label-restapi_token']['fr-fr'] = '';
$text['label-restapi_token']['he-il'] = '';
$text['label-restapi_token']['it-it'] = '';
$text['label-restapi_token']['nl-nl'] = '';
$text['label-restapi_token']['pl-pl'] = '';
$text['label-restapi_token']['pt-br'] = 'Token';
$text['label-restapi_token']['pt-pt'] = '';
$text['label-restapi_token']['ro-ro'] = '';
$text['label-restapi_token']['ru-ru'] = '';
$text['label-restapi_token']['sv-se'] = '';
$text['label-restapi_token']['uk-ua'] = '';


$text['description-restapi_token']['en-us'] = 'Authentication Token.';
$text['description-restapi_token']['ar-eg'] = '';
$text['description-restapi_token']['de-at'] = '';
$text['description-restapi_token']['de-ch'] = '';
$text['description-restapi_token']['de-de'] = '';
$text['description-restapi_token']['es-cl'] = '';
$text['description-restapi_token']['es-mx'] = '';
$text['description-restapi_token']['fr-ca'] = '';
$text['description-restapi_token']['fr-fr'] = '';
$text['description-restapi_token']['he-il'] = '';
$text['description-restapi_token']['it-it'] = '';
$text['description-restapi_token']['nl-nl'] = '';
$text['description-restapi_token']['pl-pl'] = '';
$text['description-restapi_token']['pt-br'] = 'Token de Autenticação.';
$text['description-restapi_token']['pt-pt'] = '';
$text['description-restapi_token']['ro-ro'] = '';
$text['description-restapi_token']['ru-ru'] = '';
$text['description-restapi_token']['sv-se'] = '';
$text['description-restapi_token']['uk-ua'] = '';


$text['button-restapi_endpoint']['en-us'] = 'Endpoints';
$text['button-restapi_endpoint']['ar-eg'] = '';
$text['button-restapi_endpoint']['de-at'] = '';
$text['button-restapi_endpoint']['de-ch'] = '';
$text['button-restapi_endpoint']['de-de'] = '';
$text['button-restapi_endpoint']['es-cl'] = '';
$text['button-restapi_endpoint']['es-mx'] = '';
$text['button-restapi_endpoint']['fr-ca'] = '';
$text['button-restapi_endpoint']['fr-fr'] = '';
$text['button-restapi_endpoint']['he-il'] = '';
$text['button-restapi_endpoint']['it-it'] = '';
$text['button-restapi_endpoint']['nl-nl'] = '';
$text['button-restapi_endpoint']['pl-pl'] = '';
$text['button-restapi_endpoint']['pt-br'] = 'Endpoints';
$text['button-restapi_endpoint']['pt-pt'] = '';
$text['button-restapi_endpoint']['ro-ro'] = '';
$text['button-restapi_endpoint']['ru-ru'] = '';
$text['button-restapi_endpoint']['sv-se'] = '';
$text['button-restapi_endpoint']['uk-ua'] = '';


$text['button-restapi']['en-us'] = 'Rest APIs';
$text['button-restapi']['ar-eg'] = 'Rest APIs';
$text['button-restapi']['de-at'] = 'Rest APIs';
$text['button-restapi']['de-ch'] = 'Rest APIs';
$text['button-restapi']['de-de'] = 'Rest APIs';
$text['button-restapi']['es-cl'] = 'Rest APIs';
$text['button-restapi']['es-mx'] = 'Rest APIs';
$text['button-restapi']['fr-ca'] = 'Rest APIs';
$text['button-restapi']['fr-fr'] = 'Rest APIs';
$text['button-restapi']['he-il'] = 'Rest APIs';
$text['button-restapi']['it-it'] = 'Rest APIs';
$text['button-restapi']['nl-nl'] = 'Rest APIs';
$text['button-restapi']['pl-pl'] = 'Rest APIs';
$text['button-restapi']['pt-br'] = 'Rest APIs';
$text['button-restapi']['pt-pt'] = 'Rest APIs';
$text['button-restapi']['ro-ro'] = 'Rest APIs';
$text['button-restapi']['ru-ru'] = 'Rest APIs';
$text['button-restapi']['sv-se'] = 'Rest APIs';
$text['button-restapi']['uk-ua'] = 'Rest APIs';

$text['description-restapi_sql']['en-us'] = 'Enter the SQL.';
$text['description-restapi_sql']['ar-eg'] = '';
$text['description-restapi_sql']['de-at'] = '';
$text['description-restapi_sql']['de-ch'] = '';
$text['description-restapi_sql']['de-de'] = '';
$text['description-restapi_sql']['es-cl'] = '';
$text['description-restapi_sql']['es-mx'] = '';
$text['description-restapi_sql']['fr-ca'] = '';
$text['description-restapi_sql']['fr-fr'] = '';
$text['description-restapi_sql']['he-il'] = '';
$text['description-restapi_sql']['it-it'] = '';
$text['description-restapi_sql']['nl-nl'] = '';
$text['description-restapi_sql']['pl-pl'] = '';
$text['description-restapi_sql']['pt-br'] = '';
$text['description-restapi_sql']['pt-pt'] = '';
$text['description-restapi_sql']['ro-ro'] = '';
$text['description-restapi_sql']['ru-ru'] = '';
$text['description-restapi_sql']['sv-se'] = '';
$text['description-restapi_sql']['uk-ua'] = '';

$text['label-restapi_enabled']['en-us'] = 'Enabled';
$text['label-restapi_enabled']['ar-eg'] = '';
$text['label-restapi_enabled']['de-at'] = '';
$text['label-restapi_enabled']['de-ch'] = '';
$text['label-restapi_enabled']['de-de'] = '';
$text['label-restapi_enabled']['es-cl'] = '';
$text['label-restapi_enabled']['es-mx'] = '';
$text['label-restapi_enabled']['fr-ca'] = 'Activé';
$text['label-restapi_enabled']['fr-fr'] = 'Activé';
$text['label-restapi_enabled']['he-il'] = '';
$text['label-restapi_enabled']['it-it'] = '';
$text['label-restapi_enabled']['nl-nl'] = 'Geactiveerd';
$text['label-restapi_enabled']['pl-pl'] = '';
$text['label-restapi_enabled']['pt-br'] = '';
$text['label-restapi_enabled']['pt-pt'] = '';
$text['label-restapi_enabled']['ro-ro'] = '';
$text['label-restapi_enabled']['ru-ru'] = '';
$text['label-restapi_enabled']['sv-se'] = '';
$text['label-restapi_enabled']['uk-ua'] = '';

$text['description-restapi_enabled']['en-us'] = 'Select to enable or disable.';
$text['description-restapi_enabled']['ar-eg'] = '';
$text['description-restapi_enabled']['de-at'] = '';
$text['description-restapi_enabled']['de-ch'] = '';
$text['description-restapi_enabled']['de-de'] = '';
$text['description-restapi_enabled']['es-cl'] = '';
$text['description-restapi_enabled']['es-mx'] = '';
$text['description-restapi_enabled']['fr-ca'] = 'Sélectionnez pour activer ou désactiver';
$text['description-restapi_enabled']['fr-fr'] = 'Sélectionnez pour activer ou désactiver';
$text['description-restapi_enabled']['he-il'] = '';
$text['description-restapi_enabled']['it-it'] = '';
$text['description-restapi_enabled']['nl-nl'] = 'Kies aktiveer/deactiveer.';
$text['description-restapi_enabled']['pl-pl'] = '';
$text['description-restapi_enabled']['pt-br'] = '';
$text['description-restapi_enabled']['pt-pt'] = '';
$text['description-restapi_enabled']['ro-ro'] = '';
$text['description-restapi_enabled']['ru-ru'] = '';
$text['description-restapi_enabled']['sv-se'] = '';
$text['description-restapi_enabled']['uk-ua'] = '';

$text['description-restapi_description']['en-us'] = 'Enter the description. ';
$text['description-restapi_description']['ar-eg'] = '';
$text['description-restapi_description']['de-at'] = '';
$text['description-restapi_description']['de-ch'] = '';
$text['description-restapi_description']['de-de'] = '';
$text['description-restapi_description']['es-cl'] = '';
$text['description-restapi_description']['es-mx'] = '';
$text['description-restapi_description']['fr-ca'] = 'Entrez la description';
$text['description-restapi_description']['fr-fr'] = 'Entrez la description';
$text['description-restapi_description']['he-il'] = '';
$text['description-restapi_description']['it-it'] = '';
$text['description-restapi_description']['nl-nl'] = 'Voer omschrijving in.';
$text['description-restapi_description']['pl-pl'] = '';
$text['description-restapi_description']['pt-br'] = '';
$text['description-restapi_description']['pt-pt'] = '';
$text['description-restapi_description']['ro-ro'] = '';
$text['description-restapi_description']['ru-ru'] = '';
$text['description-restapi_description']['sv-se'] = '';
$text['description-restapi_description']['uk-ua'] = '';

$text['label-restapi_description']['en-us'] = "Description";
$text['label-restapi_description']['ar-eg'] = "";
$text['label-restapi_description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-restapi_description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-restapi_description']['de-de'] = "Beschreibung";
$text['label-restapi_description']['es-cl'] = "Descripción";
$text['label-restapi_description']['es-mx'] = "Descripción"; //copied from es-cl
$text['label-restapi_description']['fr-ca'] = "Description"; //copied from fr-fr
$text['label-restapi_description']['fr-fr'] = "Description";
$text['label-restapi_description']['he-il'] = "";
$text['label-restapi_description']['it-it'] = "Descrizione";
$text['label-restapi_description']['nl-nl'] = "Omschrijving";
$text['label-restapi_description']['pl-pl'] = "Opis";
$text['label-restapi_description']['pt-br'] = "Descrição";
$text['label-restapi_description']['pt-pt'] = "Descripção";
$text['label-restapi_description']['ro-ro'] = "";
$text['label-restapi_description']['ru-ru'] = "Описание";
$text['label-restapi_description']['sv-se'] = "Beskrivning";
$text['label-restapi_description']['uk-ua'] = "Опис";
$text['label-restapi_description']['tr-tr'] = "Açıklama";

?>
