<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-flux_providers']['en-us'] = "Flux Providers";
$text['title-flux_providers']['en-gb'] = "Flux Providers";
$text['title-flux_providers']['ar-eg'] = "";
$text['title-flux_providers']['de-at'] = "Rufgruppen"; //copied from de-de
$text['title-flux_providers']['de-ch'] = "Rufgruppen"; //copied from de-de
$text['title-flux_providers']['de-de'] = "Rufgruppen";
$text['title-flux_providers']['es-cl'] = "Grupo de llamado";
$text['title-flux_providers']['es-mx'] = "Grupo de llamado"; //copied from es-cl
$text['title-flux_providers']['fr-ca'] = "Groupes de Sonnerie"; //copied from fr-fr
$text['title-flux_providers']['fr-fr'] = "Groupes de Sonnerie";
$text['title-flux_providers']['he-il'] = "קבוצות חיוג";
$text['title-flux_providers']['it-it'] = "Gruppi di Squillo";
$text['title-flux_providers']['nl-nl'] = "Bel groepen";
$text['title-flux_providers']['pl-pl'] = "Grupy odbiorców rozmów";
$text['title-flux_providers']['pt-br'] = "Provedores Flux API";
$text['title-flux_providers']['pt-pt'] = "Grupos";
$text['title-flux_providers']['ro-ro'] = "";
$text['title-flux_providers']['ru-ru'] = "Группа вызовов";
$text['title-flux_providers']['sv-se'] = "Ringgrupper";
$text['title-flux_providers']['uk-ua'] = "Групи";


$text['title-flux_providers_users']['en-us'] = "Flux Providers Users";
$text['title-flux_providers_users']['en-gb'] = "Flux Providers Users";
$text['title-flux_providers_users']['ar-eg'] = "";
$text['title-flux_providers_users']['de-at'] = "Rufgruppen"; //copied from de-de
$text['title-flux_providers_users']['de-ch'] = "Rufgruppen"; //copied from de-de
$text['title-flux_providers_users']['de-de'] = "Rufgruppen";
$text['title-flux_providers_users']['es-cl'] = "Grupo de llamado";
$text['title-flux_providers_users']['es-mx'] = "Grupo de llamado"; //copied from es-cl
$text['title-flux_providers_users']['fr-ca'] = "Groupes de Sonnerie"; //copied from fr-fr
$text['title-flux_providers_users']['fr-fr'] = "Groupes de Sonnerie";
$text['title-flux_providers_users']['he-il'] = "קבוצות חיוג";
$text['title-flux_providers_users']['it-it'] = "Gruppi di Squillo";
$text['title-flux_providers_users']['nl-nl'] = "Bel groepen";
$text['title-flux_providers_users']['pl-pl'] = "Grupy odbiorców rozmów";
$text['title-flux_providers_users']['pt-br'] = "Usuários Flux API";
$text['title-flux_providers_users']['pt-pt'] = "Grupos";
$text['title-flux_providers_users']['ro-ro'] = "";
$text['title-flux_providers_users']['ru-ru'] = "Группа вызовов";
$text['title-flux_providers_users']['sv-se'] = "Ringgrupper";
$text['title-flux_providers_users']['uk-ua'] = "Групи";

$text['title-flux_provider']['en-us'] = "Flux Provider";
$text['title-flux_provider']['en-gb'] = "Flux Provider";
$text['title-flux_provider']['ar-eg'] = "";
$text['title-flux_provider']['de-at'] = "Rufgruppen"; //copied from de-de
$text['title-flux_provider']['de-ch'] = "Rufgruppen"; //copied from de-de
$text['title-flux_provider']['de-de'] = "Rufgruppen";
$text['title-flux_provider']['es-cl'] = "Grupo de llamado";
$text['title-flux_provider']['es-mx'] = "Grupo de llamado"; //copied from es-cl
$text['title-flux_provider']['fr-ca'] = "Groupes de Sonnerie"; //copied from fr-fr
$text['title-flux_provider']['fr-fr'] = "Groupes de Sonnerie";
$text['title-flux_provider']['he-il'] = "קבוצות חיוג";
$text['title-flux_provider']['it-it'] = "Gruppi di Squillo";
$text['title-flux_provider']['nl-nl'] = "Bel groepen";
$text['title-flux_provider']['pl-pl'] = "Grupy odbiorców rozmów";
$text['title-flux_provider']['pt-br'] = "Provedor Flux API";
$text['title-flux_provider']['pt-pt'] = "Grupos";
$text['title-flux_provider']['ro-ro'] = "";
$text['title-flux_provider']['ru-ru'] = "Группа вызовов";
$text['title-flux_provider']['sv-se'] = "Ringgrupper";
$text['title-flux_provider']['uk-ua'] = "Групи";

$text['option-simultaneous']['en-us'] = "Simultaneous";
$text['option-simultaneous']['en-gb'] = "Simultaneous";
$text['option-simultaneous']['ar-eg'] = "";
$text['option-simultaneous']['de-at'] = "gleichzeitig"; //copied from de-de
$text['option-simultaneous']['de-ch'] = "gleichzeitig"; //copied from de-de
$text['option-simultaneous']['de-de'] = "gleichzeitig";
$text['option-simultaneous']['es-cl'] = "Simultaneos";
$text['option-simultaneous']['es-mx'] = "Simultaneos"; //copied from es-cl
$text['option-simultaneous']['fr-ca'] = "Simultané"; //copied from fr-fr
$text['option-simultaneous']['fr-fr'] = "Simultané";
$text['option-simultaneous']['he-il'] = "באותו הזמן";
$text['option-simultaneous']['it-it'] = "Parallelo";
$text['option-simultaneous']['nl-nl'] = "Gelijktijdig";
$text['option-simultaneous']['pl-pl'] = "Jednoczesne";
$text['option-simultaneous']['pt-br'] = "Simultâneo"; //copied from pt-pt
$text['option-simultaneous']['pt-pt'] = "Simultâneo";
$text['option-simultaneous']['ro-ro'] = "";
$text['option-simultaneous']['ru-ru'] = "Одновременное";
$text['option-simultaneous']['sv-se'] = "Samtidig";
$text['option-simultaneous']['uk-ua'] = "";

$text['option-sequence']['en-us'] = "Sequence";
$text['option-sequence']['en-gb'] = "Sequence";
$text['option-sequence']['ar-eg'] = "";
$text['option-sequence']['de-at'] = "sequenziell"; //copied from de-de
$text['option-sequence']['de-ch'] = "sequenziell"; //copied from de-de
$text['option-sequence']['de-de'] = "sequenziell";
$text['option-sequence']['es-cl'] = "Secuencia";
$text['option-sequence']['es-mx'] = "Secuencia"; //copied from es-cl
$text['option-sequence']['fr-ca'] = "Séquence"; //copied from fr-fr
$text['option-sequence']['fr-fr'] = "Séquence";
$text['option-sequence']['he-il'] = "אחד אחרי השני";
$text['option-sequence']['it-it'] = "Sequenza";
$text['option-sequence']['nl-nl'] = "Opeenvolgend";
$text['option-sequence']['pl-pl'] = "Kolejne";
$text['option-sequence']['pt-br'] = "Sequência"; //copied from pt-pt
$text['option-sequence']['pt-pt'] = "Sequência";
$text['option-sequence']['ro-ro'] = "";
$text['option-sequence']['ru-ru'] = "Последовательность";
$text['option-sequence']['sv-se'] = "I Ordning";
$text['option-sequence']['uk-ua'] = "";

$text['option-rollover']['en-us'] = "Rollover";
$text['option-rollover']['en-gb'] = "Rollover";
$text['option-rollover']['ar-eg'] = "";
$text['option-rollover']['de-at'] = "Rotierend"; //copied from de-de
$text['option-rollover']['de-ch'] = "Rotierend"; //copied from de-de
$text['option-rollover']['de-de'] = "Rotierend";
$text['option-rollover']['es-cl'] = "Rollover";
$text['option-rollover']['es-mx'] = "Rollover"; //copied from es-cl
$text['option-rollover']['fr-ca'] = "capotage"; //copied from fr-fr
$text['option-rollover']['fr-fr'] = "capotage";
$text['option-rollover']['he-il'] = "";
$text['option-rollover']['it-it'] = "Sequenza (liberi)";
$text['option-rollover']['nl-nl'] = "Overlappend";
$text['option-rollover']['pl-pl'] = "Rollover ";
$text['option-rollover']['pt-br'] = "Rollover"; //copied from pt-pt
$text['option-rollover']['pt-pt'] = "Rollover";
$text['option-rollover']['ro-ro'] = "";
$text['option-rollover']['ru-ru'] = "Переходить";
$text['option-rollover']['sv-se'] = "Revolver";
$text['option-rollover']['uk-ua'] = "";

$text['option-random']['en-us'] = "Random";
$text['option-random']['en-gb'] = "Random";
$text['option-random']['ar-eg'] = "";
$text['option-random']['de-at'] = "Zufällig"; //copied from de-de
$text['option-random']['de-ch'] = "Zufällig"; //copied from de-de
$text['option-random']['de-de'] = "Zufällig";
$text['option-random']['es-cl'] = "Aleatorio";
$text['option-random']['es-mx'] = "Aleatorio"; //copied from es-cl
$text['option-random']['fr-ca'] = "Aléatoire";
$text['option-random']['fr-fr'] = "Aléatoire";
$text['option-random']['he-il'] = "";
$text['option-random']['it-it'] = "Casuale";
$text['option-random']['nl-nl'] = "Willekurig";
$text['option-random']['pl-pl'] = "";
$text['option-random']['pt-br'] = "";
$text['option-random']['pt-pt'] = "";
$text['option-random']['ro-ro'] = "";
$text['option-random']['ru-ru'] = "Случайная";
$text['option-random']['sv-se'] = "Slumpmässig";
$text['option-random']['uk-ua'] = "";

$text['option-ptring']['en-us'] = "pt-ring";
$text['option-ptring']['en-gb'] = "pt-ring";
$text['option-ptring']['ar-eg'] = "";
$text['option-ptring']['de-at'] = "pt-ring"; //copied from de-de
$text['option-ptring']['de-ch'] = "pt-ring"; //copied from de-de
$text['option-ptring']['de-de'] = "pt-ring";
$text['option-ptring']['es-cl'] = "pt-ring";
$text['option-ptring']['es-mx'] = "pt-ring"; //copied from es-cl
$text['option-ptring']['fr-ca'] = "pt-sonnerie"; //copied from fr-fr
$text['option-ptring']['fr-fr'] = "pt-sonnerie";
$text['option-ptring']['he-il'] = "צלצול פולני";
$text['option-ptring']['it-it'] = "pt-ring";
$text['option-ptring']['nl-nl'] = "pt-ring";
$text['option-ptring']['pl-pl'] = "pt-ring ";
$text['option-ptring']['pt-br'] = "PTRing";
$text['option-ptring']['pt-pt'] = "pt-ring";
$text['option-ptring']['ro-ro'] = "";
$text['option-ptring']['ru-ru'] = "pt-ring";
$text['option-ptring']['sv-se'] = "pt-ring";
$text['option-ptring']['uk-ua'] = "pt-ring";

$text['option-itring']['en-us'] = "it-ring";
$text['option-itring']['en-gb'] = "it-ring";
$text['option-itring']['ar-eg'] = "";
$text['option-itring']['de-at'] = "it-ring"; //copied from de-de
$text['option-itring']['de-ch'] = "it-ring"; //copied from de-de
$text['option-itring']['de-de'] = "it-ring";
$text['option-itring']['es-cl'] = "it-ring";
$text['option-itring']['es-mx'] = "it-ring"; //copied from es-cl
$text['option-itring']['fr-ca'] = "it-sonnerie"; //copied from fr-fr
$text['option-itring']['fr-fr'] = "it-sonnerie";
$text['option-itring']['he-il'] = "צלצול איטלקי";
$text['option-itring']['it-it'] = "it-ring";
$text['option-itring']['nl-nl'] = "it-ring";
$text['option-itring']['pl-pl'] = "it-ring ";
$text['option-itring']['pt-br'] = "ITRing";
$text['option-itring']['pt-pt'] = "it-ring";
$text['option-itring']['ro-ro'] = "";
$text['option-itring']['ru-ru'] = "it-ring";
$text['option-itring']['sv-se'] = "it-ring";
$text['option-itring']['uk-ua'] = "it-ring";

$text['option-frring']['en-us'] = "fr-ring";
$text['option-frring']['en-gb'] = "fr-ring";
$text['option-frring']['ar-eg'] = "";
$text['option-frring']['de-at'] = "fr-ring"; //copied from de-de
$text['option-frring']['de-ch'] = "fr-ring"; //copied from de-de
$text['option-frring']['de-de'] = "fr-ring";
$text['option-frring']['es-cl'] = "fr-ring";
$text['option-frring']['es-mx'] = "fr-ring"; //copied from es-cl
$text['option-frring']['fr-ca'] = "fr-sonnerie"; //copied from fr-fr
$text['option-frring']['fr-fr'] = "fr-sonnerie";
$text['option-frring']['he-il'] = "צלצול צרפתי";
$text['option-frring']['it-it'] = "fr-ring";
$text['option-frring']['nl-nl'] = "fr-ring";
$text['option-frring']['pl-pl'] = "fr-ring ";
$text['option-frring']['pt-br'] = "FRRing";
$text['option-frring']['pt-pt'] = "fr-ring";
$text['option-frring']['ro-ro'] = "";
$text['option-frring']['ru-ru'] = "fr-ring";
$text['option-frring']['sv-se'] = "fr-ring";
$text['option-frring']['uk-ua'] = "fr-ring";

$text['option-dering']['en-us'] = "de-ring";
$text['option-dering']['en-gb'] = "de-ring";
$text['option-dering']['ar-eg'] = "";
$text['option-dering']['de-at'] = "de-ring"; //copied from de-de
$text['option-dering']['de-ch'] = "de-ring"; //copied from de-de
$text['option-dering']['de-de'] = "de-ring";
$text['option-dering']['es-cl'] = "de-ring";
$text['option-dering']['es-mx'] = "de-ring"; //copied from es-cl
$text['option-dering']['fr-ca'] = "de-sonnerie"; //copied from fr-fr
$text['option-dering']['fr-fr'] = "de-sonnerie";
$text['option-dering']['he-il'] = "טבעת גרמנית";
$text['option-dering']['it-it'] = "";
$text['option-dering']['nl-nl'] = "de-ring";
$text['option-dering']['pl-pl'] = "de-ring ";
$text['option-dering']['pt-br'] = "DERing";
$text['option-dering']['pt-pt'] = "de-ring";
$text['option-dering']['ro-ro'] = "";
$text['option-dering']['ru-ru'] = "de-ring";
$text['option-dering']['sv-se'] = "de-ring";
$text['option-dering']['uk-ua'] = "de-ring";

$text['option-enterprise']['en-us'] = "Enterprise";
$text['option-enterprise']['en-gb'] = "Enterprise";
$text['option-enterprise']['ar-eg'] = "";
$text['option-enterprise']['de-at'] = "Unternehmen"; //copied from de-de
$text['option-enterprise']['de-ch'] = "Unternehmen"; //copied from de-de
$text['option-enterprise']['de-de'] = "Unternehmen";
$text['option-enterprise']['es-cl'] = "Compañia";
$text['option-enterprise']['es-mx'] = "Compañia"; //copied from es-cl
$text['option-enterprise']['fr-ca'] = "Entreprise"; //copied from fr-fr
$text['option-enterprise']['fr-fr'] = "Entreprise";
$text['option-enterprise']['he-il'] = "ארגון";
$text['option-enterprise']['it-it'] = "Sequenza (seguimi)";
$text['option-enterprise']['nl-nl'] = "Onderneming";
$text['option-enterprise']['pl-pl'] = "Enterprise ";
$text['option-enterprise']['pt-br'] = "Empresa"; //copied from pt-pt
$text['option-enterprise']['pt-pt'] = "Empresa";
$text['option-enterprise']['ro-ro'] = "";
$text['option-enterprise']['ru-ru'] = "Предприятие";
$text['option-enterprise']['sv-se'] = "Företag";
$text['option-enterprise']['uk-ua'] = "";

$text['option-enabled']['en-us'] = "Enabled";
$text['option-enabled']['en-gb'] = "Enabled";
$text['option-enabled']['ar-eg'] = "";
$text['option-enabled']['de-at'] = "Aktiviert"; //copied from de-de
$text['option-enabled']['de-ch'] = "Aktiviert"; //copied from de-de
$text['option-enabled']['de-de'] = "Aktiviert";
$text['option-enabled']['es-cl'] = "Activado";
$text['option-enabled']['es-mx'] = "Activado"; //copied from es-cl
$text['option-enabled']['fr-ca'] = "Activé"; //copied from fr-fr
$text['option-enabled']['fr-fr'] = "Activé";
$text['option-enabled']['he-il'] = "מופעל";
$text['option-enabled']['it-it'] = "Abilitato";
$text['option-enabled']['nl-nl'] = "Aan";
$text['option-enabled']['pl-pl'] = "Włączony";
$text['option-enabled']['pt-br'] = "Ativado";
$text['option-enabled']['pt-pt'] = "Habilitado";
$text['option-enabled']['ro-ro'] = "";
$text['option-enabled']['ru-ru'] = "Включено";
$text['option-enabled']['sv-se'] = "Aktiverad";
$text['option-enabled']['uk-ua'] = "Включено";

$text['option-disabled']['en-us'] = "Disabled";
$text['option-disabled']['en-gb'] = "Disabled";
$text['option-disabled']['ar-eg'] = "";
$text['option-disabled']['de-at'] = "Deaktiviert"; //copied from de-de
$text['option-disabled']['de-ch'] = "Deaktiviert"; //copied from de-de
$text['option-disabled']['de-de'] = "Deaktiviert";
$text['option-disabled']['es-cl'] = "Desactivado";
$text['option-disabled']['es-mx'] = "Desactivado"; //copied from es-cl
$text['option-disabled']['fr-ca'] = "Désactivé"; //copied from fr-fr
$text['option-disabled']['fr-fr'] = "Désactivé";
$text['option-disabled']['he-il'] = "מנוטרל";
$text['option-disabled']['it-it'] = "Disabilitato";
$text['option-disabled']['nl-nl'] = "Uit";
$text['option-disabled']['pl-pl'] = "Wyłączony";
$text['option-disabled']['pt-br'] = "Inválido";
$text['option-disabled']['pt-pt'] = "Desabilitado";
$text['option-disabled']['ro-ro'] = "";
$text['option-disabled']['ru-ru'] = "Выключено";
$text['option-disabled']['sv-se'] = "Avaktiverad";
$text['option-disabled']['uk-ua'] = "Виключено";

$text['message-timeout_action']['en-us'] = "Please provide: Timeout Action";
$text['message-timeout_action']['en-gb'] = "Please provide: Timeout Action";
$text['message-timeout_action']['ar-eg'] = "";
$text['message-timeout_action']['de-at'] = "Bitte geben Sie folgendes an: Time-Out Aktion"; //copied from de-de
$text['message-timeout_action']['de-ch'] = "Bitte geben Sie folgendes an: Time-Out Aktion"; //copied from de-de
$text['message-timeout_action']['de-de'] = "Bitte geben Sie folgendes an: Time-Out Aktion";
$text['message-timeout_action']['es-cl'] = "Por favor indique: Acción en timeout";
$text['message-timeout_action']['es-mx'] = "Por favor indique: Acción en timeout"; //copied from es-cl
$text['message-timeout_action']['fr-ca'] = "Merci d'indiquer: Action sur non réponse"; //copied from fr-fr
$text['message-timeout_action']['fr-fr'] = "Merci d'indiquer: Action sur non réponse";
$text['message-timeout_action']['he-il'] = "";
$text['message-timeout_action']['it-it'] = "Prego fornire: Azione al timeout";
$text['message-timeout_action']['nl-nl'] = "Geef aub.: Aktie timeout";
$text['message-timeout_action']['pl-pl'] = "Wprowadź następny krok po upływie limitu czasu operacji";
$text['message-timeout_action']['pt-br'] = "Por favor indique: Ação de tempo de saída";
$text['message-timeout_action']['pt-pt'] = "Por favor indique: Acção de Timeout";
$text['message-timeout_action']['ro-ro'] = "";
$text['message-timeout_action']['ru-ru'] = "Пожалуйста, предоставьте: Действие при превышении времени ожидания";
$text['message-timeout_action']['sv-se'] = "Ange: Timeout Åtgärd";
$text['message-timeout_action']['uk-ua'] = "";

$text['message-call_timeout']['en-us'] = "Please provide: Timeout";
$text['message-call_timeout']['en-gb'] = "Please provide: Timeout";
$text['message-call_timeout']['ar-eg'] = "";
$text['message-call_timeout']['de-at'] = "Bitte geben Sie folgendes an: Time-Out"; //copied from de-de
$text['message-call_timeout']['de-ch'] = "Bitte geben Sie folgendes an: Time-Out"; //copied from de-de
$text['message-call_timeout']['de-de'] = "Bitte geben Sie folgendes an: Time-Out";
$text['message-call_timeout']['es-cl'] = "Por favor indique: Timeout";
$text['message-call_timeout']['es-mx'] = "Por favor indique: Timeout"; //copied from es-cl
$text['message-call_timeout']['fr-ca'] = "Merci d'indiquer: Durée de sonnerie"; //copied from fr-fr
$text['message-call_timeout']['fr-fr'] = "Merci d'indiquer: Durée de sonnerie";
$text['message-call_timeout']['he-il'] = "";
$text['message-call_timeout']['it-it'] = "Prego fornire: Timeout";
$text['message-call_timeout']['nl-nl'] = "Geef aub.: Timeout";
$text['message-call_timeout']['pl-pl'] = "Wprowadź limit czasu operacji";
$text['message-call_timeout']['pt-br'] = "Por favor indique: Tempo de saída";
$text['message-call_timeout']['pt-pt'] = "Por favor indique: Timeout";
$text['message-call_timeout']['ro-ro'] = "";
$text['message-call_timeout']['ru-ru'] = "Пожалуйста укажите: время ожидания";
$text['message-call_timeout']['sv-se'] = "Ange: Timeout";
$text['message-call_timeout']['uk-ua'] = "";

$text['message-strategy']['en-us'] = "Please provide: Strategy";
$text['message-strategy']['en-gb'] = "Please provide: Strategy";
$text['message-strategy']['ar-eg'] = "";
$text['message-strategy']['de-at'] = "Bitte geben Sie folgendes an: Strategie"; //copied from de-de
$text['message-strategy']['de-ch'] = "Bitte geben Sie folgendes an: Strategie"; //copied from de-de
$text['message-strategy']['de-de'] = "Bitte geben Sie folgendes an: Strategie";
$text['message-strategy']['es-cl'] = "Por favor indique: Estrategia";
$text['message-strategy']['es-mx'] = "Por favor indique: Estrategia"; //copied from es-cl
$text['message-strategy']['fr-ca'] = "Merci d'indiquer: Stratégie"; //copied from fr-fr
$text['message-strategy']['fr-fr'] = "Merci d'indiquer: Stratégie";
$text['message-strategy']['he-il'] = "";
$text['message-strategy']['it-it'] = "Prego fornire: Strategia";
$text['message-strategy']['nl-nl'] = "Geef aub.: Strategie";
$text['message-strategy']['pl-pl'] = "Wprowadź strategię";
$text['message-strategy']['pt-br'] = "Por favor indique: Estratégia"; //copied from pt-pt
$text['message-strategy']['pt-pt'] = "Por favor indique: Estratégia";
$text['message-strategy']['ro-ro'] = "";
$text['message-strategy']['ru-ru'] = "Пожалуйста укажите: Стратегию";
$text['message-strategy']['sv-se'] = "Ange: Strategi";
$text['message-strategy']['uk-ua'] = "";

$text['message-name']['en-us'] = "Please provide: Name";
$text['message-name']['en-gb'] = "Please provide: Name";
$text['message-name']['ar-eg'] = "";
$text['message-name']['de-at'] = "Bitte geben Sie folgendes an: Name"; //copied from de-de
$text['message-name']['de-ch'] = "Bitte geben Sie folgendes an: Name"; //copied from de-de
$text['message-name']['de-de'] = "Bitte geben Sie folgendes an: Name";
$text['message-name']['es-cl'] = "Por favor indique: Nombre ";
$text['message-name']['es-mx'] = "Por favor indique: Nombre "; //copied from es-cl
$text['message-name']['fr-ca'] = "Merci d'indiquer: Nom"; //copied from fr-fr
$text['message-name']['fr-fr'] = "Merci d'indiquer: Nom";
$text['message-name']['he-il'] = "";
$text['message-name']['it-it'] = "Prego fornire: Nome";
$text['message-name']['nl-nl'] = "Geef aub.: Naam";
$text['message-name']['pl-pl'] = "Wprowadź nazwę";
$text['message-name']['pt-br'] = "Por favor indique: Nome"; //copied from pt-pt
$text['message-name']['pt-pt'] = "Por favor indique: Nome";
$text['message-name']['ro-ro'] = "";
$text['message-name']['ru-ru'] = "Пожалуйста укажите: Имя";
$text['message-name']['sv-se'] = "Ange: Namn";
$text['message-name']['uk-ua'] = "";

$text['message-maximum_ring_groups']['en-us'] = "Maximum Flux Providers:";
$text['message-maximum_ring_groups']['en-gb'] = "Maximum Flux Providers:";
$text['message-maximum_ring_groups']['ar-eg'] = "";
$text['message-maximum_ring_groups']['de-at'] = "Maximale Anzahl an Rufgruppen"; //copied from de-de
$text['message-maximum_ring_groups']['de-ch'] = "Maximale Anzahl an Rufgruppen"; //copied from de-de
$text['message-maximum_ring_groups']['de-de'] = "Maximale Anzahl an Rufgruppen";
$text['message-maximum_ring_groups']['es-cl'] = "Grupos máximos Anillo Animales:";
$text['message-maximum_ring_groups']['es-mx'] = "Grupos máximos Anillo Animales:"; //copied from es-cl
$text['message-maximum_ring_groups']['fr-ca'] = "Groupes de Sonneries Maximum Autorisé:"; //copied from fr-fr
$text['message-maximum_ring_groups']['fr-fr'] = "Groupes de Sonneries Maximum Autorisé:";
$text['message-maximum_ring_groups']['he-il'] = "";
$text['message-maximum_ring_groups']['it-it'] = "Massimo Gruppi di Squillo:";
$text['message-maximum_ring_groups']['nl-nl'] = "Maximaal aanl Belgroepen";
$text['message-maximum_ring_groups']['pl-pl'] = "Maksymalna ilość grup odbiorców.";
$text['message-maximum_ring_groups']['pt-br'] = "Máximo de chamadas por grupo";
$text['message-maximum_ring_groups']['pt-pt'] = "Grupos Máximo Anel de Estimação:";
$text['message-maximum_ring_groups']['ro-ro'] = "";
$text['message-maximum_ring_groups']['ru-ru'] = "Максимальное количество групп вызовов:";
$text['message-maximum_ring_groups']['sv-se'] = "Max Antal Ringgrupper:";
$text['message-maximum_ring_groups']['uk-ua'] = "";

$text['message-enabled']['en-us'] = "Please provide: Enabled";
$text['message-enabled']['en-gb'] = "Please provide: Enabled";
$text['message-enabled']['ar-eg'] = "";
$text['message-enabled']['de-at'] = "Bitte geben Sie folgendes an: Aktiviert"; //copied from de-de
$text['message-enabled']['de-ch'] = "Bitte geben Sie folgendes an: Aktiviert"; //copied from de-de
$text['message-enabled']['de-de'] = "Bitte geben Sie folgendes an: Aktiviert";
$text['message-enabled']['es-cl'] = "Por favor indique: Activado";
$text['message-enabled']['es-mx'] = "Por favor indique: Activado"; //copied from es-cl
$text['message-enabled']['fr-ca'] = "Merci d'indiquer: Actif"; //copied from fr-fr
$text['message-enabled']['fr-fr'] = "Merci d'indiquer: Actif";
$text['message-enabled']['he-il'] = "";
$text['message-enabled']['it-it'] = "Prego fornire: Abilitato";
$text['message-enabled']['nl-nl'] = "Geef aub.: aan/uit";
$text['message-enabled']['pl-pl'] = "Wprowadź: Włączony";
$text['message-enabled']['pt-br'] = "Por favor informe: Ativado";
$text['message-enabled']['pt-pt'] = "Por favor indique: Activado";
$text['message-enabled']['ro-ro'] = "";
$text['message-enabled']['ru-ru'] = "Пожалуйста укажите: Включено";
$text['message-enabled']['sv-se'] = "Ange: Aktiverad";
$text['message-enabled']['uk-ua'] = "";

$text['link-call-forward']['en-us'] = "Call Forward";
$text['link-call-forward']['en-gb'] = "Call Forward";
$text['link-call-forward']['ar-eg'] = "";
$text['link-call-forward']['de-at'] = "Ruf Weiterleitung"; //copied from de-de
$text['link-call-forward']['de-ch'] = "Ruf Weiterleitung"; //copied from de-de
$text['link-call-forward']['de-de'] = "Ruf Weiterleitung";
$text['link-call-forward']['es-cl'] = "Desvío de llamados";
$text['link-call-forward']['es-mx'] = "Desvío de llamados"; //copied from es-cl
$text['link-call-forward']['fr-ca'] = "Renvoi d'Appel"; //copied from fr-fr
$text['link-call-forward']['fr-fr'] = "Renvoi d'Appel";
$text['link-call-forward']['he-il'] = "הפניית שיחה";
$text['link-call-forward']['it-it'] = "Inoltra Chiamata";
$text['link-call-forward']['nl-nl'] = "Gesprek doorsturen";
$text['link-call-forward']['pl-pl'] = "Przekierowanie rozmowy";
$text['link-call-forward']['pt-br'] = "Encaminhar chamada";
$text['link-call-forward']['pt-pt'] = "Encaminhar Chamada";
$text['link-call-forward']['ro-ro'] = "";
$text['link-call-forward']['ru-ru'] = "Переадресация вызова";
$text['link-call-forward']['sv-se'] = "Vidarekoppling";
$text['link-call-forward']['uk-ua'] = "";

$text['label-user_list']['en-us'] = "User List";
$text['label-user_list']['en-gb'] = "User List";
$text['label-user_list']['ar-eg'] = "";
$text['label-user_list']['de-at'] = "Benutzer Liste"; //copied from de-de
$text['label-user_list']['de-ch'] = "Benutzer Liste"; //copied from de-de
$text['label-user_list']['de-de'] = "Benutzer Liste";
$text['label-user_list']['es-cl'] = "Listado de usuarios";
$text['label-user_list']['es-mx'] = "Listado de usuarios"; //copied from es-cl
$text['label-user_list']['fr-ca'] = "Liste d'utilisateurs"; //copied from fr-fr
$text['label-user_list']['fr-fr'] = "Liste d'utilisateurs";
$text['label-user_list']['he-il'] = "רשימת משתמשים";
$text['label-user_list']['it-it'] = "Lista Utenti";
$text['label-user_list']['nl-nl'] = "Gebruikerslijst";
$text['label-user_list']['pl-pl'] = "Lista użytkowników";
$text['label-user_list']['pt-br'] = "Utilizadores"; //copied from pt-pt
$text['label-user_list']['pt-pt'] = "Utilizadores";
$text['label-user_list']['ro-ro'] = "";
$text['label-user_list']['ru-ru'] = "Список пользователей";
$text['label-user_list']['sv-se'] = "Användar-lista";
$text['label-user_list']['uk-ua'] = "Список користувачів";

$text['label-url']['en-us'] = "URL";
$text['label-url']['en-gb'] = "URL";
$text['label-url']['ar-eg'] = "";
$text['label-url']['de-at'] = "URL"; //copied from de-de
$text['label-url']['de-ch'] = "URL"; //copied from de-de
$text['label-url']['de-de'] = "URL";
$text['label-url']['es-cl'] = "URL";
$text['label-url']['es-mx'] = "URL"; //copied from es-cl
$text['label-url']['fr-ca'] = "URL"; //copied from fr-fr
$text['label-url']['fr-fr'] = "URL";
$text['label-url']['he-il'] = "";
$text['label-url']['it-it'] = "URL";
$text['label-url']['nl-nl'] = "URL";
$text['label-url']['pl-pl'] = "URL";
$text['label-url']['pt-br'] = "URL"; //copied from pt-pt
$text['label-url']['pt-pt'] = "URL";
$text['label-url']['ro-ro'] = "";
$text['label-url']['ru-ru'] = "URL-адрес";
$text['label-url']['sv-se'] = "URL";
$text['label-url']['uk-ua'] = "URL";

$text['label-timeout_destination']['en-us'] = "Timeout Destination";
$text['label-timeout_destination']['en-gb'] = "Timeout Destination";
$text['label-timeout_destination']['ar-eg'] = "";
$text['label-timeout_destination']['de-at'] = "Time-Out Ziel"; //copied from de-de
$text['label-timeout_destination']['de-ch'] = "Time-Out Ziel"; //copied from de-de
$text['label-timeout_destination']['de-de'] = "Time-Out Ziel";
$text['label-timeout_destination']['es-cl'] = "Timeout de destino";
$text['label-timeout_destination']['es-mx'] = "Timeout de destino"; //copied from es-cl
$text['label-timeout_destination']['fr-ca'] = "Destination si non réponse"; //copied from fr-fr
$text['label-timeout_destination']['fr-fr'] = "Destination si non réponse";
$text['label-timeout_destination']['he-il'] = "";
$text['label-timeout_destination']['it-it'] = "Destinazione al Timeout";
$text['label-timeout_destination']['nl-nl'] = "Bestemmingsafbreektijd";
$text['label-timeout_destination']['pl-pl'] = "Alternatywna destynacja rozmowy po upłynięciu limitu czasowego.";
$text['label-timeout_destination']['pt-br'] = "Destino tempo de saída";
$text['label-timeout_destination']['pt-pt'] = "Destino Timeout";
$text['label-timeout_destination']['ro-ro'] = "";
$text['label-timeout_destination']['ru-ru'] = "Переадресация по Тайм-ауту";
$text['label-timeout_destination']['sv-se'] = "Timeout Destination";
$text['label-timeout_destination']['uk-ua'] = "";

$text['label-call_timeout']['en-us'] = "Call Timeout";
$text['label-call_timeout']['en-gb'] = "Call Timeout";
$text['label-call_timeout']['ar-eg'] = "";
$text['label-call_timeout']['de-at'] = "Zeitüberschreitung des Anrufs"; //copied from de-de
$text['label-call_timeout']['de-ch'] = "Zeitüberschreitung des Anrufs"; //copied from de-de
$text['label-call_timeout']['de-de'] = "Zeitüberschreitung des Anrufs";
$text['label-call_timeout']['es-cl'] = "Tiempo de Espera de Llamada";
$text['label-call_timeout']['es-mx'] = "Tiempo de Espera de Llamada"; //copied from es-cl
$text['label-call_timeout']['fr-ca'] = "Durée max d'appel"; //copied from fr-fr
$text['label-call_timeout']['fr-fr'] = "Durée max d'appel";
$text['label-call_timeout']['he-il'] = "";
$text['label-call_timeout']['it-it'] = "Timeout Chiamata";
$text['label-call_timeout']['nl-nl'] = "Oproep Afbreektijd";
$text['label-call_timeout']['pl-pl'] = "Limit czasu rozmowy";
$text['label-call_timeout']['pt-br'] = "Timeout da chamada";
$text['label-call_timeout']['pt-pt'] = "Timeout da Chamada";
$text['label-call_timeout']['ro-ro'] = "";
$text['label-call_timeout']['ru-ru'] = "Тайм-аут вызова";
$text['label-call_timeout']['sv-se'] = "Call Timeout";
$text['label-call_timeout']['uk-ua'] = "";

$text['label-provider_api_url']['en-us'] = "API URL";
$text['label-provider_api_url']['ar-eg'] = "";
$text['label-provider_api_url']['de-at'] = "";
$text['label-provider_api_url']['de-ch'] = "";
$text['label-provider_api_url']['de-de'] = "";
$text['label-provider_api_url']['es-cl'] = "";
$text['label-provider_api_url']['es-mx'] = "";
$text['label-provider_api_url']['fr-ca'] = "";
$text['label-provider_api_url']['fr-fr'] = "";
$text['label-provider_api_url']['he-il'] = "";
$text['label-provider_api_url']['it-it'] = "";
$text['label-provider_api_url']['nl-nl'] = "";
$text['label-provider_api_url']['pl-pl'] = "";
$text['label-provider_api_url']['pt-br'] = "API URL";
$text['label-provider_api_url']['pt-pt'] = "";
$text['label-provider_api_url']['ro-ro'] = "";
$text['label-provider_api_url']['ru-ru'] = "";
$text['label-provider_api_url']['sv-se'] = "";
$text['label-provider_api_url']['uk-ua'] = "";


$text['select-global']['en-us'] = "Global";
$text['select-global']['ar-eg'] = "";
$text['select-global']['de-at'] = "";
$text['select-global']['de-ch'] = "";
$text['select-global']['de-de'] = "";
$text['select-global']['es-cl'] = "";
$text['select-global']['es-mx'] = "";
$text['select-global']['fr-ca'] = "";
$text['select-global']['fr-fr'] = "";
$text['select-global']['he-il'] = "";
$text['select-global']['it-it'] = "";
$text['select-global']['nl-nl'] = "";
$text['select-global']['pl-pl'] = "";
$text['select-global']['pt-br'] = "Global";
$text['select-global']['pt-pt'] = "";
$text['select-global']['ro-ro'] = "";
$text['select-global']['ru-ru'] = "";
$text['select-global']['sv-se'] = "";
$text['select-global']['uk-ua'] = "";


$text['label-provider_auth_type']['en-us'] = "Auth Type";
$text['label-provider_auth_type']['ar-eg'] = "";
$text['label-provider_auth_type']['de-at'] = "";
$text['label-provider_auth_type']['de-ch'] = "";
$text['label-provider_auth_type']['de-de'] = "";
$text['label-provider_auth_type']['es-cl'] = "";
$text['label-provider_auth_type']['es-mx'] = "";
$text['label-provider_auth_type']['fr-ca'] = "";
$text['label-provider_auth_type']['fr-fr'] = "";
$text['label-provider_auth_type']['he-il'] = "";
$text['label-provider_auth_type']['it-it'] = "";
$text['label-provider_auth_type']['nl-nl'] = "";
$text['label-provider_auth_type']['pl-pl'] = "";
$text['label-provider_auth_type']['pt-br'] = "Auth Type";
$text['label-provider_auth_type']['pt-pt'] = "";
$text['label-provider_auth_type']['ro-ro'] = "";
$text['label-provider_auth_type']['ru-ru'] = "";
$text['label-provider_auth_type']['sv-se'] = "";
$text['label-provider_auth_type']['uk-ua'] = "";


$text['label-provider_auth_method']['en-us'] = "Auth Method";
$text['label-provider_auth_method']['ar-eg'] = "";
$text['label-provider_auth_method']['de-at'] = "";
$text['label-provider_auth_method']['de-ch'] = "";
$text['label-provider_auth_method']['de-de'] = "";
$text['label-provider_auth_method']['es-cl'] = "";
$text['label-provider_auth_method']['es-mx'] = "";
$text['label-provider_auth_method']['fr-ca'] = "";
$text['label-provider_auth_method']['fr-fr'] = "";
$text['label-provider_auth_method']['he-il'] = "";
$text['label-provider_auth_method']['it-it'] = "";
$text['label-provider_auth_method']['nl-nl'] = "";
$text['label-provider_auth_method']['pl-pl'] = "";
$text['label-provider_auth_method']['pt-br'] = "Auth Method";
$text['label-provider_auth_method']['pt-pt'] = "";
$text['label-provider_auth_method']['ro-ro'] = "";
$text['label-provider_auth_method']['ru-ru'] = "";
$text['label-provider_auth_method']['sv-se'] = "";
$text['label-provider_auth_method']['uk-ua'] = "";

$text['label-provider_token']['en-us'] = "Token";
$text['label-provider_token']['ar-eg'] = "";
$text['label-provider_token']['de-at'] = "";
$text['label-provider_token']['de-ch'] = "";
$text['label-provider_token']['de-de'] = "";
$text['label-provider_token']['es-cl'] = "";
$text['label-provider_token']['es-mx'] = "";
$text['label-provider_token']['fr-ca'] = "Nom";
$text['label-provider_token']['fr-fr'] = "Nom";
$text['label-provider_token']['he-il'] = "";
$text['label-provider_token']['it-it'] = "";
$text['label-provider_token']['nl-nl'] = "Naam";
$text['label-provider_token']['pl-pl'] = "";
$text['label-provider_token']['pt-br'] = "Token";
$text['label-provider_token']['pt-pt'] = "";
$text['label-provider_token']['ro-ro'] = "";
$text['label-provider_token']['ru-ru'] = "";
$text['label-provider_token']['sv-se'] = "";
$text['label-provider_token']['uk-ua'] = "";


$text['label-user_token']['en-us'] = "User Token";
$text['label-user_token']['ar-eg'] = "";
$text['label-user_token']['de-at'] = "";
$text['label-user_token']['de-ch'] = "";
$text['label-user_token']['de-de'] = "";
$text['label-user_token']['es-cl'] = "";
$text['label-user_token']['es-mx'] = "";
$text['label-user_token']['fr-ca'] = "Nom";
$text['label-user_token']['fr-fr'] = "Nom";
$text['label-user_token']['he-il'] = "";
$text['label-user_token']['it-it'] = "";
$text['label-user_token']['nl-nl'] = "Naam";
$text['label-user_token']['pl-pl'] = "";
$text['label-user_token']['pt-br'] = "Token de Usuário";
$text['label-user_token']['pt-pt'] = "";
$text['label-user_token']['ro-ro'] = "";
$text['label-user_token']['ru-ru'] = "";
$text['label-user_token']['sv-se'] = "";
$text['label-user_token']['uk-ua'] = "";



$text['label-provider_both']['en-us'] = "Both";
$text['label-provider_both']['ar-eg'] = "";
$text['label-provider_both']['de-at'] = "";
$text['label-provider_both']['de-ch'] = "";
$text['label-provider_both']['de-de'] = "";
$text['label-provider_both']['es-cl'] = "";
$text['label-provider_both']['es-mx'] = "";
$text['label-provider_both']['fr-ca'] = "Nom";
$text['label-provider_both']['fr-fr'] = "Nom";
$text['label-provider_both']['he-il'] = "";
$text['label-provider_both']['it-it'] = "";
$text['label-provider_both']['nl-nl'] = "Naam";
$text['label-provider_both']['pl-pl'] = "";
$text['label-provider_both']['pt-br'] = "Ambos";
$text['label-provider_both']['pt-pt'] = "";
$text['label-provider_both']['ro-ro'] = "";
$text['label-provider_both']['ru-ru'] = "";
$text['label-provider_both']['sv-se'] = "";
$text['label-provider_both']['uk-ua'] = "";

$text['label-provider_name']['en-us'] = "Provider Name";
$text['label-provider_name']['ar-eg'] = "";
$text['label-provider_name']['de-at'] = "";
$text['label-provider_name']['de-ch'] = "";
$text['label-provider_name']['de-de'] = "";
$text['label-provider_name']['es-cl'] = "";
$text['label-provider_name']['es-mx'] = "";
$text['label-provider_name']['fr-ca'] = "Nom";
$text['label-provider_name']['fr-fr'] = "Nom";
$text['label-provider_name']['he-il'] = "";
$text['label-provider_name']['it-it'] = "";
$text['label-provider_name']['nl-nl'] = "Naam";
$text['label-provider_name']['pl-pl'] = "";
$text['label-provider_name']['pt-br'] = "Nome do Provedor";
$text['label-provider_name']['pt-pt'] = "";
$text['label-provider_name']['ro-ro'] = "";
$text['label-provider_name']['ru-ru'] = "";
$text['label-provider_name']['sv-se'] = "";
$text['label-provider_name']['uk-ua'] = "";

$text['description-provider_name']['en-us'] = "Enter the Provider Name.";
$text['description-provider_name']['ar-eg'] = "";
$text['description-provider_name']['de-at'] = "";
$text['description-provider_name']['de-ch'] = "";
$text['description-provider_name']['de-de'] = "";
$text['description-provider_name']['es-cl'] = "";
$text['description-provider_name']['es-mx'] = "";
$text['description-provider_name']['fr-ca'] = "Entrez le nom";
$text['description-provider_name']['fr-fr'] = "Entrez le nom";
$text['description-provider_name']['he-il'] = "";
$text['description-provider_name']['it-it'] = "";
$text['description-provider_name']['nl-nl'] = "Voer naam in.";
$text['description-provider_name']['pl-pl'] = "";
$text['description-provider_name']['pt-br'] = "Digite o nome do provedor CRM.";
$text['description-provider_name']['pt-pt'] = "";
$text['description-provider_name']['ro-ro'] = "";
$text['description-provider_name']['ru-ru'] = "";
$text['description-provider_name']['sv-se'] = "";
$text['description-provider_name']['uk-ua'] = "";


$text['label-timeout']['en-us'] = "Timeout";
$text['label-timeout']['en-gb'] = "Timeout";
$text['label-timeout']['ar-eg'] = "";
$text['label-timeout']['de-at'] = "Time-Out"; //copied from de-de
$text['label-timeout']['de-ch'] = "Time-Out"; //copied from de-de
$text['label-timeout']['de-de'] = "Time-Out";
$text['label-timeout']['es-cl'] = "Timeout";
$text['label-timeout']['es-mx'] = "Timeout"; //copied from es-cl
$text['label-timeout']['fr-ca'] = "Durée de sonnerie"; //copied from fr-fr
$text['label-timeout']['fr-fr'] = "Durée de sonnerie";
$text['label-timeout']['he-il'] = "";
$text['label-timeout']['it-it'] = "Timeout";
$text['label-timeout']['nl-nl'] = "Afbreektijd";
$text['label-timeout']['pl-pl'] = "Przekroczenie czasu oczekiwania (timeout)";
$text['label-timeout']['pt-br'] = "Tempo limite";
$text['label-timeout']['pt-pt'] = "Timeout";
$text['label-timeout']['ro-ro'] = "";
$text['label-timeout']['ru-ru'] = "Тайм-аут";
$text['label-timeout']['sv-se'] = "Tidsgräns";
$text['label-timeout']['uk-ua'] = "Таймаут";

$text['label-text']['en-us'] = "Text";
$text['label-text']['en-gb'] = "Text";
$text['label-text']['ar-eg'] = "";
$text['label-text']['de-at'] = "Text"; //copied from de-de
$text['label-text']['de-ch'] = "Text"; //copied from de-de
$text['label-text']['de-de'] = "Text";
$text['label-text']['es-cl'] = "Texto";
$text['label-text']['es-mx'] = "Texto"; //copied from es-cl
$text['label-text']['fr-ca'] = "texte"; //copied from fr-fr
$text['label-text']['fr-fr'] = "texte";
$text['label-text']['he-il'] = "טקסט";
$text['label-text']['it-it'] = "Testo";
$text['label-text']['nl-nl'] = "Tekst";
$text['label-text']['pl-pl'] = "Tekst";
$text['label-text']['pt-br'] = "Texto"; //copied from pt-pt
$text['label-text']['pt-pt'] = "Texto";
$text['label-text']['ro-ro'] = "";
$text['label-text']['ru-ru'] = "Текст";
$text['label-text']['sv-se'] = "Text";
$text['label-text']['uk-ua'] = "текст";

$text['label-provider_auth_url']['en-us'] = "Auth URL";
$text['label-provider_auth_url']['ar-eg'] = "";
$text['label-provider_auth_url']['de-at'] = "";
$text['label-provider_auth_url']['de-ch'] = "";
$text['label-provider_auth_url']['de-de'] = "";
$text['label-provider_auth_url']['es-cl'] = "";
$text['label-provider_auth_url']['es-mx'] = "";
$text['label-provider_auth_url']['fr-ca'] = "";
$text['label-provider_auth_url']['fr-fr'] = "";
$text['label-provider_auth_url']['he-il'] = "";
$text['label-provider_auth_url']['it-it'] = "";
$text['label-provider_auth_url']['nl-nl'] = "";
$text['label-provider_auth_url']['pl-pl'] = "";
$text['label-provider_auth_url']['pt-br'] = "URL de Autenticação";
$text['label-provider_auth_url']['pt-pt'] = "";
$text['label-provider_auth_url']['ro-ro'] = "";
$text['label-provider_auth_url']['ru-ru'] = "";
$text['label-provider_auth_url']['sv-se'] = "";
$text['label-provider_auth_url']['uk-ua'] = "";


$text['label-provider_password']['en-us'] = "Auth Password";
$text['label-provider_password']['ar-eg'] = "";
$text['label-provider_password']['de-at'] = "";
$text['label-provider_password']['de-ch'] = "";
$text['label-provider_password']['de-de'] = "";
$text['label-provider_password']['es-cl'] = "";
$text['label-provider_password']['es-mx'] = "";
$text['label-provider_password']['fr-ca'] = "";
$text['label-provider_password']['fr-fr'] = "";
$text['label-provider_password']['he-il'] = "";
$text['label-provider_password']['it-it'] = "";
$text['label-provider_password']['nl-nl'] = "";
$text['label-provider_password']['pl-pl'] = "";
$text['label-provider_password']['pt-br'] = "Senha de Autenticação";
$text['label-provider_password']['pt-pt'] = "";
$text['label-provider_password']['ro-ro'] = "";
$text['label-provider_password']['ru-ru'] = "";
$text['label-provider_password']['sv-se'] = "";
$text['label-provider_password']['uk-ua'] = "";


$text['description-provider_api_url']['en-us'] = "Enter the Provider API URL.";
$text['description-provider_api_url']['ar-eg'] = "";
$text['description-provider_api_url']['de-at'] = "";
$text['description-provider_api_url']['de-ch'] = "";
$text['description-provider_api_url']['de-de'] = "";
$text['description-provider_api_url']['es-cl'] = "";
$text['description-provider_api_url']['es-mx'] = "";
$text['description-provider_api_url']['fr-ca'] = "";
$text['description-provider_api_url']['fr-fr'] = "";
$text['description-provider_api_url']['he-il'] = "";
$text['description-provider_api_url']['it-it'] = "";
$text['description-provider_api_url']['nl-nl'] = "";
$text['description-provider_api_url']['pl-pl'] = "";
$text['description-provider_api_url']['pt-br'] = "Insira a URL de API do CRM";
$text['description-provider_api_url']['pt-pt'] = "";
$text['description-provider_api_url']['ro-ro'] = "";
$text['description-provider_api_url']['ru-ru'] = "";
$text['description-provider_api_url']['sv-se'] = "";
$text['description-provider_api_url']['uk-ua'] = "";


$text['description-provider_auth_url']['en-us'] = "Enter the Provider Authentication URL.";
$text['description-provider_auth_url']['ar-eg'] = "";
$text['description-provider_auth_url']['de-at'] = "";
$text['description-provider_auth_url']['de-ch'] = "";
$text['description-provider_auth_url']['de-de'] = "";
$text['description-provider_auth_url']['es-cl'] = "";
$text['description-provider_auth_url']['es-mx'] = "";
$text['description-provider_auth_url']['fr-ca'] = "";
$text['description-provider_auth_url']['fr-fr'] = "";
$text['description-provider_auth_url']['he-il'] = "";
$text['description-provider_auth_url']['it-it'] = "";
$text['description-provider_auth_url']['nl-nl'] = "";
$text['description-provider_auth_url']['pl-pl'] = "";
$text['description-provider_auth_url']['pt-br'] = "Insira a URL de Autenticação da API.";
$text['description-provider_auth_url']['pt-pt'] = "";
$text['description-provider_auth_url']['ro-ro'] = "";
$text['description-provider_auth_url']['ru-ru'] = "";
$text['description-provider_auth_url']['sv-se'] = "";
$text['description-provider_auth_url']['uk-ua'] = "";

$text['description-provider_user_token']['en-us'] = "Enter the Provider Authentication Token.";
$text['description-provider_user_token']['ar-eg'] = "";
$text['description-provider_user_token']['de-at'] = "";
$text['description-provider_user_token']['de-ch'] = "";
$text['description-provider_user_token']['de-de'] = "";
$text['description-provider_user_token']['es-cl'] = "";
$text['description-provider_user_token']['es-mx'] = "";
$text['description-provider_user_token']['fr-ca'] = "";
$text['description-provider_user_token']['fr-fr'] = "";
$text['description-provider_user_token']['he-il'] = "";
$text['description-provider_user_token']['it-it'] = "";
$text['description-provider_user_token']['nl-nl'] = "";
$text['description-provider_user_token']['pl-pl'] = "";
$text['description-provider_user_token']['pt-br'] = "Insira o Token de Autenticação da API.";
$text['description-provider_user_token']['pt-pt'] = "";
$text['description-provider_user_token']['ro-ro'] = "";
$text['description-provider_user_token']['ru-ru'] = "";
$text['description-provider_user_token']['sv-se'] = "";
$text['description-provider_user_token']['uk-ua'] = "";

$text['description-providers']['en-us'] = "Enter the Provider.";
$text['description-providers']['ar-eg'] = "";
$text['description-providers']['de-at'] = "";
$text['description-providers']['de-ch'] = "";
$text['description-providers']['de-de'] = "";
$text['description-providers']['es-cl'] = "";
$text['description-providers']['es-mx'] = "";
$text['description-providers']['fr-ca'] = "";
$text['description-providers']['fr-fr'] = "";
$text['description-providers']['he-il'] = "";
$text['description-providers']['it-it'] = "";
$text['description-providers']['nl-nl'] = "";
$text['description-providers']['pl-pl'] = "";
$text['description-providers']['pt-br'] = "Insira o Provedor.";
$text['description-providers']['pt-pt'] = "";
$text['description-providers']['ro-ro'] = "";
$text['description-providers']['ru-ru'] = "";
$text['description-providers']['sv-se'] = "";
$text['description-providers']['uk-ua'] = "";

$text['description-provider_user_password']['en-us'] = "Enter the Provider Authentication Password.";
$text['description-provider_user_password']['ar-eg'] = "";
$text['description-provider_user_password']['de-at'] = "";
$text['description-provider_user_password']['de-ch'] = "";
$text['description-provider_user_password']['de-de'] = "";
$text['description-provider_user_password']['es-cl'] = "";
$text['description-provider_user_password']['es-mx'] = "";
$text['description-provider_user_password']['fr-ca'] = "";
$text['description-provider_user_password']['fr-fr'] = "";
$text['description-provider_user_password']['he-il'] = "";
$text['description-provider_user_password']['it-it'] = "";
$text['description-provider_user_password']['nl-nl'] = "";
$text['description-provider_user_password']['pl-pl'] = "";
$text['description-provider_user_password']['pt-br'] = "Insira a Senha de Autenticação da API.";
$text['description-provider_user_password']['pt-pt'] = "";
$text['description-provider_user_password']['ro-ro'] = "";
$text['description-provider_user_password']['ru-ru'] = "";
$text['description-provider_user_password']['sv-se'] = "";
$text['description-provider_user_password']['uk-ua'] = "";

$text['description-provider_method']['en-us'] = "Enter the authentication method.";
$text['description-provider_method']['ar-eg'] = "";
$text['description-provider_method']['de-at'] = "";
$text['description-provider_method']['de-ch'] = "";
$text['description-provider_method']['de-de'] = "";
$text['description-provider_method']['es-cl'] = "";
$text['description-provider_method']['es-mx'] = "";
$text['description-provider_method']['fr-ca'] = "";
$text['description-provider_method']['fr-fr'] = "";
$text['description-provider_method']['he-il'] = "";
$text['description-provider_method']['it-it'] = "";
$text['description-provider_method']['nl-nl'] = "";
$text['description-provider_method']['pl-pl'] = "";
$text['description-provider_method']['pt-br'] = "Escolha o método de Autenticação";
$text['description-provider_method']['pt-pt'] = "";
$text['description-provider_method']['ro-ro'] = "";
$text['description-provider_method']['ru-ru'] = "";
$text['description-provider_method']['sv-se'] = "";
$text['description-provider_method']['uk-ua'] = "";

$text['description-provider_auth_type']['en-us'] = "Enter the authentication request type.";
$text['description-provider_auth_type']['ar-eg'] = "";
$text['description-provider_auth_type']['de-at'] = "";
$text['description-provider_auth_type']['de-ch'] = "";
$text['description-provider_auth_type']['de-de'] = "";
$text['description-provider_auth_type']['es-cl'] = "";
$text['description-provider_auth_type']['es-mx'] = "";
$text['description-provider_auth_type']['fr-ca'] = "";
$text['description-provider_auth_type']['fr-fr'] = "";
$text['description-provider_auth_type']['he-il'] = "";
$text['description-provider_auth_type']['it-it'] = "";
$text['description-provider_auth_type']['nl-nl'] = "";
$text['description-provider_auth_type']['pl-pl'] = "";
$text['description-provider_auth_type']['pt-br'] = "Escolha o tipo de requisição.";
$text['description-provider_auth_type']['pt-pt'] = "";
$text['description-provider_auth_type']['ro-ro'] = "";
$text['description-provider_auth_type']['ru-ru'] = "";
$text['description-provider_auth_type']['sv-se'] = "";
$text['description-provider_auth_type']['uk-ua'] = "";

$text['label-flux-provider-extension']['en-us'] = "Flux Provider Extension";
$text['label-flux-provider-extension']['en-gb'] = "Flux Provider Extension";
$text['label-flux-provider-extension']['ar-eg'] = "";
$text['label-flux-provider-extension']['de-at'] = "Nebenstelle der Rufgruppe"; //copied from de-de
$text['label-flux-provider-extension']['de-ch'] = "Nebenstelle der Rufgruppe"; //copied from de-de
$text['label-flux-provider-extension']['de-de'] = "Nebenstelle der Rufgruppe";
$text['label-flux-provider-extension']['es-cl'] = "Extensión de grupo de llamado";
$text['label-flux-provider-extension']['es-mx'] = "Extensión de grupo de llamado"; //copied from es-cl
$text['label-flux-provider-extension']['fr-ca'] = "Extension du groupe de sonnerie"; //copied from fr-fr
$text['label-flux-provider-extension']['fr-fr'] = "Extension du groupe de sonnerie";
$text['label-flux-provider-extension']['he-il'] = "";
$text['label-flux-provider-extension']['it-it'] = "Interno Gruppo di Squillo";
$text['label-flux-provider-extension']['nl-nl'] = "Belgroep toestel";
$text['label-flux-provider-extension']['pl-pl'] = "Numer wewnętrzny grupy odbiorców.";
$text['label-flux-provider-extension']['pt-br'] = "Extensão associada ao grupo"; //copied from pt-pt
$text['label-flux-provider-extension']['pt-pt'] = "Extensão associada ao grupo";
$text['label-flux-provider-extension']['ro-ro'] = "";
$text['label-flux-provider-extension']['ru-ru'] = "Группы вызовов внутренних номеров";
$text['label-flux-provider-extension']['sv-se'] = "Ringgrupp Anknytning";
$text['label-flux-provider-extension']['uk-ua'] = "";

$text['label-flux-provider']['en-us'] = "Flux Provider";
$text['label-flux-provider']['en-gb'] = "Flux Provider";
$text['label-flux-provider']['ar-eg'] = "";
$text['label-flux-provider']['de-at'] = "Rufgruppe"; //copied from de-de
$text['label-flux-provider']['de-ch'] = "Rufgruppe"; //copied from de-de
$text['label-flux-provider']['de-de'] = "Rufgruppe";
$text['label-flux-provider']['es-cl'] = "Grupo de llamado";
$text['label-flux-provider']['es-mx'] = "Grupo de llamado"; //copied from es-cl
$text['label-flux-provider']['fr-ca'] = "Groupe de sonnerie"; //copied from fr-fr
$text['label-flux-provider']['fr-fr'] = "Groupe de sonnerie";
$text['label-flux-provider']['he-il'] = "קבוצת חיוג";
$text['label-flux-provider']['it-it'] = "Gruppo di Squillo";
$text['label-flux-provider']['nl-nl'] = "Belgroep";
$text['label-flux-provider']['pl-pl'] = "Grupa odbiorców.";
$text['label-flux-provider']['pt-br'] = "Provedor"; //copied from pt-pt
$text['label-flux-provider']['pt-pt'] = "Grupo";
$text['label-flux-provider']['ro-ro'] = "";
$text['label-flux-provider']['ru-ru'] = "Группа вызовов";
$text['label-flux-provider']['sv-se'] = "Ringgrupp";
$text['label-flux-provider']['uk-ua'] = "";


$text['label-missed_call']['en-us'] = "Missed Call";
$text['label-missed_call']['en-gb'] = "Missed Call";
$text['label-missed_call']['ar-eg'] = "";
$text['label-missed_call']['de-at'] = "Verpasster Anruf"; //copied from de-de
$text['label-missed_call']['de-ch'] = "Verpasster Anruf"; //copied from de-de
$text['label-missed_call']['de-de'] = "Verpasster Anruf";
$text['label-missed_call']['es-cl'] = "Llamada Perdida";
$text['label-missed_call']['es-mx'] = "Llamada Perdida"; //copied from es-cl
$text['label-missed_call']['fr-ca'] = "Appel Manqué"; //copied from fr-fr
$text['label-missed_call']['fr-fr'] = "Appel Manqué";
$text['label-missed_call']['he-il'] = "שיחה שלא נענתה";
$text['label-missed_call']['it-it'] = "Chiamata Persa";
$text['label-missed_call']['nl-nl'] = "Gemist gesprek";
$text['label-missed_call']['pl-pl'] = "Nieodebrane Połączenie";
$text['label-missed_call']['pt-br'] = "Chamada Perdida"; //copied from pt-pt
$text['label-missed_call']['pt-pt'] = "Chamada Perdida";
$text['label-missed_call']['ro-ro'] = "";
$text['label-missed_call']['ru-ru'] = "Пропущенный вызов";
$text['label-missed_call']['sv-se'] = "Missat Samtal";
$text['label-missed_call']['uk-ua'] = "пропущений Дзвінок";


$text['label-extension']['en-us'] = "Extension";
$text['label-extension']['en-gb'] = "Extension";
$text['label-extension']['ar-eg'] = "";
$text['label-extension']['de-at'] = "Nebenstelle"; //copied from de-de
$text['label-extension']['de-ch'] = "Nebenstelle"; //copied from de-de
$text['label-extension']['de-de'] = "Nebenstelle";
$text['label-extension']['es-cl'] = "Extensión";
$text['label-extension']['es-mx'] = "Extensión"; //copied from es-cl
$text['label-extension']['fr-ca'] = "Extension"; //copied from fr-fr
$text['label-extension']['fr-fr'] = "Extension";
$text['label-extension']['he-il'] = "שלוחה";
$text['label-extension']['it-it'] = "Interno";
$text['label-extension']['nl-nl'] = "Toestel";
$text['label-extension']['pl-pl'] = "Numer wewnętrzny";
$text['label-extension']['pt-br'] = "Ramal";
$text['label-extension']['pt-pt'] = "Extensão";
$text['label-extension']['ro-ro'] = "";
$text['label-extension']['ru-ru'] = "Внутренний номер";
$text['label-extension']['sv-se'] = "Anknytning";
$text['label-extension']['uk-ua'] = "Розширення (Extention)";

$text['label-email']['en-us'] = "Email";
$text['label-email']['en-gb'] = "Email";
$text['label-email']['ar-eg'] = "";
$text['label-email']['de-at'] = "Email"; //copied from de-de
$text['label-email']['de-ch'] = "Email"; //copied from de-de
$text['label-email']['de-de'] = "Email";
$text['label-email']['es-cl'] = "Email";
$text['label-email']['es-mx'] = "Email"; //copied from es-cl
$text['label-email']['fr-ca'] = "Courriel"; //copied from fr-fr
$text['label-email']['fr-fr'] = "Courriel";
$text['label-email']['he-il'] = "אימייל";
$text['label-email']['it-it'] = "Email";
$text['label-email']['nl-nl'] = "E-mail";
$text['label-email']['pl-pl'] = "Email";
$text['label-email']['pt-br'] = "Email"; //copied from pt-pt
$text['label-email']['pt-pt'] = "Email";
$text['label-email']['ro-ro'] = "";
$text['label-email']['ru-ru'] = "Адрес электронной почты";
$text['label-email']['sv-se'] = "E-post";
$text['label-email']['uk-ua'] = "Електронна пошта";


$text['label-username']['en-us'] = "Username";
$text['label-username']['en-gb'] = "Username";
$text['label-username']['ar-eg'] = "";
$text['label-username']['de-at'] = "Username"; //copied from de-de
$text['label-username']['de-ch'] = "Username"; //copied from de-de
$text['label-username']['de-de'] = "Username";
$text['label-username']['es-cl'] = "Username";
$text['label-username']['es-mx'] = "Username"; //copied from es-cl
$text['label-username']['fr-ca'] = "Courriel"; //copied from fr-fr
$text['label-username']['fr-fr'] = "Courriel";
$text['label-username']['he-il'] = "אימייל";
$text['label-username']['it-it'] = "Username";
$text['label-username']['nl-nl'] = "E-mail";
$text['label-username']['pl-pl'] = "Username";
$text['label-username']['pt-br'] = "Usuário"; //copied from pt-pt
$text['label-username']['pt-pt'] = "Username";
$text['label-username']['ro-ro'] = "";
$text['label-username']['ru-ru'] = "Адрес электронной почты";
$text['label-username']['sv-se'] = "E-post";
$text['label-username']['uk-ua'] = "Електронна пошта";

$text['label-destination_enabled']['en-us'] = "Enabled";
$text['label-destination_enabled']['en-gb'] = "Enabled";
$text['label-destination_enabled']['ar-eg'] = "";
$text['label-destination_enabled']['de-at'] = "Aktiviert"; //copied from de-de
$text['label-destination_enabled']['de-ch'] = "Aktiviert"; //copied from de-de
$text['label-destination_enabled']['de-de'] = "Aktiviert";
$text['label-destination_enabled']['es-cl'] = "Activado";
$text['label-destination_enabled']['es-mx'] = "Activado"; //copied from es-cl
$text['label-destination_enabled']['fr-ca'] = "Activé"; //copied from fr-fr
$text['label-destination_enabled']['fr-fr'] = "Activé";
$text['label-destination_enabled']['he-il'] = "מופעל";
$text['label-destination_enabled']['it-it'] = "Abilitato";
$text['label-destination_enabled']['nl-nl'] = "Aan";
$text['label-destination_enabled']['pl-pl'] = "Włączony";
$text['label-destination_enabled']['pt-br'] = "Ativado";
$text['label-destination_enabled']['pt-pt'] = "Habilitado";
$text['label-destination_enabled']['ro-ro'] = "";
$text['label-destination_enabled']['ru-ru'] = "Включено";
$text['label-destination_enabled']['sv-se'] = "Aktiverad";
$text['label-destination_enabled']['uk-ua'] = "Включено";

$text['label-context']['en-us'] = "Context";
$text['label-context']['en-gb'] = "Context";
$text['label-context']['ar-eg'] = "";
$text['label-context']['de-at'] = "Kontext"; //copied from de-de
$text['label-context']['de-ch'] = "Kontext"; //copied from de-de
$text['label-context']['de-de'] = "Kontext";
$text['label-context']['es-cl'] = "Contexto";
$text['label-context']['es-mx'] = "Contexto"; //copied from es-cl
$text['label-context']['fr-ca'] = "Contexte"; //copied from fr-fr
$text['label-context']['fr-fr'] = "Contexte";
$text['label-context']['he-il'] = "";
$text['label-context']['it-it'] = "Contesto";
$text['label-context']['nl-nl'] = "Context";
$text['label-context']['pl-pl'] = "Kontekst";
$text['label-context']['pt-br'] = "Contexto"; //copied from pt-pt
$text['label-context']['pt-pt'] = "Contexto";
$text['label-context']['ro-ro'] = "";
$text['label-context']['ru-ru'] = "Контекст";
$text['label-context']['sv-se'] = "Context";
$text['label-context']['uk-ua'] = "Контекст";

$text['header-description']['en-us'] = "Description";
$text['header-description']['en-gb'] = "Description";
$text['header-description']['ar-eg'] = "";
$text['header-description']['de-at'] = "Beschreibung"; //copied from de-de
$text['header-description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['header-description']['de-de'] = "Beschreibung";
$text['header-description']['es-cl'] = "Descripción";
$text['header-description']['es-mx'] = "Descripción"; //copied from es-cl
$text['header-description']['fr-ca'] = "Description"; //copied from fr-fr
$text['header-description']['fr-fr'] = "Description";
$text['header-description']['he-il'] = "תאור";
$text['header-description']['it-it'] = "Descrizione";
$text['header-description']['nl-nl'] = "Omschrijving";
$text['header-description']['pl-pl'] = "Opis";
$text['header-description']['pt-br'] = "Descrição"; //copied from pt-pt
$text['header-description']['pt-pt'] = "Descrição";
$text['header-description']['ro-ro'] = "";
$text['header-description']['ru-ru'] = "Описание";
$text['header-description']['sv-se'] = "Beskrivning";
$text['header-description']['uk-ua'] = "Опис";

$text['description-user_list']['en-us'] = "Define users assigned to this ring group.";
$text['description-user_list']['en-gb'] = "Define users assigned to this ring group.";
$text['description-user_list']['ar-eg'] = "";
$text['description-user_list']['de-at'] = "Weisen Sie diese Rufgruppe Benutzern zu."; //copied from de-de
$text['description-user_list']['de-ch'] = "Weisen Sie diese Rufgruppe Benutzern zu."; //copied from de-de
$text['description-user_list']['de-de'] = "Weisen Sie diese Rufgruppe Benutzern zu.";
$text['description-user_list']['es-cl'] = "Define los usuarios que serán asignados a este grupo de llamado";
$text['description-user_list']['es-mx'] = "Define los usuarios que serán asignados a este grupo de llamado"; //copied from es-cl
$text['description-user_list']['fr-ca'] = "Associer les utilisateurs à ce groupe de sonnerie. "; //copied from fr-fr
$text['description-user_list']['fr-fr'] = "Associer les utilisateurs à ce groupe de sonnerie. ";
$text['description-user_list']['he-il'] = "";
$text['description-user_list']['it-it'] = "Seleziona gli utenti che sono assegnati a questo gruppo di squillo.";
$text['description-user_list']['nl-nl'] = "Deinieer gebruikers die aan deze belgroep toegewezen zijn.";
$text['description-user_list']['pl-pl'] = "Przypisz użytkowników do grupy odbiorców rozmów.";
$text['description-user_list']['pt-br'] = "Atribua os utilizadores que estão associados a essa extensão";
$text['description-user_list']['pt-pt'] = "Associar utilizadores ao grupo.";
$text['description-user_list']['ro-ro'] = "";
$text['description-user_list']['ru-ru'] = "Назначьте пользователей, которые будут членами этой группе вызовов.";
$text['description-user_list']['sv-se'] = "Tilldela användare till denna ringgrupp.";
$text['description-user_list']['uk-ua'] = "";

$text['description-name']['en-us'] = "Enter a name.";
$text['description-name']['en-gb'] = "Enter a name.";
$text['description-name']['ar-eg'] = "";
$text['description-name']['de-at'] = "Geben Sie einen Namen an."; //copied from de-de
$text['description-name']['de-ch'] = "Geben Sie einen Namen an."; //copied from de-de
$text['description-name']['de-de'] = "Geben Sie einen Namen an.";
$text['description-name']['es-cl'] = "Ingrese un nombre.";
$text['description-name']['es-mx'] = "Ingrese un nombre."; //copied from es-cl
$text['description-name']['fr-ca'] = "Insérer un nom."; //copied from fr-fr
$text['description-name']['fr-fr'] = "Insérer un nom.";
$text['description-name']['he-il'] = "הכנס את השם";
$text['description-name']['it-it'] = "Inserire un nome.";
$text['description-name']['nl-nl'] = "Voer een naam in.";
$text['description-name']['pl-pl'] = "Wprowadź nazwę";
$text['description-name']['pt-br'] = "Insira o nome do menu";
$text['description-name']['pt-pt'] = "Introduza um nome.";
$text['description-name']['ro-ro'] = "";
$text['description-name']['ru-ru'] = "Введите Имя.";
$text['description-name']['sv-se'] = "Ange ett namn.";
$text['description-name']['uk-ua'] = "Введіть назву меню";


$text['description-missed_call']['en-us'] = "Select the notification type, and enter the appropriate destination.";
$text['description-missed_call']['en-gb'] = "Select the notification type, and enter the appropriate destination.";
$text['description-missed_call']['ar-eg'] = "";
$text['description-missed_call']['de-at'] = "Wählen Sie den Benachrichtigungstyp und geben Sie das entsprechende Ziel an."; //copied from de-de
$text['description-missed_call']['de-ch'] = "Wählen Sie den Benachrichtigungstyp und geben Sie das entsprechende Ziel an."; //copied from de-de
$text['description-missed_call']['de-de'] = "Wählen Sie den Benachrichtigungstyp und geben Sie das entsprechende Ziel an.";
$text['description-missed_call']['es-cl'] = "Seleccione el tipo de notificación, y entrar en el destino apropiado.";
$text['description-missed_call']['es-mx'] = "Seleccione el tipo de notificación, y entrar en el destino apropiado."; //copied from es-cl
$text['description-missed_call']['fr-ca'] = "Sélectionnez le type de notification, et entrez la destination appropriée."; //copied from fr-fr
$text['description-missed_call']['fr-fr'] = "Sélectionnez le type de notification, et entrez la destination appropriée.";
$text['description-missed_call']['he-il'] = "";
$text['description-missed_call']['it-it'] = "Selezionare il tipo di notifica, e definire la destinazione appropriata.";
$text['description-missed_call']['nl-nl'] = "Kies meldingstype en voer de juiste bestemming in. ";
$text['description-missed_call']['pl-pl'] = "Wybierz typ powiadomienia, i wpisz odpowiednie miejsce przeznaczenia.";
$text['description-missed_call']['pt-br'] = "Selecione o tipo de notificação e digite o destino apropriado."; //copied from pt-pt
$text['description-missed_call']['pt-pt'] = "Selecione o tipo de notificação e digite o destino apropriado.";
$text['description-missed_call']['ro-ro'] = "";
$text['description-missed_call']['ru-ru'] = "Выберите тип уведомления и введите соответствующий пункт назначения.";
$text['description-missed_call']['sv-se'] = "Välj typ anmälan, och ange lämplig destination.";
$text['description-missed_call']['uk-ua'] = "Виберіть тип повідомлення, і ввести відповідний пункт призначення.";

$text['description-extension']['en-us'] = "Enter the extension number.";
$text['description-extension']['en-gb'] = "Enter the extension number.";
$text['description-extension']['ar-eg'] = "";
$text['description-extension']['de-at'] = "Geben Sie eine Nebenstelle an."; //copied from de-de
$text['description-extension']['de-ch'] = "Geben Sie eine Nebenstelle an."; //copied from de-de
$text['description-extension']['de-de'] = "Geben Sie eine Nebenstelle an.";
$text['description-extension']['es-cl'] = "Introduzca el número de extensión.";
$text['description-extension']['es-mx'] = "Introduzca el número de extensión."; //copied from es-cl
$text['description-extension']['fr-ca'] = "Entrez le numéro de poste."; //copied from fr-fr
$text['description-extension']['fr-fr'] = "Entrez le numéro de poste.";
$text['description-extension']['he-il'] = "";
$text['description-extension']['it-it'] = "Inserire il numero di interno.";
$text['description-extension']['nl-nl'] = "Voer het teostelnummer in.";
$text['description-extension']['pl-pl'] = "Wprowadź alfanumeryczny numer wewnętrzny. Domyślna konfiguracja pozwala na 2-7 cyfrowe  numery wewnętrzne";
$text['description-extension']['pt-br'] = "Atribua a extensão e números ao dispositivo";
$text['description-extension']['pt-pt'] = "Digite o número do ramal.";
$text['description-extension']['ro-ro'] = "";
$text['description-extension']['ru-ru'] = "Введите номер внутреннего абонента.";
$text['description-extension']['sv-se'] = "Ange anknytningsnumret.";
$text['description-extension']['uk-ua'] = "";



$text['description-username']['en-us'] = "Enter the API username.";
$text['description-username']['en-gb'] = "Enter the API username.";
$text['description-username']['ar-eg'] = "";
$text['description-username']['de-at'] = "Geben Sie eine Nebenstelle an."; //copied from de-de
$text['description-username']['de-ch'] = "Geben Sie eine Nebenstelle an."; //copied from de-de
$text['description-username']['de-de'] = "Geben Sie eine Nebenstelle an.";
$text['description-username']['es-cl'] = "Introduzca el número de extensión.";
$text['description-username']['es-mx'] = "Introduzca el número de extensión."; //copied from es-cl
$text['description-username']['fr-ca'] = "Entrez le numéro de poste."; //copied from fr-fr
$text['description-username']['fr-fr'] = "Entrez le numéro de poste.";
$text['description-username']['he-il'] = "";
$text['description-username']['it-it'] = "Inserire il numero di interno.";
$text['description-username']['nl-nl'] = "Voer het teostelnummer in.";
$text['description-username']['pl-pl'] = "Wprowadź alfanumeryczny numer wewnętrzny. Domyślna konfiguracja pozwala na 2-7 cyfrowe  numery wewnętrzne";
$text['description-username']['pt-br'] = "Insira o Usuário de autenticação.";
$text['description-username']['pt-pt'] = "Digite o número do ramal.";
$text['description-username']['ro-ro'] = "";
$text['description-username']['ru-ru'] = "Введите номер внутреннего абонента.";
$text['description-username']['sv-se'] = "Ange anknytningsnumret.";
$text['description-username']['uk-ua'] = "";


$text['description-enabled']['en-us'] = "Set the status of this provider.";
$text['description-enabled']['en-gb'] = "Set the status of this ring group.";
$text['description-enabled']['ar-eg'] = "";
$text['description-enabled']['de-at'] = "Setzen Sie den Status dieser Rufgruppe."; //copied from de-de
$text['description-enabled']['de-ch'] = "Setzen Sie den Status dieser Rufgruppe."; //copied from de-de
$text['description-enabled']['de-de'] = "Setzen Sie den Status dieser Rufgruppe.";
$text['description-enabled']['es-cl'] = "Define el estado de este grupo de llamado.";
$text['description-enabled']['es-mx'] = "Define el estado de este grupo de llamado."; //copied from es-cl
$text['description-enabled']['fr-ca'] = "Choisir l'état de ce groupe de sonnerie"; //copied from fr-fr
$text['description-enabled']['fr-fr'] = "Choisir l'état de ce groupe de sonnerie";
$text['description-enabled']['he-il'] = "";
$text['description-enabled']['it-it'] = "Selezionare lo stato di questo gruppo.";
$text['description-enabled']['nl-nl'] = "Kies de status van deze belgroep.";
$text['description-enabled']['pl-pl'] = "Ustaw status tej grupy odbiorców.";
$text['description-enabled']['pt-br'] = "Escolha o estado desta definição";
$text['description-enabled']['pt-pt'] = "Escolher o estado do grupo.";
$text['description-enabled']['ro-ro'] = "";
$text['description-enabled']['ru-ru'] = "Установите статус этой группы вызовов.";
$text['description-enabled']['sv-se'] = "Ange status på denna ringgrupp.";
$text['description-enabled']['uk-ua'] = "";


$text['description-user-enabled']['en-us'] = "Set the status of this user.";
$text['description-user-enabled']['en-gb'] = "Set the status of this ring group.";
$text['description-user-enabled']['ar-eg'] = "";
$text['description-user-enabled']['de-at'] = "Setzen Sie den Status dieser Rufgruppe."; //copied from de-de
$text['description-user-enabled']['de-ch'] = "Setzen Sie den Status dieser Rufgruppe."; //copied from de-de
$text['description-user-enabled']['de-de'] = "Setzen Sie den Status dieser Rufgruppe.";
$text['description-user-enabled']['es-cl'] = "Define el estado de este grupo de llamado.";
$text['description-user-enabled']['es-mx'] = "Define el estado de este grupo de llamado."; //copied from es-cl
$text['description-user-enabled']['fr-ca'] = "Choisir l'état de ce groupe de sonnerie"; //copied from fr-fr
$text['description-user-enabled']['fr-fr'] = "Choisir l'état de ce groupe de sonnerie";
$text['description-user-enabled']['he-il'] = "";
$text['description-user-enabled']['it-it'] = "Selezionare lo stato di questo gruppo.";
$text['description-user-enabled']['nl-nl'] = "Kies de status van deze belgroep.";
$text['description-user-enabled']['pl-pl'] = "Ustaw status tej grupy odbiorców.";
$text['description-user-enabled']['pt-br'] = "Escolha o estado do usuário";
$text['description-user-enabled']['pt-pt'] = "Escolher o estado do grupo.";
$text['description-user-enabled']['ro-ro'] = "";
$text['description-user-enabled']['ru-ru'] = "Установите статус этой группы вызовов.";
$text['description-user-enabled']['sv-se'] = "Ange status på denna ringgrupp.";
$text['description-user-enabled']['uk-ua'] = "";


$text['description-destinations']['en-us'] = "Add destinations and parameters to the ring group.";
$text['description-destinations']['en-gb'] = "Add destinations and parameters to the ring group.";
$text['description-destinations']['ar-eg'] = "";
$text['description-destinations']['de-at'] = "Fügen Sie Ziele und Parameter zu einer Rufgruppe hinzu."; //copied from de-de
$text['description-destinations']['de-ch'] = "Fügen Sie Ziele und Parameter zu einer Rufgruppe hinzu."; //copied from de-de
$text['description-destinations']['de-de'] = "Fügen Sie Ziele und Parameter zu einer Rufgruppe hinzu.";
$text['description-destinations']['es-cl'] = "Agregar destinos y parámetros al grupo de llamado";
$text['description-destinations']['es-mx'] = "Agregar destinos y parámetros al grupo de llamado"; //copied from es-cl
$text['description-destinations']['fr-ca'] = "Ajouter des destinations et des paramètres au groupe de sonnerie."; //copied from fr-fr
$text['description-destinations']['fr-fr'] = "Ajouter des destinations et des paramètres au groupe de sonnerie.";
$text['description-destinations']['he-il'] = "";
$text['description-destinations']['it-it'] = "Inserire destinazioni e parametri per il gruppo di squillo.";
$text['description-destinations']['nl-nl'] = "Voeg bestemming en parameters toe aan de belgroep.";
$text['description-destinations']['pl-pl'] = "Dodaj destynację i parametry grupy odbiorców.";
$text['description-destinations']['pt-br'] = "Destinos de entrada são os DID/DDI, DNIS";
$text['description-destinations']['pt-pt'] = "Adicionar destinos e parâmetros ao grupo.";
$text['description-destinations']['ro-ro'] = "";
$text['description-destinations']['ru-ru'] = "Добавьте адресатов и параметры в группу вызовов.";
$text['description-destinations']['sv-se'] = "Lägg till destinationer och parametrar till ringgruppen.";
$text['description-destinations']['uk-ua'] = "Вхідні номери можуть бути таких типів: DID/DDI, DNIS або Alias  для вхідних дзвінків";


$text['description']['en-us'] = "CRM provider for API integrations and Rest calls.";
$text['description']['en-gb'] = "CRM provider for API integrations and Rest calls.";
$text['description']['ar-eg'] = "";
$text['description']['de-at'] = "Rufgruppen sind gruppierte Ziele, welche über eine vordefinierte Rufstrategie angerufen werden."; //copied from de-de
$text['description']['de-ch'] = "Rufgruppen sind gruppierte Ziele, welche über eine vordefinierte Rufstrategie angerufen werden."; //copied from de-de
$text['description']['de-de'] = "Rufgruppen sind gruppierte Ziele, welche über eine vordefinierte Rufstrategie angerufen werden.";
$text['description']['es-cl'] = "Un grupo de llamado es un conjunto de destino que pueden ser llamados con una estrategía de llamado.";
$text['description']['es-mx'] = "Un grupo de llamado es un conjunto de destino que pueden ser llamados con una estrategía de llamado."; //copied from es-cl
$text['description']['fr-ca'] = "Un groupe de sonnerie est un groupe de destinations pouvant être appelé via une stratégie de sonnerie."; //copied from fr-fr
$text['description']['fr-fr'] = "Un groupe de sonnerie est un groupe de destinations pouvant être appelé via une stratégie de sonnerie.";
$text['description']['he-il'] = "ערוך את פרטי החשבון";
$text['description']['it-it'] = "Un gruppo di squillo è un insieme di destinazioni che squillano secondo una certa strategia.";
$text['description']['nl-nl'] = "En belgroep is een samenstel van bestemmingen die door middel van een strategie gekozen kunnen worden.";
$text['description']['pl-pl'] = "Grupa odbiorców rozmowy składa się z kilku destynacji (numery kom, stacjonarne lub numery wew) na które można dzwonić za pomocą różnych strategii.";
$text['description']['pt-br'] = "Provedor CRM para integrações API e chamadas Rest.";
$text['description']['pt-pt'] = "Um grupo é um conjunto de destinos que podem ser chamados segunda uma determinada estratégia.";
$text['description']['ro-ro'] = "";
$text['description']['ru-ru'] = "Группа вызовов - это набор мест назначения, которые можно вызывать с помощью стратегии вызовов.";
$text['description']['sv-se'] = "En ringgrupp är en uppsättning av destinationer som kan anropas med en ringstrategi.";
$text['description']['uk-ua'] = "Редагування інформації облікового запису";



$text['description_users']['en-us'] = "Users on CRM provider for API integrations and Rest calls.";
$text['description_users']['en-gb'] = "CRM provider for API integrations and Rest calls.";
$text['description_users']['ar-eg'] = "";
$text['description_users']['de-at'] = "Rufgruppen sind gruppierte Ziele, welche über eine vordefinierte Rufstrategie angerufen werden."; //copied from de-de
$text['description_users']['de-ch'] = "Rufgruppen sind gruppierte Ziele, welche über eine vordefinierte Rufstrategie angerufen werden."; //copied from de-de
$text['description_users']['de-de'] = "Rufgruppen sind gruppierte Ziele, welche über eine vordefinierte Rufstrategie angerufen werden.";
$text['description_users']['es-cl'] = "Un grupo de llamado es un conjunto de destino que pueden ser llamados con una estrategía de llamado.";
$text['description_users']['es-mx'] = "Un grupo de llamado es un conjunto de destino que pueden ser llamados con una estrategía de llamado."; //copied from es-cl
$text['description_users']['fr-ca'] = "Un groupe de sonnerie est un groupe de destinations pouvant être appelé via une stratégie de sonnerie."; //copied from fr-fr
$text['description_users']['fr-fr'] = "Un groupe de sonnerie est un groupe de destinations pouvant être appelé via une stratégie de sonnerie.";
$text['description_users']['he-il'] = "ערוך את פרטי החשבון";
$text['description_users']['it-it'] = "Un gruppo di squillo è un insieme di destinazioni che squillano secondo una certa strategia.";
$text['description_users']['nl-nl'] = "En belgroep is een samenstel van bestemmingen die door middel van een strategie gekozen kunnen worden.";
$text['description_users']['pl-pl'] = "Grupa odbiorców rozmowy składa się z kilku destynacji (numery kom, stacjonarne lub numery wew) na które można dzwonić za pomocą różnych strategii.";
$text['description_users']['pt-br'] = "Usuários do CRM para integrações API e chamadas Rest.";
$text['description_users']['pt-pt'] = "Um grupo é um conjunto de destinos que podem ser chamados segunda uma determinada estratégia.";
$text['description_users']['ro-ro'] = "";
$text['description_users']['ru-ru'] = "Группа вызовов - это набор мест назначения, которые можно вызывать с помощью стратегии вызовов.";
$text['description_users']['sv-se'] = "En ringgrupp är en uppsättning av destinationer som kan anropas med en ringstrategi.";
$text['description_users']['uk-ua'] = "Редагування інформації облікового запису";



$text['button-view_all']['en-us'] = "View All";
$text['button-view_all']['en-gb'] = "View All";
$text['button-view_all']['ar-eg'] = "";
$text['button-view_all']['de-at'] = "Alle anzeigen"; //copied from de-de
$text['button-view_all']['de-ch'] = "Alle anzeigen"; //copied from de-de
$text['button-view_all']['de-de'] = "Alle anzeigen";
$text['button-view_all']['es-cl'] = "Mostrar Todos";
$text['button-view_all']['es-mx'] = "Mostrar Todos"; //copied from es-cl
$text['button-view_all']['fr-ca'] = "Tout Montrer"; //copied from fr-fr
$text['button-view_all']['fr-fr'] = "Tout Montrer";
$text['button-view_all']['he-il'] = "הצג הכל";
$text['button-view_all']['it-it'] = "Mostra Tutto";
$text['button-view_all']['nl-nl'] = "Toon Alles";
$text['button-view_all']['pl-pl'] = "Pokaż wszystkie";
$text['button-view_all']['pt-br'] = "Mostrar Todos"; //copied from pt-pt
$text['button-view_all']['pt-pt'] = "Mostrar Todos";
$text['button-view_all']['ro-ro'] = "";
$text['button-view_all']['ru-ru'] = "Показать Все";
$text['button-view_all']['sv-se'] = "Visa Allt";
$text['button-view_all']['uk-ua'] = "Показати всі";


$text['button-users']['en-us'] = "Users";
$text['button-users']['en-gb'] = "Users";
$text['button-users']['ar-eg'] = "";
$text['button-users']['de-at'] = "Alle anzeigen"; //copied from de-de
$text['button-users']['de-ch'] = "Alle anzeigen"; //copied from de-de
$text['button-users']['de-de'] = "Alle anzeigen";
$text['button-users']['es-cl'] = "Usuários";
$text['button-users']['es-mx'] = "Usuários"; //copied from es-cl
$text['button-users']['fr-ca'] = "Tout Montrer"; //copied from fr-fr
$text['button-users']['fr-fr'] = "Tout Montrer";
$text['button-users']['he-il'] = "הצג הכל";
$text['button-users']['it-it'] = "Mostra Tutto";
$text['button-users']['nl-nl'] = "Toon Alles";
$text['button-users']['pl-pl'] = "Pokaż wszystkie";
$text['button-users']['pt-br'] = "Usuários"; //copied from pt-pt
$text['button-users']['pt-pt'] = "Usuários";
$text['button-users']['ro-ro'] = "";
$text['button-users']['ru-ru'] = "Показать Все";
$text['button-users']['sv-se'] = "Visa Allt";
$text['button-users']['uk-ua'] = "Показати всі";


$text['button-providers']['en-us'] = "Providers";
$text['button-providers']['en-gb'] = "Providers";
$text['button-providers']['ar-eg'] = "";
$text['button-providers']['de-at'] = "Alle anzeigen"; //copied from de-de
$text['button-providers']['de-ch'] = "Alle anzeigen"; //copied from de-de
$text['button-providers']['de-de'] = "Alle anzeigen";
$text['button-providers']['es-cl'] = "Provedores";
$text['button-providers']['es-mx'] = "Provedores"; //copied from es-cl
$text['button-providers']['fr-ca'] = "Tout Montrer"; //copied from fr-fr
$text['button-providers']['fr-fr'] = "Tout Montrer";
$text['button-providers']['he-il'] = "הצג הכל";
$text['button-providers']['it-it'] = "Mostra Tutto";
$text['button-providers']['nl-nl'] = "Toon Alles";
$text['button-providers']['pl-pl'] = "Pokaż wszystkie";
$text['button-providers']['pt-br'] = "Provedores"; //copied from pt-pt
$text['button-providers']['pt-pt'] = "Provedores";
$text['button-providers']['ro-ro'] = "";
$text['button-providers']['ru-ru'] = "Показать Все";
$text['button-providers']['sv-se'] = "Visa Allt";
$text['button-providers']['uk-ua'] = "Показати всі";

?>
